src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KS_Actividad__c</fullName>
        <label>Actividad</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Actividad</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <label>Canal</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KS_Actividad__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Canal</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Grupo_de_ctas_deudor__c</fullName>
        <label>Grupo de ctas. deudor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Grupo_de_ctas_deudor</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Id_SAP__c</fullName>
        <externalId>true</externalId>
        <label>Id SAP</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>KS_Idioma__c</fullName>
        <label>Idioma</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Idiomas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_N_de_telefono_2__c</fullName>
        <label>Nº de telefono 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>KS_N_identificacion_fiscal_suplementario__c</fullName>
        <label>Nº identificación fiscal suplementario</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Nombre_2__c</fullName>
        <label>Nombre Fiscal</label>
        <length>71</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Numero_de_identificacion_fiscal_1__c</fullName>
        <label>NIF</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>KS_Distribuidores_SAP</fullName>
        <active>true</active>
        <description>Tipo de registro para albergar clientes distribuidores provenientes de SAP</description>
        <label>Distribuidores SAP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>KS_IDSAP__c</fullName>
        <inlineHelpText>El formato del campo Número de Personal (ID SAP) es: 00000XXX (8 carácteres en total, donde el id va precedido de tantos 0s como haga falta para completar la longitud)</inlineHelpText>
        <label>Número de Personal (SAP)</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Idiomas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ES</fullName>
        <default>true</default>
        <label>ES</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
    </customValue>
    <customValue>
        <fullName>ZF</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>CAT</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Contactos / Cliente Distribucion --&gt; CARGADO</description>
    <masterLabel>Idiomas</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Actividad.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alojamiento Turístico</fullName>
    </customValue>
    <customValue>
        <fullName>Arquitectura</fullName>
    </customValue>
    <customValue>
        <fullName>Bancos y cajas</fullName>
    </customValue>
    <customValue>
        <fullName>Centros comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Compañías de Seguros</fullName>
    </customValue>
    <customValue>
        <fullName>Consultoras Inmobiliarias</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidor</fullName>
    </customValue>
    <customValue>
        <fullName>Educación</fullName>
    </customValue>
    <customValue>
        <fullName>Gran empresa Privada</fullName>
    </customValue>
    <customValue>
        <fullName>Ingeniería</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Integrador</fullName>
    </customValue>
    <customValue>
        <fullName>Interiorista</fullName>
    </customValue>
    <customValue>
        <fullName>Laboratorio</fullName>
    </customValue>
    <customValue>
        <fullName>Moda y Complementos</fullName>
    </customValue>
    <customValue>
        <fullName>Organismos Oficiales</fullName>
    </customValue>
    <customValue>
        <fullName>Reformistas</fullName>
    </customValue>
    <customValue>
        <fullName>Restauración</fullName>
    </customValue>
    <customValue>
        <fullName>Sanidad</fullName>
    </customValue>
    <customValue>
        <fullName>TEI</fullName>
    </customValue>
    <customValue>
        <fullName>Alimentación</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion/Gremio Instaladores</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion DME</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion Domoticas</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones EE y VE</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones Prensa</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones Sectorial</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion Light Designers e iluminacion</fullName>
    </customValue>
    <customValue>
        <fullName>Automoción</fullName>
    </customValue>
    <customValue>
        <fullName>Bienestar</fullName>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en cuentas</description>
    <masterLabel>Actividad</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Canal.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Distribuidores CRM</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Prescriptores</fullName>
    </customValue>
    <customValue>
        <fullName>Clientes finales</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidores SAP</fullName>
    </customValue>
    <customValue>
        <fullName>Varios</fullName>
        <isActive>false</isActive>
        <label>Varios</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en Cuentas</description>
    <masterLabel>Canal</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Grupo_de_ctas_deudor.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
    </customValue>
    <customValue>
        <fullName>0002</fullName>
    </customValue>
    <customValue>
        <fullName>0003</fullName>
    </customValue>
    <customValue>
        <fullName>0004</fullName>
    </customValue>
    <customValue>
        <fullName>0012</fullName>
    </customValue>
    <customValue>
        <fullName>Z001</fullName>
    </customValue>
    <customValue>
        <fullName>Z010</fullName>
    </customValue>
    <customValue>
        <fullName>Z011</fullName>
    </customValue>
    <customValue>
        <fullName>Z014</fullName>
    </customValue>
    <customValue>
        <fullName>Z015</fullName>
    </customValue>
    <customValue>
        <fullName>ZE01</fullName>
    </customValue>
    <customValue>
        <fullName>ZEXT</fullName>
    </customValue>
    <customValue>
        <fullName>ZINT</fullName>
    </customValue>
    <customValue>
        <fullName>Z009</fullName>
    </customValue>
    <customValue>
        <fullName>Z012</fullName>
    </customValue>
    <customValue>
        <fullName>Z013</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Cliente Distribucion --&gt; CARGADO</description>
    <masterLabel>Grupo de ctas. deudor</masterLabel>
</GlobalValueSet>

src/classes/ConvertAttachmentsKSUtils.cls
global class ConvertAttachmentsKSUtils {

    global static Map<String, ID> getRecordType() {
        
        Map<String, ID> rtM = new Map<String, ID>();
        for (RecordType rt : [SELECT ID, DeveloperName FROM RecordType]) {
            rtM.put(rt.DeveloperName, rt.ID);
        }
        return rtM;
    }
    
    global static Profile getProfile() {
        return [SELECT ID, Name FROM Profile WHERE Name = 'Usuario estándar' or Name = 'Standard User' LIMIT 1];
    }    
    
    global static User newUser( ID profileId, String firstName, String lastName, String email ) {
        Integer rand = Math.round( Math.random() * 1000 );
        return new User(
            isActive = true,
            profileId = profileId,
            alias = firstName.substring(0,1) + lastName.substring(1,5),
            firstName = firstName,
            lastName = lastName,
            email = email,
            username = rand + email,
            emailEncodingKey = 'UTF-8',
            languageLocaleKey = 'en_US',
            localeSidKey = 'en_US',
            timeZoneSidKey = 'America/Chicago',
            KS_IDSAP__c = ConvertAttachmentsKSUtils.generateRandomDocument(8)
        );
    }
    
    global static Account newAccount( ID ownerID, String name, Integer accId, Map<String, ID> rtM ) {
        
        ID rt = rtM.get('KS_Distribuidores_SAP');
        Account acc = 
            new Account(
                RecordTypeId = rt,
                Name = name+accId,
                KS_Id_SAP__c = 'IDSAPTEST1234-'+accId,
                Phone = '666666666',
                BillingCountryCode = 'ES',
                BillingCity = 'Barcelona',
                BillingPostalCode = '08907',
                BillingStreet = 'Calle de gracia',
                KS_Grupo_de_ctas_deudor__c = '0001',
                KS_Idioma__c = 'ES',
                KS_Nombre_2__c = 'Cliente Distribuidor TEST',
                KS_N_identificacion_fiscal_suplementario__c = '1',
                KS_Numero_de_identificacion_fiscal_1__c = '1',
                KS_N_de_telefono_2__c = '1',
                KS_Actividad__c = 'Distribuidor',
                KS_Canal__c = 'Distribuidores SAP'
            );
        if (ownerID != null) { acc.OwnerId = OwnerId; }
        return acc;
    }

    global static string generateRandomDocument(integer len){
        string document = '';
        string nums = '0123456789';
        for(integer i=0; i<len; i++){
            Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), nums.length());
            document += nums.substring(idx,idx+1);
        }
        return document;
    }
    
}