src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KS_C_digo_Postal__c</fullName>
        <label>Código Postal</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Calle__c</fullName>
        <label>Calle</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ciudad__c</fullName>
        <label>Ciudad</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Estado_o_Provincia__c</fullName>
        <label>Estado o Provincia</label>
        <length>38</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Pais__c</fullName>
        <label>País</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Codigo_Pais</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Tipo_de_via__c</fullName>
        <label>Tipo de via</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Tipo_de_via</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>KS_Calle__c</fullName>
        <formula>Account.BillingStreet</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Calle</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ciudad__c</fullName>
        <formula>Account.BillingCity</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ciudad</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Pais__c</fullName>
        <formula>Account.BillingCountry</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>País</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>KS_C_digo_Postal__c</fullName>
        <inlineHelpText>Este campo es obligatorio para la conversión</inlineHelpText>
        <label>Código_Postal</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Calle__c</fullName>
        <inlineHelpText>Este campo es obligatorio para la conversión</inlineHelpText>
        <label>Nombre de la vía</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ciudad__c</fullName>
        <inlineHelpText>Este campo es obligatorio para la conversión</inlineHelpText>
        <label>Ciudad</label>
        <length>38</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Consentimiento__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Uno de los campos de tratamiento es obligatorio para poder convertir</inlineHelpText>
        <label>Consentimiento</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Estado_o_Provincia__c</fullName>
        <inlineHelpText>Este campo es obligatorio para la conversión</inlineHelpText>
        <label>Estado / Provincia</label>
        <length>38</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_N_m_portal_piso_puerta_y_resto_domici__c</fullName>
        <inlineHelpText>Este campo es obligatorio para la conversión</inlineHelpText>
        <label>Núm, portal, piso, puerta y resto dom.</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Pais__c</fullName>
        <inlineHelpText>Este campo es obligatorio para la conversión</inlineHelpText>
        <label>Pais</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Codigo_Pais</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_RechazoComunicaciones__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Uno de los campos de tratamiento es obligatorio para poder convertir</inlineHelpText>
        <label>Rechazo de comunicaciones</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Tipo_de_via__c</fullName>
        <inlineHelpText>Este campo es obligatorio para la conversión</inlineHelpText>
        <label>Tipo de vía</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Tipo_de_via</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/globalValueSets/Tipo_de_via.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CALLE</fullName>
    </customValue>
    <customValue>
        <fullName>CARRER</fullName>
    </customValue>
    <customValue>
        <fullName>KALEA</fullName>
    </customValue>
    <customValue>
        <fullName>AVENIDA</fullName>
    </customValue>
    <customValue>
        <fullName>AVINGUDA</fullName>
    </customValue>
    <customValue>
        <fullName>ETORBIDEA</fullName>
    </customValue>
    <customValue>
        <fullName>ALAMEDA</fullName>
    </customValue>
    <customValue>
        <fullName>ALBEREDA</fullName>
    </customValue>
    <customValue>
        <fullName>ALDEA</fullName>
    </customValue>
    <customValue>
        <fullName>AUTOPISTA</fullName>
    </customValue>
    <customValue>
        <fullName>AUTOVIA</fullName>
    </customValue>
    <customValue>
        <fullName>AUTOVÍA</fullName>
    </customValue>
    <customValue>
        <fullName>AUZUNEA</fullName>
    </customValue>
    <customValue>
        <fullName>BARRI</fullName>
    </customValue>
    <customValue>
        <fullName>BARRIADA</fullName>
    </customValue>
    <customValue>
        <fullName>BARRIO</fullName>
    </customValue>
    <customValue>
        <fullName>BIDEA</fullName>
    </customValue>
    <customValue>
        <fullName>BULEVAR</fullName>
    </customValue>
    <customValue>
        <fullName>CALLEJÓN</fullName>
    </customValue>
    <customValue>
        <fullName>CALZADA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMÍ</fullName>
    </customValue>
    <customValue>
        <fullName>CAMINO</fullName>
    </customValue>
    <customValue>
        <fullName>CAMIÑO</fullName>
    </customValue>
    <customValue>
        <fullName>CARRERA</fullName>
    </customValue>
    <customValue>
        <fullName>CARRETERA</fullName>
    </customValue>
    <customValue>
        <fullName>CONCELLO</fullName>
    </customValue>
    <customValue>
        <fullName>CUESTA</fullName>
    </customValue>
    <customValue>
        <fullName>ENPARANTZA</fullName>
    </customValue>
    <customValue>
        <fullName>ENTITATEA</fullName>
    </customValue>
    <customValue>
        <fullName>ERREPIDEA</fullName>
    </customValue>
    <masterLabel>Tipo de via</masterLabel>
</GlobalValueSet>

src/classes/KS_RGProteccionDatos_TEST.cls
@isTest
public class KS_RGProteccionDatos_TEST {

    @testSetup static void TEST_SETUP_RGProteccionDatos() {
        Lead can = new Lead();
        can.FirstName = 'Kaizen';
        can.LastName = 'Step';
        can.Phone = '333222111';
        can.Email = 'kstep@kaizen.com';
        can.Company = 'KaizenStep';
        can.KS_Tipo_de_via__c = 'AVENIDA';
        can.KS_Calle__c = 'MERIDIANA';
        can.KS_N_m_portal_piso_puerta_y_resto_domici__c = '354, 5A';
        can.KS_C_digo_Postal__c = '08027';
        can.KS_Ciudad__c = 'BARCELONA';
        can.KS_Estado_o_Provincia__c = 'BARCELONA';
        can.KS_Pais__c = 'ES';
        can.KS_RechazoComunicaciones__c = true;
        insert can;
        
        KS_Trigger_Test.disableTrigger();
        KS_TEST_FUNCTIONS tstfnc = new KS_TEST_FUNCTIONS();
        Map<String, ID> rtM = KS_TEST_FUNCTIONS.getRecordTypeStatic();
        Account acc = tstfnc.createAccDistribuidor(rtM);
        Contact con = tstfnc.createContact(acc);
        KS_Trigger_Test.enableTrigger();
    }
    public static testMethod void TEST_RGProteccionDatos_Lead() {
        Lead sobj = [SELECT ID FROM Lead limit 1];
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(sobj);
        KS_RGProteccionDatos_Controller control = new KS_RGProteccionDatos_Controller(sc);
        control.led.KS_Consentimiento__c = true;
        control.led.KS_RechazoComunicaciones__c = false;
        control.save();
        control.cancel();
        control.getReturnURL();
        control.led = null;
        control.getReturnURL();
    }
    public static testMethod void TEST_RGProteccionDatos_Account() {
        Account sobj = [SELECT ID FROM Account limit 1];
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(sobj);
        KS_RGProteccionDatos_Controller control = new KS_RGProteccionDatos_Controller(sc);
        control.save();
        control.cancel();
        control.getReturnURL();
    }
    public static testMethod void TEST_RGProteccionDatos_Contact() {
        Contact sobj = [SELECT ID FROM Contact limit 1];
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(sobj);
        KS_RGProteccionDatos_Controller control = new KS_RGProteccionDatos_Controller(sc);
        control.save();
        control.cancel();
        control.getReturnURL();
    }
    public static testMethod void TEST_RGProteccionDatos_STATIC() {
        KS_RGProteccionDatos_Controller.getIsAdmin();
    }
}