src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KS_Actividad__c</fullName>
        <label>Actividad</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Actividad</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <label>Canal</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KS_Actividad__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Canal</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>KS_Idioma__c</fullName>
        <label>Idioma</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Idiomas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_N_de_telefono_2__c</fullName>
        <label>Nº de telefono 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>KS_N_de_telefono_3__c</fullName>
        <label>Nº de telefono 3</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>KS_Sector__c</fullName>
        <label>Sector</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>KS_Actividad__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Sector</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Subactividad__c</fullName>
        <label>Subactividad</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>KS_Actividad__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Subactividad</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>KS_Funcion_en_empresa__c</fullName>
        <label>Función en empresa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Funcion_en_empresa</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Idioma__c</fullName>
        <label>Idioma</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Idiomas</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KS_Debug__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto que contiene los registros de depuración de los WDSLs</description>
    <fields>
        <fullName>KS_Descripcion__c</fullName>
        <label>Descripción</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>KS_Master_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta Maestra</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Histórico Merge</relationshipLabel>
        <relationshipName>DebugMergeCuenta</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Master_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contacto Maestro</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Histórico Merge</relationshipLabel>
        <relationshipName>DebugMergeContacto</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Master_Marca__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marca Maestra</label>
        <referenceTo>KS_Organizacion_Cliente__c</referenceTo>
        <relationshipLabel>Histórico Merge</relationshipLabel>
        <relationshipName>DebugMergeMarca</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Master_Owner__c</fullName>
        <label>Propietario Maestro</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Depuración</label>
    <nameField>
        <label>Identificador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Depuraciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Fusion__c.object
<CustomObject>
    <fields>
        <fullName>KS_Acc_Actividad__c</fullName>
        <label>KS_Acc_Actividad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Calle__c</fullName>
        <label>KS_Acc_Calle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Canal__c</fullName>
        <label>KS_Acc_Canal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Ciudad__c</fullName>
        <label>KS_Acc_Ciudad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Codigo_Postal__c</fullName>
        <label>KS_Acc_Codigo_Postal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Correo__c</fullName>
        <label>KS_Acc_Correo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Estado_Provincia__c</fullName>
        <label>KS_Acc_Estado_Provincia</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Pais__c</fullName>
        <label>KS_Acc_Pais</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Sector__c</fullName>
        <label>KS_Acc_Sector</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Subactividad__c</fullName>
        <label>KS_Acc_Subactividad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Telefono_2__c</fullName>
        <label>KS_Acc_Telefono_2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Telefono_3__c</fullName>
        <label>KS_Acc_Telefono_3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Telefono__c</fullName>
        <label>KS_Acc_Telefono</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Calle__c</fullName>
        <label>KS_Ctc_Calle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Ciudad__c</fullName>
        <label>KS_Ctc_Ciudad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Codigo_Postal__c</fullName>
        <label>KS_Ctc_Codigo_Postal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Correo__c</fullName>
        <label>KS_Ctc_Correo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Estado_Provincia__c</fullName>
        <label>KS_Ctc_Estado_Provincia</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Funcion_en_empresa__c</fullName>
        <label>KS_Ctc_Funcion_en_empresa</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Idioma__c</fullName>
        <label>KS_Ctc_Idioma</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Movil__c</fullName>
        <label>KS_Ctc_Movil</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Pais__c</fullName>
        <label>KS_Ctc_Pais</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Telefono_Particular__c</fullName>
        <label>KS_Ctc_Telefono_Particular</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Telefono__c</fullName>
        <label>KS_Ctc_Telefono</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Id_Principal__c</fullName>
        <label>KS_Id_Principal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Fusion</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Fusion ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fusiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Idiomas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ES</fullName>
        <default>true</default>
        <label>ES</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
    </customValue>
    <customValue>
        <fullName>ZF</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>CAT</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Contactos / Cliente Distribucion --&gt; CARGADO</description>
    <masterLabel>Idiomas</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Actividad.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alojamiento Turístico</fullName>
    </customValue>
    <customValue>
        <fullName>Arquitectura</fullName>
    </customValue>
    <customValue>
        <fullName>Bancos y cajas</fullName>
    </customValue>
    <customValue>
        <fullName>Centros comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Compañías de Seguros</fullName>
    </customValue>
    <customValue>
        <fullName>Consultoras Inmobiliarias</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidor</fullName>
    </customValue>
    <customValue>
        <fullName>Educación</fullName>
    </customValue>
    <customValue>
        <fullName>Gran empresa Privada</fullName>
    </customValue>
    <customValue>
        <fullName>Ingeniería</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Integrador</fullName>
    </customValue>
    <customValue>
        <fullName>Interiorista</fullName>
    </customValue>
    <customValue>
        <fullName>Laboratorio</fullName>
    </customValue>
    <customValue>
        <fullName>Moda y Complementos</fullName>
    </customValue>
    <customValue>
        <fullName>Organismos Oficiales</fullName>
    </customValue>
    <customValue>
        <fullName>Reformistas</fullName>
    </customValue>
    <customValue>
        <fullName>Restauración</fullName>
    </customValue>
    <customValue>
        <fullName>Sanidad</fullName>
    </customValue>
    <customValue>
        <fullName>TEI</fullName>
    </customValue>
    <customValue>
        <fullName>Alimentación</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion/Gremio Instaladores</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion DME</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion Domoticas</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones EE y VE</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones Prensa</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones Sectorial</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion Light Designers e iluminacion</fullName>
    </customValue>
    <customValue>
        <fullName>Automoción</fullName>
    </customValue>
    <customValue>
        <fullName>Bienestar</fullName>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en cuentas</description>
    <masterLabel>Actividad</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Canal.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Distribuidores CRM</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Prescriptores</fullName>
    </customValue>
    <customValue>
        <fullName>Clientes finales</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidores SAP</fullName>
    </customValue>
    <customValue>
        <fullName>Varios</fullName>
        <isActive>false</isActive>
        <label>Varios</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en Cuentas</description>
    <masterLabel>Canal</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Funcion_en_empresa.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Compras</fullName>
    </customValue>
    <customValue>
        <fullName>Gerencia</fullName>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Servicios Técnicos</fullName>
    </customValue>
    <customValue>
        <fullName>Especialista de Producto</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Administración</fullName>
    </customValue>
    <customValue>
        <fullName>Logística</fullName>
    </customValue>
    <customValue>
        <fullName>Calidad</fullName>
    </customValue>
    <customValue>
        <fullName>Operario</fullName>
    </customValue>
    <customValue>
        <fullName>Arquitecto</fullName>
    </customValue>
    <customValue>
        <fullName>Interiorista</fullName>
        <isActive>false</isActive>
        <label>Interiorista</label>
    </customValue>
    <customValue>
        <fullName>Otros</fullName>
        <isActive>false</isActive>
        <label>Otros</label>
    </customValue>
    <customValue>
        <fullName>Fabricante</fullName>
        <isActive>false</isActive>
        <label>Fabricante</label>
    </customValue>
    <customValue>
        <fullName>Tienda</fullName>
        <isActive>false</isActive>
        <label>Tienda</label>
    </customValue>
    <customValue>
        <fullName>Proyectos</fullName>
        <isActive>false</isActive>
        <label>Proyectos</label>
    </customValue>
    <customValue>
        <fullName>Dueño</fullName>
        <isActive>false</isActive>
        <label>Dueño</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado en objeto Contactos</description>
    <masterLabel>Función en empresa</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Sector.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Residencial</fullName>
    </customValue>
    <customValue>
        <fullName>Terciario</fullName>
    </customValue>
    <customValue>
        <fullName>Hotelero</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Otros</fullName>
    </customValue>
    <customValue>
        <fullName>Edificios administrativos</fullName>
        <isActive>false</isActive>
        <label>Edificios administrativos</label>
    </customValue>
    <customValue>
        <fullName>Industrial (Naves, Fábricas, etc...)</fullName>
        <isActive>false</isActive>
        <label>Industrial (Naves, Fábricas, etc...)</label>
    </customValue>
    <customValue>
        <fullName>Educación</fullName>
        <isActive>false</isActive>
        <label>Educación</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en cuentas</description>
    <masterLabel>Sector</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Subactividad.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Agencia Viajes</fullName>
    </customValue>
    <customValue>
        <fullName>Agua</fullName>
    </customValue>
    <customValue>
        <fullName>Alojamientos Rurales</fullName>
    </customValue>
    <customValue>
        <fullName>Alquiler automobiles</fullName>
    </customValue>
    <customValue>
        <fullName>Aparejadores</fullName>
    </customValue>
    <customValue>
        <fullName>Apartamentos turísticos</fullName>
    </customValue>
    <customValue>
        <fullName>Arquitectura</fullName>
    </customValue>
    <customValue>
        <fullName>Auditor Energético</fullName>
    </customValue>
    <customValue>
        <fullName>Bancos y cajas</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Belleza</fullName>
    </customValue>
    <customValue>
        <fullName>Bolsos</fullName>
    </customValue>
    <customValue>
        <fullName>Camping</fullName>
    </customValue>
    <customValue>
        <fullName>Central, del Estado</fullName>
    </customValue>
    <customValue>
        <fullName>Centros comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Centros de día</fullName>
    </customValue>
    <customValue>
        <fullName>Centros de Salud</fullName>
    </customValue>
    <customValue>
        <fullName>Comarcal: Diputación y Autonómicas</fullName>
    </customValue>
    <customValue>
        <fullName>Comercializador</fullName>
    </customValue>
    <customValue>
        <fullName>Compañías de Seguros</fullName>
    </customValue>
    <customValue>
        <fullName>Concesionarios automoción</fullName>
    </customValue>
    <customValue>
        <fullName>Consejerías de Sanidad</fullName>
    </customValue>
    <customValue>
        <fullName>Consultoras Inmobiliarias</fullName>
    </customValue>
    <customValue>
        <fullName>Cuadrista</fullName>
    </customValue>
    <customValue>
        <fullName>Deporte</fullName>
    </customValue>
    <customValue>
        <fullName>Direccion de Obra</fullName>
    </customValue>
    <customValue>
        <fullName>DMX</fullName>
    </customValue>
    <customValue>
        <fullName>Edificación</fullName>
    </customValue>
    <customValue>
        <fullName>Educación</fullName>
    </customValue>
    <customValue>
        <fullName>Eléctrico</fullName>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en cuentas</description>
    <masterLabel>Subactividad</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/KS_MergeTool_Utils.cls
global without sharing class KS_MergeTool_Utils {

    public static Map<Id,Account> getAccountMapBySetId(Set<ID> idSet) {
        return new Map<Id,Account>(
            [SELECT Id, Name, KS_Canal__c, KS_Actividad__c, KS_Subactividad__c, KS_Sector__c, 
             BillingStreet, BillingCity, BillingPostalCode, BillingState, BillingCountryCode,
             Phone, KS_N_de_telefono_2__c, KS_N_de_telefono_3__c, KS_Email__c
             FROM Account WHERE Id In :idSet]
        );
    }
    public static Map<Id,String> getAccountOwnerUserNameMap(Set<ID> idSet) {
        Map<Id,String> mapa = new Map<Id,String>();
        for (Account acc : [SELECT Id, Owner.UserName FROM Account WHERE Id In :idSet]) {
            mapa.put(acc.ID, acc.Owner.UserName);
        }
        return mapa;
    }
    
    public static Map<Id,Contact> getContactMapBySetId(Set<ID> idSet) {
        return new Map<Id,Contact>(
            [SELECT Id, Name, OtherStreet, OtherCity, OtherPostalCode, OtherState, OtherCountry,
             Phone, MobilePhone, HomePhone, Email, KS_Funcion_en_empresa__c, KS_Idioma__c
             FROM Contact WHERE Id In :idSet]
        );
    }
    public static Map<Id,String> getContactOwnerUserNameMap(Set<ID> idSet) {
        Map<Id,String> mapa = new Map<Id,String>();
        for (Contact con : [SELECT Id, Owner.UserName FROM Contact WHERE Id In :idSet]) {
            mapa.put(con.ID, con.Owner.UserName);
        }
        return mapa;
    }
    
    public static KS_Debug__c debugNew(String cls, String apx, String mtd, KS_Fusion__c fus) {
        return KS_Debug_Utils.newFusionDebug(cls, apx, mtd, fus.KS_Id_Principal__c);
    }
    public static KS_Debug__c debugDesc(String cls, String apx, String mtd, String dsc, KS_Fusion__c fus) {
        return KS_Debug_Utils.newFusionDebugDesc(cls, apx, mtd, dsc, fus.KS_Id_Principal__c);
    }

    public static Map<String, String> accountFusionFieldsMap() {
        Map<String, String> campos = new Map<String, String>();
        campos.put('KS_Acc_Calle__c', 'BillingStreet');
        campos.put('KS_Acc_Ciudad__c', 'BillingCity');
        campos.put('KS_Acc_Codigo_Postal__c', 'BillingPostalCode');
        campos.put('KS_Acc_Estado_Provincia__c', 'BillingState');
        campos.put('KS_Acc_Pais__c', 'BillingCountryCode');
        campos.put('KS_Acc_Telefono__c', 'Phone');
        campos.put('KS_Acc_Telefono_2__c', 'KS_N_de_telefono_2__c');
        campos.put('KS_Acc_Telefono_3__c', 'KS_N_de_telefono_3__c');
        campos.put('KS_Acc_Correo__c', 'KS_Email__c');
        campos.put('KS_Acc_Canal__c', 'KS_Canal__c');
        campos.put('KS_Acc_Actividad__c', 'KS_Actividad__c');
        campos.put('KS_Acc_Subactividad__c', 'KS_Subactividad__c');
        campos.put('KS_Acc_Sector__c', 'KS_Sector__c');
        return campos;
    }
    public static Map<String, String> contactsFusionFieldsMap() {
        Map<String, String> campos = new Map<String, String>();
        campos.put('KS_Ctc_Calle__c', 'OtherStreet');
        campos.put('KS_Ctc_Ciudad__c', 'OtherCity');
        campos.put('KS_Ctc_Codigo_Postal__c', 'OtherPostalCode');
        campos.put('KS_Ctc_Estado_Provincia__c', 'OtherState');
        campos.put('KS_Ctc_Pais__c', 'OtherCountry');
        campos.put('KS_Ctc_Telefono__c', 'Phone');
        campos.put('KS_Ctc_Movil__c', 'MobilePhone');
        campos.put('KS_Ctc_Telefono_Particular__c', 'HomePhone');
        campos.put('KS_Ctc_Correo__c', 'Email');
        campos.put('KS_Ctc_Funcion_en_empresa__c', 'KS_Funcion_en_empresa__c');
        campos.put('KS_Ctc_Idioma__c', 'KS_Idioma__c');
        return campos;
    }
    public static Boolean campoNotFull(String campo, SObject obj) {
        return obj.get(campo) != null && ((String)obj.get(campo) != '');
    }
    
    public static List<KS_Debug__c> debugAccount(String apx, String mtd, KS_Fusion__c fus, Account acc, Account ac2, Account ac3, ID rtID, String owner) {
        return KS_MergeTool_Utils.debugSObject('Account', apx, mtd, fus, 'Name', acc, new List<sObject>{ac2, ac3}, KS_MergeTool_Utils.accountFusionFieldsMap(), rtID, owner);
    }
    public static List<KS_Debug__c> debugContact(String apx, String mtd, KS_Fusion__c fus, Contact con, Contact co2, Contact co3, ID rtID, String owner) {
        return KS_MergeTool_Utils.debugSObject('Contact', apx, mtd, fus, 'Name', con, new List<sObject>{co2, co3}, KS_MergeTool_Utils.contactsFusionFieldsMap(), rtID, owner);
    }
    
    // cls = clase del objeto fusionado (Account, Contact)
    // apx = clase apex que llama
    // mtd = metodo apex que llama
    // fus = objeto Fusion a procesar
    // keyfield = nombre de campo identificativo de objetos
    // sObj = objetos principal de la fusión
    // sObjLst = lista de objetos vinculados a fusión (duplicado_1, duplicado_2)
    // campos = mapeo nombre campos <fusion, objeto>
    // rtID = Debug RecordTypeId
    // owner = propietario/s del objeto fusionado
    public Static List<KS_Debug__c> debugSObject(String cls, String apx, String mtd, KS_Fusion__c fus, String keyField, sObject sObj, List<sObject> sObjLst, Map<String, String> campos, ID rtID, String owner) {
        List<KS_Debug__c> debugList = new List<KS_Debug__c>();
        
        // Se creará un objeto fusión por cada duplicado
        // se guardará el valor original de tanto el principal como el duplicado
        // todo en campos String, se separará ambos valores por una ; y un >, o sea: valor1 ; valor2 ; valor3 > valorNuevo
        sObjLst = sObjLst != null ? sObjLst : new List<sObject>();
        for (sObject sObjDupli : sObjLst) {
            if (sObjDupli == null) {continue;}
            KS_Debug__c debug = KS_Debug_Utils.debugObjectFieldsLst(
                cls, apx, mtd, fus.KS_Id_Principal__c, keyField, 
                fus, new List<sObject>{sObj, sObjDupli}, campos);
            
            debug.KS_Descripcion__c = 'Histórico de: \r\n' + sObj.get(keyField) + '; \r\n' + sObjDupli.get(keyField);
            debug.RecordTypeId = rtID; debugList.add(debug);
            debug.KS_Master_Owner__c = owner;
            if (cls == 'Account') { debug.KS_Master_Account__c = fus.KS_Id_Principal__c; }
            if (cls == 'Contact') { debug.KS_Master_Contact__c = fus.KS_Id_Principal__c; }
            //if (cls == 'Organización Cliente') { debug.KS_Master_Marca__c = fus.KS_Id_Principal__c; }
        }
        
        return debugList;
    }
    
    /*

	MAP CAMPOS FUSION > OBJETO
	MAP CAMPOS OBJETO > DEPURACIÓN

	*/
}