src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KS_Actividad__c</fullName>
        <label>Actividad</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Actividad</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <label>Canal</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KS_Actividad__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Canal</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Grupo_de_ctas_deudor__c</fullName>
        <label>Grupo de ctas. deudor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Grupo_de_ctas_deudor</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Id_SAP__c</fullName>
        <externalId>true</externalId>
        <label>Id SAP</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>KS_Id_Salesforce__c</fullName>
        <displayFormat>ID-{0000000}</displayFormat>
        <externalId>true</externalId>
        <label>Id Salesforce</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>KS_Idioma__c</fullName>
        <label>Idioma</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Idiomas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_N_de_telefono_2__c</fullName>
        <label>Nº de telefono 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>KS_N_identificacion_fiscal_suplementario__c</fullName>
        <label>Nº identificación fiscal suplementario</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Nombre_2__c</fullName>
        <label>Nombre Fiscal</label>
        <length>71</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Numero_de_identificacion_fiscal_1__c</fullName>
        <label>NIF</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/KS_Entrega__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto de integración SAP para traer entregas de clientes</description>
    <fields>
        <fullName>KS_Numero_Entrega__c</fullName>
        <externalId>true</externalId>
        <label>Número Entrega</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Entrega</label>
    <nameField>
        <label>Entrega</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/KS_Pedido__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto para alojar los pedidos provinientes de SAP</description>
    <fields>
        <fullName>KS_Numero_Pedido__c</fullName>
        <description>ID SAP</description>
        <externalId>true</externalId>
        <label>Número Pedido</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Pedido</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Número SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Idiomas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ES</fullName>
        <default>true</default>
        <label>ES</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
    </customValue>
    <customValue>
        <fullName>ZF</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>CAT</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Contactos / Cliente Distribucion --&gt; CARGADO</description>
    <masterLabel>Idiomas</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Actividad.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alojamiento Turístico</fullName>
    </customValue>
    <customValue>
        <fullName>Arquitectura</fullName>
    </customValue>
    <customValue>
        <fullName>Bancos y cajas</fullName>
    </customValue>
    <customValue>
        <fullName>Centros comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Compañías de Seguros</fullName>
    </customValue>
    <customValue>
        <fullName>Consultoras Inmobiliarias</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidor</fullName>
    </customValue>
    <customValue>
        <fullName>Educación</fullName>
    </customValue>
    <customValue>
        <fullName>Gran empresa Privada</fullName>
    </customValue>
    <customValue>
        <fullName>Ingeniería</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Integrador</fullName>
    </customValue>
    <customValue>
        <fullName>Interiorista</fullName>
    </customValue>
    <customValue>
        <fullName>Laboratorio</fullName>
    </customValue>
    <customValue>
        <fullName>Moda y Complementos</fullName>
    </customValue>
    <customValue>
        <fullName>Organismos Oficiales</fullName>
    </customValue>
    <customValue>
        <fullName>Reformistas</fullName>
    </customValue>
    <customValue>
        <fullName>Restauración</fullName>
    </customValue>
    <customValue>
        <fullName>Sanidad</fullName>
    </customValue>
    <customValue>
        <fullName>TEI</fullName>
    </customValue>
    <customValue>
        <fullName>Alimentación</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion/Gremio Instaladores</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion DME</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion Domoticas</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones EE y VE</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones Prensa</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones Sectorial</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion Light Designers e iluminacion</fullName>
    </customValue>
    <customValue>
        <fullName>Automoción</fullName>
    </customValue>
    <customValue>
        <fullName>Bienestar</fullName>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en cuentas</description>
    <masterLabel>Actividad</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Canal.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Distribuidores CRM</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Prescriptores</fullName>
    </customValue>
    <customValue>
        <fullName>Clientes finales</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidores SAP</fullName>
    </customValue>
    <customValue>
        <fullName>Varios</fullName>
        <isActive>false</isActive>
        <label>Varios</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en Cuentas</description>
    <masterLabel>Canal</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Grupo_de_ctas_deudor.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
    </customValue>
    <customValue>
        <fullName>0002</fullName>
    </customValue>
    <customValue>
        <fullName>0003</fullName>
    </customValue>
    <customValue>
        <fullName>0004</fullName>
    </customValue>
    <customValue>
        <fullName>0012</fullName>
    </customValue>
    <customValue>
        <fullName>Z001</fullName>
    </customValue>
    <customValue>
        <fullName>Z010</fullName>
    </customValue>
    <customValue>
        <fullName>Z011</fullName>
    </customValue>
    <customValue>
        <fullName>Z014</fullName>
    </customValue>
    <customValue>
        <fullName>Z015</fullName>
    </customValue>
    <customValue>
        <fullName>ZE01</fullName>
    </customValue>
    <customValue>
        <fullName>ZEXT</fullName>
    </customValue>
    <customValue>
        <fullName>ZINT</fullName>
    </customValue>
    <customValue>
        <fullName>Z009</fullName>
    </customValue>
    <customValue>
        <fullName>Z012</fullName>
    </customValue>
    <customValue>
        <fullName>Z013</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Cliente Distribucion --&gt; CARGADO</description>
    <masterLabel>Grupo de ctas. deudor</masterLabel>
</GlobalValueSet>

src/classes/KS_INT_SAP_TEST.cls
@isTest
public class KS_INT_SAP_TEST {

    public static testMethod void testDelPedido(){
        
        KS_Trigger_Test.disableTrigger();
        KS_Pedido__c pedido = new KS_Pedido__c();
        pedido.KS_Numero_pedido__c = 'TEST_TEST';
        KS_INT_GEN.KS_Pedido pedidoSAP = new KS_INT_GEN.KS_Pedido();
        pedidoSAP.KS_documento_de_ventas = pedido.KS_Numero_pedido__c;
        
        insert pedido;
        KS_Trigger_Test.enableTrigger();
        
        List<KS_INT_GEN.KS_Pedido> lstPedidoSAP = new List<KS_INT_GEN.KS_Pedido>();
        lstPedidoSAP.add(pedidoSAP);
        List<KS_INT_GEN.KS_Resultado> res = KS_INT_SAP.DelPedidos(lstPedidoSAP);
        System.debug(Logginglevel.ERROR,'-- TEST FINAL RESULT ------------------------------ JCAR testDelPedido -- ' +  res);
    }
    
    public static testMethod void testDelEntrega(){
        
        KS_Trigger_Test.disableTrigger();
        KS_Entrega__c entrega = new KS_Entrega__c();
        entrega.KS_Numero_entrega__c = 'TEST_TEST';
        KS_INT_GEN.KS_Entrega entregaSAP = new KS_INT_GEN.KS_Entrega();
        entregaSAP.KS_Numero_Entrega = entrega.KS_Numero_entrega__c;
        
        insert entrega;
        KS_Trigger_Test.enableTrigger();
        
        List<KS_INT_GEN.KS_Entrega> lstEntregaSAP = new List<KS_INT_GEN.KS_Entrega>();
        lstEntregaSAP.add(entregaSAP);
        List<KS_INT_GEN.KS_Resultado> res = KS_INT_SAP.DelEntregas(lstEntregaSAP);
        System.debug(Logginglevel.ERROR,'-- TEST FINAL RESULT ------------------------------ JCAR testDelEntrega -- ' +  res);
    }
    
    public static testMethod void testSetCliente(){
        List<Account> a = KS_INT_SAP_TEST.createCuentaSAP(true, 'TESTCLIENT');
        if (a.isEmpty()) {return;}
        List<Account> b = KS_INT_SAP_TEST.createCuentaSAP(false, a.get(0).KS_ID_SALESFORCE__c);
        if (b.isEmpty()) {return;}
        
        System.debug(Logginglevel.ERROR,'-- TEST RESULT ------------------------------ JCAR testSetCliente Account a -- ' +  a);
        System.debug(Logginglevel.ERROR,'-- TEST RESULT ------------------------------ JCAR testSetCliente Account b -- ' +  b);
        
        if (a.get(0).ID != b.get(0).ID) { 
            String error = 
                '-- TEST RESULT ERROR -- WRONG ASIGNACIÓN DE ID ' +
                a.get(0).ID + ' != ' + b.get(0).ID;
            System.debug(Logginglevel.ERROR,error);
            throw new TestException(error);
        } 
        
        Set<ID> accounts = new Set<ID>(); accounts.add(a.get(0).ID);
        KS_OrgCliente_Trigger.futureUpdateCall(accounts);
    }
    
    public static List<Account> createCuentaSAP(Boolean idSAP, String idExterna) 
    {return createCuentaSAP(idSAP, idExterna, null);}
    public static List<Account> createCuentaSAP(Boolean idSAP, String idExterna, String idSecundaria) {
        
        List<KS_INT_GEN.KS_Cliente> lstCliente = new List<KS_INT_GEN.KS_Cliente>();
        List<KS_INT_GEN.KS_Resultado> lstResult = new List<KS_INT_GEN.KS_Resultado>();
        
        KS_INT_GEN.KS_Cliente clie = new KS_INT_GEN.KS_Cliente();
        KS_INT_GEN.KS_OrganizacionCliente orgClie = new KS_INT_GEN.KS_OrganizacionCliente();
        
        if (idSAP) { clie.KS_Numero_de_deudor = idExterna;/*'TESTCLIENT';*/ }
        else { clie.KS_Clave_de_grupo = idExterna; clie.KS_Numero_de_deudor = idSecundaria; }
        
        clie.KS_Nombre_1 = 'NAME1';
        clie.KS_Nombre_2 = 'NAME2';
        clie.KS_Nombre_3 = 'NAME3';
        clie.KS_Nombre_4 = 'NAME4';
        clie.KS_N_de_telefono_1 = '666666666';
        clie.KS_Pais_Cliente = 'ES';
        clie.KS_Poblacion = 'Barcelona';
        clie.KS_Codigo_Postal = '08907';
        clie.KS_Calle_y_N = 'Calle de gracia';
        clie.KS_Grupo_de_ctas_deudor = '0001';
        clie.KS_Idioma = 'ES';
        clie.KS_N_identificacion_fiscal_suplementario = '1';
        clie.KS_Numero_de_identificacion_fiscal_1 = '1';
        clie.KS_N_de_telefono_2 = '1';
        
        orgClie.KS_Moneda = 'EUR';
        orgClie.KS_Bloqueo_de_entrega_para_cliente = '01';
        orgClie.KS_Bloqueo_de_factura_para_cliente = '01';
        orgClie.KS_Bloqueo_de_pedido_para_cliente = '01';
        orgClie.KS_Cliente_Dest_Mercancias = clie.KS_Numero_de_deudor;
        orgClie.KS_Cliente_solicitante = clie.KS_Numero_de_deudor;
        orgClie.KS_Incoterms_parte_1 = 'AAA';
        orgClie.KS_Incoterms_parte_2 = 'BBB';
        orgClie.KS_Organizacion_de_ventas = 'SI10';
        orgClie.KS_Canal_de_distribucion = '10';
        orgClie.KS_Lista_de_precios = '00';
        orgClie.KS_Sector = '10';
        orgClie.KS_Peticion_de_borrado_para_cliente = true;
        orgClie.KS_Oficinas_de_ventas = '1010';
        orgClie.KS_Grupo_de_vendedores = '000';
        orgClie.KS_Clasificacion_de_Clientes = 'AA';
        orgClie.KS_Sociedad = 'SI10';
        orgClie.KS_Bloqueo_contabilizacion_para_sociedad = true; //Boolean
        orgClie.KS_Clave_de_condiciones_de_pago = '0001';
        orgClie.KS_Peticion_borrado_para_reg_maestro = true;
        
        clie.lstOrgClientes = new List<KS_INT_GEN.KS_OrganizacionCliente>();
        clie.lstOrgClientes.add(orgClie);
        lstCliente.add(clie);
        lstResult = KS_INT_SAP.setCliente(lstCliente);
        
        List<Account> a = [SELECT ID, KS_Id_SAP__c, KS_Id_Salesforce__c,
                           Name, Phone, BillingCountryCode, BillingCity, BillingPostalCode, BillingStreet, 
                           KS_Grupo_de_ctas_deudor__c, KS_Idioma__c, KS_Nombre_2__c, 
                           KS_N_identificacion_fiscal_suplementario__c, KS_Numero_de_identificacion_fiscal_1__c,
                           KS_N_de_telefono_2__c, KS_Actividad__c, KS_Canal__c
                           FROM Account WHERE KS_Id_SAP__c = :idExterna OR KS_Id_Salesforce__c = :idExterna];
        
        return a;
    }
    public class TestException extends Exception {}    
    
}