src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KS_Scoring_Actividad__c</fullName>
        <label>Scoring Actividad Comercial</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Scoring</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Scoring_Negocio__c</fullName>
        <label>Scoring Negocio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Scoring</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/KS_Estructura_Geografica__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto donde se recoge la configuración de regiones y areas para cada organización</description>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Delegacion__c</fullName>
        <label>Delegación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Delegacion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Zona__c</fullName>
        <label>Zona</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Zona_Geog</valueSetName>
        </valueSet>
    </fields>
    <label>Estructura Geografica</label>
    <nameField>
        <label>Estructura Geografica</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estructuras Geograficas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Obra__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Es el objeto superior que agrega las ofertas (oportunidades)</description>
    <label>Obra</label>
    <nameField>
        <label>Nombre de Obra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Obras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Organizacion_Cliente__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto vinculado con las cuentas (marcas) que muestra las organizaciones de ventas para cada cliente</description>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Canal_de_distribucion__c</fullName>
        <label>Canal de distribución</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Canal_de_distribucion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Cliente_Dest_Mercancias__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente Dest. Mercancias</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Clientes Dest. Mercancias</relationshipLabel>
        <relationshipName>Clientes_Dest_Mercancias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Cliente_Distribucion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente Distribución</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3) OR 4</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Distribuidores_SAP</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Lead</value>
            </filterItems>
            <filterItems>
                <field>Account.KS_Canal__c</field>
                <operation>equals</operation>
                <value>Distribuidores CRM</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Distribuidores CRM</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marcas Comerciales</relationshipLabel>
        <relationshipName>Organizaciones_Cliente</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Cliente_solicitante__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente solicitante</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marcas Comerciales</relationshipLabel>
        <relationshipName>Clientes_solicitantes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Delegacion__c</fullName>
        <label>Delegación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Delegacion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Grupo_de_vendedores__c</fullName>
        <label>Grupo de vendedores</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Grupo_de_vendedores</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_ID_Organizacion_Cliente__c</fullName>
        <externalId>true</externalId>
        <label>ID Organizacion Cliente</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>KS_Id_Salesforce_Destinatario__c</fullName>
        <formula>KS_Cliente_Dest_Mercancias__r.KS_Id_Salesforce__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id Salesforce Destinatario</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Id_Salesforce_Distribuidor__c</fullName>
        <formula>KS_Cliente_Distribucion__r.KS_Id_Salesforce__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id Salesforce Distribuidor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Id_Salesforce_Solicitante__c</fullName>
        <formula>KS_Cliente_solicitante__r.KS_Id_Salesforce__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id Salesforce Solicitante</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Lista_de_precios__c</fullName>
        <label>Lista de precios</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Lista_de_precios</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Oficinas_de_ventas__c</fullName>
        <label>Oficinas de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Oficinas_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Recurrencia__c</fullName>
        <inlineHelpText>Una vez establecida la recurrencia solicite aprobación del registro para que el responsable autorice el régimen de visitas y se generen los avisos automáticos.</inlineHelpText>
        <label>Recurrencia (días)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
                <value>
                    <fullName>365</fullName>
                </value>
                <value>
                    <fullName>---</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Scoring_Actividad__c</fullName>
        <label>Scoring Actividad</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Scoring</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Scoring_IF__c</fullName>
        <label>Scoring IF</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Scoring_AC</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Scoring_Negocio__c</fullName>
        <label>Scoring Negocio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Scoring</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Sector_Distribuidor__c</fullName>
        <label>Sector (Distribuidor)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Tipo_Sector</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Sociedad__c</fullName>
        <label>Sociedad</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Sociedad</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Zona__c</fullName>
        <label>Zona</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Zona_Geog</valueSetName>
        </valueSet>
    </fields>
    <label>Organización Cliente</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Nombre de Organización Cliente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizaciones Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/KS_Usuario_MarcaArea__c.object
<CustomObject>
    <description>KAIZENSTEP. DESACTIVADO. Determina el ámbito de actuación de cada usuario (por zona) --&gt; mapping del crm antinguo</description>
    <fields>
        <fullName>KS_Area__c</fullName>
        <description>Área Geográfica</description>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <label>Usuario Marca/Área</label>
    <nameField>
        <displayFormat>UMA-{0000000}</displayFormat>
        <label>ID Usuario Marca/Área</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usuarios Marcas/Áreas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Delegacion__c</fullName>
        <label>Delegación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Delegacion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Lista_de_precios__c</fullName>
        <formula>TEXT(KS_Organizacion_Cliente__r.KS_Lista_de_precios__c)</formula>
        <label>Lista de Precios</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>KS_Obra__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Oportunidades</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KS_Obra__c</referenceTo>
        <relationshipLabel>Ofertas</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Organizacion_Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marca Comercial</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>KS_Organizacion_Cliente__c.KS_Cliente_solicitante__c</field>
                <operation>equals</operation>
                <valueField>$Source.KS_Distribuidor__c</valueField>
            </filterItems>
            <filterItems>
                <field>KS_Organizacion_Cliente__c.KS_Cliente_Distribucion__c</field>
                <operation>equals</operation>
                <valueField>$Source.KS_Distribuidor__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KS_Organizacion_Cliente__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <formula>text( KS_Organizacion_Cliente__r.KS_Organizacion_de_ventas__c )</formula>
        <label>Organización de ventas (FÓRMULA)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Zona__c</fullName>
        <label>Zona</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Zona_Geog</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/KS_Area.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1010</fullName>
    </customValue>
    <customValue>
        <fullName>1020</fullName>
    </customValue>
    <customValue>
        <fullName>1021</fullName>
    </customValue>
    <customValue>
        <fullName>1030</fullName>
    </customValue>
    <customValue>
        <fullName>1040</fullName>
    </customValue>
    <customValue>
        <fullName>1050</fullName>
    </customValue>
    <customValue>
        <fullName>1060</fullName>
    </customValue>
    <customValue>
        <fullName>INTE</fullName>
    </customValue>
    <description>SAP. IDs SAP de Área</description>
    <masterLabel>Área</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Canal_de_distribucion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>Nacional</fullName>
        <isActive>false</isActive>
        <label>Nacional</label>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente - Jerarquia Cliente - Producto --&gt; CARGADO</description>
    <masterLabel>Canal de distribución</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Delegacion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>009</fullName>
    </customValue>
    <customValue>
        <fullName>010</fullName>
    </customValue>
    <customValue>
        <fullName>011</fullName>
    </customValue>
    <customValue>
        <fullName>012</fullName>
    </customValue>
    <customValue>
        <fullName>013</fullName>
    </customValue>
    <customValue>
        <fullName>015</fullName>
    </customValue>
    <customValue>
        <fullName>017</fullName>
    </customValue>
    <customValue>
        <fullName>018</fullName>
    </customValue>
    <customValue>
        <fullName>019</fullName>
    </customValue>
    <customValue>
        <fullName>020</fullName>
    </customValue>
    <customValue>
        <fullName>021</fullName>
    </customValue>
    <customValue>
        <fullName>023</fullName>
    </customValue>
    <customValue>
        <fullName>024</fullName>
    </customValue>
    <customValue>
        <fullName>025</fullName>
    </customValue>
    <customValue>
        <fullName>026</fullName>
    </customValue>
    <customValue>
        <fullName>027</fullName>
    </customValue>
    <customValue>
        <fullName>028</fullName>
    </customValue>
    <customValue>
        <fullName>029</fullName>
    </customValue>
    <customValue>
        <fullName>030</fullName>
    </customValue>
    <customValue>
        <fullName>031</fullName>
    </customValue>
    <customValue>
        <fullName>032</fullName>
    </customValue>
    <customValue>
        <fullName>033</fullName>
    </customValue>
    <customValue>
        <fullName>034</fullName>
    </customValue>
    <customValue>
        <fullName>035</fullName>
    </customValue>
    <customValue>
        <fullName>036</fullName>
    </customValue>
    <description>SAP. IDs SAP de Delegación</description>
    <masterLabel>Delegación</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Grupo_de_vendedores.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>000</fullName>
    </customValue>
    <customValue>
        <fullName>I01</fullName>
    </customValue>
    <customValue>
        <fullName>I02</fullName>
    </customValue>
    <customValue>
        <fullName>I03</fullName>
    </customValue>
    <customValue>
        <fullName>I04</fullName>
    </customValue>
    <customValue>
        <fullName>I05</fullName>
    </customValue>
    <customValue>
        <fullName>I06</fullName>
    </customValue>
    <customValue>
        <fullName>I07</fullName>
    </customValue>
    <customValue>
        <fullName>I08</fullName>
    </customValue>
    <customValue>
        <fullName>I09</fullName>
    </customValue>
    <customValue>
        <fullName>I10</fullName>
    </customValue>
    <customValue>
        <fullName>I11</fullName>
    </customValue>
    <customValue>
        <fullName>I12</fullName>
    </customValue>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AN</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AS</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente --&gt; CARGADO</description>
    <masterLabel>Grupo de vendedores</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Lista_de_precios.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>00</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>EC</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>PU</fullName>
    </customValue>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <customValue>
        <fullName>E0</fullName>
    </customValue>
    <customValue>
        <fullName>T0</fullName>
    </customValue>
    <customValue>
        <fullName>T1</fullName>
    </customValue>
    <customValue>
        <fullName>T2</fullName>
    </customValue>
    <customValue>
        <fullName>T3</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
    </customValue>
    <customValue>
        <fullName>B2</fullName>
    </customValue>
    <customValue>
        <fullName>B3</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente --&gt; CARGADO</description>
    <masterLabel>Lista de precios</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Oficinas_de_ventas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>0090</fullName>
    </customValue>
    <customValue>
        <fullName>1010</fullName>
    </customValue>
    <customValue>
        <fullName>1020</fullName>
    </customValue>
    <customValue>
        <fullName>1021</fullName>
    </customValue>
    <customValue>
        <fullName>1030</fullName>
    </customValue>
    <customValue>
        <fullName>1040</fullName>
    </customValue>
    <customValue>
        <fullName>1050</fullName>
    </customValue>
    <customValue>
        <fullName>1060</fullName>
    </customValue>
    <customValue>
        <fullName>5010</fullName>
    </customValue>
    <customValue>
        <fullName>5020</fullName>
    </customValue>
    <customValue>
        <fullName>5030</fullName>
    </customValue>
    <customValue>
        <fullName>5040</fullName>
    </customValue>
    <customValue>
        <fullName>5050</fullName>
    </customValue>
    <customValue>
        <fullName>5060</fullName>
    </customValue>
    <customValue>
        <fullName>5210</fullName>
    </customValue>
    <customValue>
        <fullName>5BEL</fullName>
    </customValue>
    <customValue>
        <fullName>B000</fullName>
    </customValue>
    <customValue>
        <fullName>BR01</fullName>
    </customValue>
    <customValue>
        <fullName>BR02</fullName>
    </customValue>
    <customValue>
        <fullName>BR03</fullName>
    </customValue>
    <customValue>
        <fullName>BR04</fullName>
    </customValue>
    <customValue>
        <fullName>BR05</fullName>
    </customValue>
    <customValue>
        <fullName>BR06</fullName>
    </customValue>
    <customValue>
        <fullName>BRDE</fullName>
    </customValue>
    <customValue>
        <fullName>BRNA</fullName>
    </customValue>
    <customValue>
        <fullName>DELE</fullName>
    </customValue>
    <customValue>
        <fullName>FINT</fullName>
    </customValue>
    <customValue>
        <fullName>IN01</fullName>
    </customValue>
    <customValue>
        <fullName>IN02</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente --&gt; CARGADO</description>
    <masterLabel>Oficinas de ventas</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Organizacion_de_ventas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>FL31</fullName>
    </customValue>
    <customValue>
        <fullName>GI50</fullName>
    </customValue>
    <customValue>
        <fullName>IE20</fullName>
    </customValue>
    <customValue>
        <fullName>MA15</fullName>
    </customValue>
    <customValue>
        <fullName>MA16</fullName>
    </customValue>
    <customValue>
        <fullName>MX24</fullName>
    </customValue>
    <customValue>
        <fullName>MX25</fullName>
    </customValue>
    <customValue>
        <fullName>MX26</fullName>
    </customValue>
    <customValue>
        <fullName>SI10</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente / Jerarquia Cliente / Producto / Autorizaciones Oferta --&gt; CARGADO</description>
    <masterLabel>Organizacion de ventas</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Scoring.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>*</fullName>
    </customValue>
    <customValue>
        <fullName>**</fullName>
    </customValue>
    <customValue>
        <fullName>***</fullName>
    </customValue>
    <customValue>
        <fullName>****</fullName>
    </customValue>
    <customValue>
        <fullName>*****</fullName>
    </customValue>
    <customValue>
        <fullName>BC</fullName>
        <isActive>false</isActive>
        <label>BC</label>
    </customValue>
    <customValue>
        <fullName>CB</fullName>
        <isActive>false</isActive>
        <label>CB</label>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
        <isActive>false</isActive>
        <label>BB</label>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
        <isActive>false</isActive>
        <label>BA</label>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
        <isActive>false</isActive>
        <label>AC</label>
    </customValue>
    <customValue>
        <fullName>AB</fullName>
        <isActive>false</isActive>
        <label>AB</label>
    </customValue>
    <customValue>
        <fullName>AA</fullName>
        <isActive>false</isActive>
        <label>AA</label>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <isActive>false</isActive>
        <label>CA</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado en objeto Leads y cuentas</description>
    <masterLabel>Scoring</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Sociedad.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>BR17</fullName>
    </customValue>
    <customValue>
        <fullName>BR18</fullName>
    </customValue>
    <customValue>
        <fullName>FL31</fullName>
    </customValue>
    <customValue>
        <fullName>GI50</fullName>
    </customValue>
    <customValue>
        <fullName>IE20</fullName>
    </customValue>
    <customValue>
        <fullName>IN19</fullName>
    </customValue>
    <customValue>
        <fullName>MA15</fullName>
    </customValue>
    <customValue>
        <fullName>MA16</fullName>
    </customValue>
    <customValue>
        <fullName>MX01</fullName>
    </customValue>
    <customValue>
        <fullName>MX24</fullName>
    </customValue>
    <customValue>
        <fullName>MX25</fullName>
    </customValue>
    <customValue>
        <fullName>MX26</fullName>
    </customValue>
    <customValue>
        <fullName>SI10</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente --&gt; CARGADO</description>
    <masterLabel>Sociedad</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Tipo_Sector.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <customValue>
        <fullName>40</fullName>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>60</fullName>
    </customValue>
    <customValue>
        <fullName>70</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente - Jerarquia Cliente - Producto --&gt; CARGADO</description>
    <masterLabel>Tipo Sector (SAP)</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Zona_Geog.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>23</fullName>
    </customValue>
    <customValue>
        <fullName>24</fullName>
    </customValue>
    <customValue>
        <fullName>25</fullName>
    </customValue>
    <customValue>
        <fullName>26</fullName>
    </customValue>
    <customValue>
        <fullName>27</fullName>
    </customValue>
    <customValue>
        <fullName>28</fullName>
    </customValue>
    <customValue>
        <fullName>29</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <description>SAP. En Uso en Oportunidaes/Obras</description>
    <masterLabel>Zona Geog.</masterLabel>
</GlobalValueSet>

src/globalValueSets/Scoring_AC.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AA</fullName>
    </customValue>
    <customValue>
        <fullName>AB</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BC</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CB</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
    </customValue>
    <customValue>
        <fullName>CD</fullName>
        <isActive>false</isActive>
        <label>CD</label>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
        <isActive>false</isActive>
        <label>BD</label>
    </customValue>
    <customValue>
        <fullName>AD</fullName>
        <isActive>false</isActive>
        <label>AD</label>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
        <isActive>false</isActive>
        <label>DC</label>
    </customValue>
    <customValue>
        <fullName>DB</fullName>
        <isActive>false</isActive>
        <label>DB</label>
    </customValue>
    <customValue>
        <fullName>DD</fullName>
        <isActive>false</isActive>
        <label>DD</label>
    </customValue>
    <customValue>
        <fullName>DA</fullName>
        <isActive>false</isActive>
        <label>DA</label>
    </customValue>
    <description>EN USO --&gt; Cuentas tipo Lead</description>
    <masterLabel>Scoring-AC</masterLabel>
</GlobalValueSet>

src/classes/KS_BATCH_Test.cls
@isTest
public class KS_BATCH_Test {

    public static testMethod void testSetCliente(){
        
        KS_Trigger_Test.disableTrigger();
        List<Account> a = KS_INT_SAP_TEST.createCuentaSAP(true, 'TESTCLIENT');
        if (a.isEmpty()) {return;}
        
        //System.debug(Logginglevel.ERROR,'-- TEST ------------------------------ JCAR Account -- ' +  a.get(0));
        KS_Organizacion_Cliente__c o1 = [SELECT ID, KS_ID_Organizacion_Cliente__c,
                                         KS_Organizacion_de_ventas__c, KS_Canal_de_distribucion__c, 
                                         KS_Sector_Distribuidor__c, KS_Oficinas_de_ventas__c, 
                                         KS_Sociedad__c, KS_Lista_de_precios__c, KS_Grupo_de_vendedores__c, 
                                         KS_Cliente_Distribucion__c, KS_Cliente_Dest_Mercancias__c, KS_Cliente_solicitante__c
                                         FROM KS_Organizacion_Cliente__c WHERE KS_Cliente_Distribucion__c = :a.get(0).ID];
        //System.debug(Logginglevel.ERROR,'-- TEST ------------------------------ JCAR KS_Organizacion_Cliente__c -- ' +  o1);

        KS_TEST_FUNCTIONS tstfnc = new KS_TEST_FUNCTIONS();
        Map<String, ID> rtM = KS_TEST_FUNCTIONS.getRecordTypeStatic();
        KS_Obra__c obr = tstfnc.createObra(rtM);
        Account acc = a.get(0);
        KS_Estructura_Geografica__c ege =  tstfnc.createEstructuraGeografica(acc);

        KS_Organizacion_Cliente__c org = o1;
        org.KS_Area__c = ege.KS_Area__c;
        org.KS_Delegacion__c = ege.KS_Delegacion__c;
        org.KS_Zona__c = ege.KS_Zona__c;
        org.KS_ID_Organizacion_Cliente__c = 'LA-ID-SE-HA-ROTO-SIN-QUERER';
        update org;
        
        Pricebook2 pbS = tstfnc.createPricebook();
        KS_Usuario_MarcaArea__c uma = tstfnc.createUserArea(org);
        Opportunity opp = tstfnc.createOferta(acc, org, obr, pbS);
        
        /*System.debug(Logginglevel.ERROR,'-- TEST ------------------------------ JCAR CALL KS_Batch_RepairOrgCliente con 1 ORG');
        
        KS_Batch_RepairOrgCliente.logic(a);
        
        org.KS_ID_Organizacion_Cliente__c = 'LA-ID-SE-HA-ROTO-SIN-QUERER';
        update org;*/
        
        KS_Organizacion_Cliente__c o2 = org.clone(false,false,false,false);
        o2.KS_ID_Organizacion_Cliente__c = 'LA-ID-SE-HA-CARGADO-MAL';
        o2.KS_Scoring_Actividad__c = '***';
        o2.KS_Scoring_Negocio__c = '***';
        o2.KS_Scoring_IF__c = 'AB';
        o2.KS_Recurrencia__c = '90';
        insert o2;
        KS_Trigger_Test.enableTrigger();
        
        //System.debug(Logginglevel.ERROR,'-- TEST ------------------------------ JCAR CALL KS_Batch_RepairOrgCliente con 2 ORG (DUPLICADOS)');
        
        List<KS_Organizacion_Cliente__c> orgUpdate = KS_Batch_RepairOrgCliente.logic(a);
        //update orgUpdate;
        
        List<KS_Organizacion_Cliente__c> orgR = [SELECT ID, KS_ID_Organizacion_Cliente__c, KS_Recurrencia__c, OwnerID,
                                                 KS_Cliente_Distribucion__c, KS_Cliente_solicitante__c, KS_Cliente_Dest_Mercancias__c,
                                                 KS_Id_Salesforce_Distribuidor__c, KS_Id_Salesforce_Solicitante__c, KS_Id_Salesforce_Destinatario__c,
                                                 KS_Organizacion_de_ventas__c, KS_Oficinas_de_ventas__c, KS_Canal_de_distribucion__c, KS_Sector_Distribuidor__c,
                                                 KS_Scoring_Actividad__c, KS_Scoring_Negocio__c, KS_Scoring_IF__c
                                                 FROM KS_Organizacion_Cliente__c WHERE KS_Cliente_Distribucion__c = :acc.ID];
        System.debug(Logginglevel.ERROR,'-- TEST FINAL RESULT ------------------------------ JCAR KS_Organizacion_Cliente__c -- ' +  orgR);
    }
}