src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KS_C_digo_Postal__c</fullName>
        <label>Código Postal</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Calle__c</fullName>
        <label>Calle</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ciudad__c</fullName>
        <label>Ciudad</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Estado_o_Provincia__c</fullName>
        <label>Estado o Provincia</label>
        <length>38</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Pais__c</fullName>
        <label>País</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Codigo_Pais</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Tipo_de_via__c</fullName>
        <label>Tipo de via</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Tipo_de_via</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>KS_Calle__c</fullName>
        <formula>Account.BillingStreet</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Calle</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ciudad__c</fullName>
        <formula>Account.BillingCity</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ciudad</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Codigo_postal__c</fullName>
        <formula>Account.BillingPostalCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Código postal</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Pais__c</fullName>
        <formula>Account.BillingCountry</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>País</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SI_Consiente_tratamiento_de_datos__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Consentimiento</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SI_Rechaza_comunicaciones__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rechaza comunicaciones</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SI_Telofono_Movil__c</fullName>
        <label>Teléfono Móvil</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>KS_C_digo_Postal__c</fullName>
        <inlineHelpText>Este campo es obligatorio para la conversión</inlineHelpText>
        <label>Código_Postal</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Calle__c</fullName>
        <inlineHelpText>Este campo es obligatorio para la conversión</inlineHelpText>
        <label>Nombre de la vía</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ciudad__c</fullName>
        <inlineHelpText>Este campo es obligatorio para la conversión</inlineHelpText>
        <label>Ciudad</label>
        <length>38</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Consentimiento__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Uno de los campos de tratamiento es obligatorio para poder convertir</inlineHelpText>
        <label>Consentimiento</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Estado_o_Provincia__c</fullName>
        <inlineHelpText>Este campo es obligatorio para la conversión</inlineHelpText>
        <label>Estado / Provincia</label>
        <length>38</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_N_m_portal_piso_puerta_y_resto_domici__c</fullName>
        <inlineHelpText>Este campo es obligatorio para la conversión</inlineHelpText>
        <label>Núm, portal, piso, puerta y resto dom.</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Pais__c</fullName>
        <inlineHelpText>Este campo es obligatorio para la conversión</inlineHelpText>
        <label>Pais</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Codigo_Pais</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_RechazoComunicaciones__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Uno de los campos de tratamiento es obligatorio para poder convertir</inlineHelpText>
        <label>Rechazo de comunicaciones</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Tipo_de_via__c</fullName>
        <inlineHelpText>Este campo es obligatorio para la conversión</inlineHelpText>
        <label>Tipo de vía</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Tipo_de_via</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SI_Telefono_Movil__c</fullName>
        <inlineHelpText>Este campo es obligatorio para la conversión</inlineHelpText>
        <label>Teléfono Móvil</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/globalValueSets/Tipo_de_via.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CALLE</fullName>
    </customValue>
    <customValue>
        <fullName>CARRER</fullName>
    </customValue>
    <customValue>
        <fullName>KALEA</fullName>
    </customValue>
    <customValue>
        <fullName>AVENIDA</fullName>
    </customValue>
    <customValue>
        <fullName>AVINGUDA</fullName>
    </customValue>
    <customValue>
        <fullName>ETORBIDEA</fullName>
    </customValue>
    <customValue>
        <fullName>ALAMEDA</fullName>
    </customValue>
    <customValue>
        <fullName>ALBEREDA</fullName>
    </customValue>
    <customValue>
        <fullName>ALDEA</fullName>
    </customValue>
    <customValue>
        <fullName>AUTOPISTA</fullName>
    </customValue>
    <customValue>
        <fullName>AUTOVIA</fullName>
    </customValue>
    <customValue>
        <fullName>AUTOVÍA</fullName>
    </customValue>
    <customValue>
        <fullName>AUZUNEA</fullName>
    </customValue>
    <customValue>
        <fullName>BARRI</fullName>
    </customValue>
    <customValue>
        <fullName>BARRIADA</fullName>
    </customValue>
    <customValue>
        <fullName>BARRIO</fullName>
    </customValue>
    <customValue>
        <fullName>BIDEA</fullName>
    </customValue>
    <customValue>
        <fullName>BULEVAR</fullName>
    </customValue>
    <customValue>
        <fullName>CALLEJÓN</fullName>
    </customValue>
    <customValue>
        <fullName>CALZADA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMÍ</fullName>
    </customValue>
    <customValue>
        <fullName>CAMINO</fullName>
    </customValue>
    <customValue>
        <fullName>CAMIÑO</fullName>
    </customValue>
    <customValue>
        <fullName>CARRERA</fullName>
    </customValue>
    <customValue>
        <fullName>CARRETERA</fullName>
    </customValue>
    <customValue>
        <fullName>CONCELLO</fullName>
    </customValue>
    <customValue>
        <fullName>CUESTA</fullName>
    </customValue>
    <customValue>
        <fullName>ENPARANTZA</fullName>
    </customValue>
    <customValue>
        <fullName>ENTITATEA</fullName>
    </customValue>
    <customValue>
        <fullName>ERREPIDEA</fullName>
    </customValue>
    <masterLabel>Tipo de via</masterLabel>
</GlobalValueSet>

src/classes/KS_RGProteccionDatos_Controller.cls
public class KS_RGProteccionDatos_Controller {

    public Lead led {get;set;} public Boolean getIsLead() { return led != null; }
    public Account acc {get;set;} public Boolean getIsAccount() { return acc != null; }
    public Contact con {get;set;} public Boolean getIsContact() { return con != null; }
    public Boolean guardado {get;set;}
    public String errorMSG {get;set;}
    
    public KS_RGProteccionDatos_Controller(ApexPages.StandardController controller) {
        
        errorMSG = '';
        sObject sobj = (sObject)controller.getRecord();
        led = sobj.getSobjectType() == Schema.Lead.getSObjectType() ? (Lead)sobj : null;
        acc = sobj.getSobjectType() == Schema.Account.getSObjectType() ? (Account)sobj : null;
        con = sobj.getSobjectType() == Schema.Contact.getSObjectType() ? (Contact)sobj : null;
        
        if (led != null) {
            led = [SELECT ID,Name,FirstName,Lastname,SI_Telefono_Movil__c,Email,Company,
                   KS_Tipo_de_via__c,KS_Calle__c,KS_N_m_portal_piso_puerta_y_resto_domici__c,
                   KS_C_digo_Postal__c,KS_Ciudad__c,KS_Estado_o_Provincia__c,KS_Pais__c,
                   KS_Consentimiento__c,KS_RechazoComunicaciones__c
                   FROM Lead WHERE ID = :led.ID];
        }
        if (acc != null) {
            acc = [SELECT ID,Name,FirstName,Lastname,Phone,PersonEmail FROM Account WHERE ID = :acc.ID];
        }
        if (con != null) {
            con = [SELECT ID,Name,FirstName,Lastname,
                   AccountId, SI_Telofono_Movil__c, Email, KS_Codigo_postal__c,
                   SI_Consiente_tratamiento_de_datos__c, SI_Rechaza_comunicaciones__c
                   FROM Contact WHERE ID = :con.ID];
        }
        
        guardado = false;
    }
    
    public String getReturnURL() {
        if (led != null) { return '/' + led.ID; }
        if (acc != null) { return '/' + acc.ID; }
        if (con != null) { return '/' + con.ID; }
        return '';
    }
    
    public PageReference save() {
        errorMSG = '';
        try {
            PageReference pg = null;
            if (led != null && led.ID != null) { update led; pg = new PageReference('/'+led.ID); }
            if (acc != null && acc.ID != null) { update acc; pg = new PageReference('/'+acc.ID); }
            if (con != null && con.ID != null) { update con; pg = new PageReference('/'+con.ID); }
            if (pg!=null) { guardado = true; pg.setRedirect(true); }
        } catch (Exception ex) {
            if (ex.getMessage().contains('VALIDATION_EXCEPTION')) {
                errorMSG = ex.getMessage().split('VALIDATION_EXCEPTION\\,')[1].split('\\: \\[\\]')[0];
            } else {
                errorMSG = ex.getMessage();
            }
        }
        return null;
    }
    public PageReference cancel() {
        PageReference pg = null;
        if (led != null && led.ID != null) { pg = new PageReference('/'+led.ID); }
        if (acc != null && acc.ID != null) { pg = new PageReference('/'+acc.ID); }
        if (con != null && con.ID != null) { pg = new PageReference('/'+con.ID); }
        if (pg!=null) { pg.setRedirect(true); }
        return null;
    }
    
    public static Boolean getIsAdmin() {
        if (UserInfo.getUserEmail()=='customers@kaizenstep.com') {return true;}
        return false;
    }
}