src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KS_Actividad__c</fullName>
        <label>Actividad</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Actividad</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <label>Canal</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KS_Actividad__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Canal</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>KS_Idioma__c</fullName>
        <label>Idioma</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Idiomas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_N_de_telefono_2__c</fullName>
        <label>Nº de telefono 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>KS_N_de_telefono_3__c</fullName>
        <label>Nº de telefono 3</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>KS_Sector__c</fullName>
        <label>Sector</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>KS_Actividad__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Sector</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Subactividad__c</fullName>
        <label>Subactividad</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>KS_Actividad__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Subactividad</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Tipo__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Tipo</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>KS_Funcion_en_empresa__c</fullName>
        <label>Función en empresa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Funcion_en_empresa</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Idioma__c</fullName>
        <label>Idioma</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Idiomas</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KS_Fusion__c.object
<CustomObject>
    <fields>
        <fullName>KS_Acc_Actividad__c</fullName>
        <label>KS_Acc_Actividad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Calle__c</fullName>
        <label>KS_Acc_Calle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Canal__c</fullName>
        <label>KS_Acc_Canal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Ciudad__c</fullName>
        <label>KS_Acc_Ciudad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Codigo_Postal__c</fullName>
        <label>KS_Acc_Codigo_Postal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Correo__c</fullName>
        <label>KS_Acc_Correo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Estado_Provincia__c</fullName>
        <label>KS_Acc_Estado_Provincia</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Pais__c</fullName>
        <label>KS_Acc_Pais</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Sector__c</fullName>
        <label>KS_Acc_Sector</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Subactividad__c</fullName>
        <label>KS_Acc_Subactividad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Telefono_2__c</fullName>
        <label>KS_Acc_Telefono_2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Telefono_3__c</fullName>
        <label>KS_Acc_Telefono_3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Telefono__c</fullName>
        <label>KS_Acc_Telefono</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Accion__c</fullName>
        <label>KS_Accion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MERGE</fullName>
                </value>
                <value>
                    <fullName>DELETE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Ctc_Correo__c</fullName>
        <label>KS_Ctc_Correo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Funcion_en_empresa__c</fullName>
        <label>KS_Ctc_Funcion_en_empresa</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Idioma__c</fullName>
        <label>KS_Ctc_Idioma</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Movil__c</fullName>
        <label>KS_Ctc_Movil</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Telefono_Particular__c</fullName>
        <label>KS_Ctc_Telefono_Particular</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Telefono__c</fullName>
        <label>KS_Ctc_Telefono</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Id_Duplicado__c</fullName>
        <label>KS_Id_Duplicado</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Id_Principal__c</fullName>
        <label>KS_Id_Principal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Tipo__c</fullName>
        <label>KS_Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACCOUNT</fullName>
                </value>
                <value>
                    <fullName>CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fusion</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Fusion ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fusiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Idiomas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ES</fullName>
        <default>true</default>
        <label>ES</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
    </customValue>
    <customValue>
        <fullName>ZF</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>CAT</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Contactos / Cliente Distribucion --&gt; CARGADO</description>
    <masterLabel>Idiomas</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Actividad.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alojamiento Turístico</fullName>
    </customValue>
    <customValue>
        <fullName>Arquitectura</fullName>
    </customValue>
    <customValue>
        <fullName>Bancos y cajas</fullName>
    </customValue>
    <customValue>
        <fullName>Centros comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Compañías de Seguros</fullName>
    </customValue>
    <customValue>
        <fullName>Consultoras Inmobiliarias</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidor</fullName>
    </customValue>
    <customValue>
        <fullName>Educación</fullName>
    </customValue>
    <customValue>
        <fullName>Gran empresa Privada</fullName>
    </customValue>
    <customValue>
        <fullName>Ingeniería</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Integrador</fullName>
    </customValue>
    <customValue>
        <fullName>Interiorista</fullName>
    </customValue>
    <customValue>
        <fullName>Laboratorio</fullName>
    </customValue>
    <customValue>
        <fullName>Moda y Complementos</fullName>
    </customValue>
    <customValue>
        <fullName>Organismos Oficiales</fullName>
    </customValue>
    <customValue>
        <fullName>Reformistas</fullName>
    </customValue>
    <customValue>
        <fullName>Restauración</fullName>
    </customValue>
    <customValue>
        <fullName>Sanidad</fullName>
    </customValue>
    <customValue>
        <fullName>TEI</fullName>
    </customValue>
    <customValue>
        <fullName>Alimentación</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion/Gremio Instaladores</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion DME</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion Domoticas</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones EE y VE</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones Prensa</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones Sectorial</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion Light Designers e iluminacion</fullName>
    </customValue>
    <customValue>
        <fullName>Automoción</fullName>
    </customValue>
    <customValue>
        <fullName>Bienestar</fullName>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en cuentas</description>
    <masterLabel>Actividad</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Canal.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Distribuidores CRM</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Prescriptores</fullName>
    </customValue>
    <customValue>
        <fullName>Clientes finales</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidores SAP</fullName>
    </customValue>
    <customValue>
        <fullName>Varios</fullName>
        <isActive>false</isActive>
        <label>Varios</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en Cuentas</description>
    <masterLabel>Canal</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Funcion_en_empresa.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Compras</fullName>
    </customValue>
    <customValue>
        <fullName>Gerencia</fullName>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Servicios Técnicos</fullName>
    </customValue>
    <customValue>
        <fullName>Especialista de Producto</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Administración</fullName>
    </customValue>
    <customValue>
        <fullName>Logística</fullName>
    </customValue>
    <customValue>
        <fullName>Calidad</fullName>
    </customValue>
    <customValue>
        <fullName>Operario</fullName>
    </customValue>
    <customValue>
        <fullName>Arquitecto</fullName>
    </customValue>
    <customValue>
        <fullName>Interiorista</fullName>
        <isActive>false</isActive>
        <label>Interiorista</label>
    </customValue>
    <customValue>
        <fullName>Otros</fullName>
        <isActive>false</isActive>
        <label>Otros</label>
    </customValue>
    <customValue>
        <fullName>Fabricante</fullName>
        <isActive>false</isActive>
        <label>Fabricante</label>
    </customValue>
    <customValue>
        <fullName>Tienda</fullName>
        <isActive>false</isActive>
        <label>Tienda</label>
    </customValue>
    <customValue>
        <fullName>Proyectos</fullName>
        <isActive>false</isActive>
        <label>Proyectos</label>
    </customValue>
    <customValue>
        <fullName>Dueño</fullName>
        <isActive>false</isActive>
        <label>Dueño</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado en objeto Contactos</description>
    <masterLabel>Función en empresa</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Sector.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Residencial</fullName>
    </customValue>
    <customValue>
        <fullName>Terciario</fullName>
    </customValue>
    <customValue>
        <fullName>Hotelero</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Otros</fullName>
    </customValue>
    <customValue>
        <fullName>Edificios administrativos</fullName>
        <isActive>false</isActive>
        <label>Edificios administrativos</label>
    </customValue>
    <customValue>
        <fullName>Industrial (Naves, Fábricas, etc...)</fullName>
        <isActive>false</isActive>
        <label>Industrial (Naves, Fábricas, etc...)</label>
    </customValue>
    <customValue>
        <fullName>Educación</fullName>
        <isActive>false</isActive>
        <label>Educación</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en cuentas</description>
    <masterLabel>Sector</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Subactividad.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Agencia Viajes</fullName>
    </customValue>
    <customValue>
        <fullName>Agua</fullName>
    </customValue>
    <customValue>
        <fullName>Alojamientos Rurales</fullName>
    </customValue>
    <customValue>
        <fullName>Alquiler automobiles</fullName>
    </customValue>
    <customValue>
        <fullName>Aparejadores</fullName>
    </customValue>
    <customValue>
        <fullName>Apartamentos turísticos</fullName>
    </customValue>
    <customValue>
        <fullName>Arquitectura</fullName>
    </customValue>
    <customValue>
        <fullName>Auditor Energético</fullName>
    </customValue>
    <customValue>
        <fullName>Bancos y cajas</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Belleza</fullName>
    </customValue>
    <customValue>
        <fullName>Bolsos</fullName>
    </customValue>
    <customValue>
        <fullName>Camping</fullName>
    </customValue>
    <customValue>
        <fullName>Central, del Estado</fullName>
    </customValue>
    <customValue>
        <fullName>Centros comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Centros de día</fullName>
    </customValue>
    <customValue>
        <fullName>Centros de Salud</fullName>
    </customValue>
    <customValue>
        <fullName>Comarcal: Diputación y Autonómicas</fullName>
    </customValue>
    <customValue>
        <fullName>Comercializador</fullName>
    </customValue>
    <customValue>
        <fullName>Compañías de Seguros</fullName>
    </customValue>
    <customValue>
        <fullName>Concesionarios automoción</fullName>
    </customValue>
    <customValue>
        <fullName>Consejerías de Sanidad</fullName>
    </customValue>
    <customValue>
        <fullName>Consultoras Inmobiliarias</fullName>
    </customValue>
    <customValue>
        <fullName>Cuadrista</fullName>
    </customValue>
    <customValue>
        <fullName>Deporte</fullName>
    </customValue>
    <customValue>
        <fullName>Direccion de Obra</fullName>
    </customValue>
    <customValue>
        <fullName>DMX</fullName>
    </customValue>
    <customValue>
        <fullName>Edificación</fullName>
    </customValue>
    <customValue>
        <fullName>Educación</fullName>
    </customValue>
    <customValue>
        <fullName>Eléctrico</fullName>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en cuentas</description>
    <masterLabel>Subactividad</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/Tipo.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Punto de venta</fullName>
    </customValue>
    <customValue>
        <fullName>Punto de compra</fullName>
    </customValue>
    <customValue>
        <fullName>Central compras</fullName>
    </customValue>
    <customValue>
        <fullName>Público</fullName>
    </customValue>
    <customValue>
        <fullName>Privado</fullName>
    </customValue>
    <customValue>
        <fullName>Explotación</fullName>
    </customValue>
    <description>SEGMENTACIÓN. Variable usada en segmentación de cuentas.</description>
    <masterLabel>Tipo</masterLabel>
</GlobalValueSet>

src/classes/KS_Merge_CSVtoFusion_Controller.cls
public class KS_Merge_CSVtoFusion_Controller {
	
    public String fields {get;set;}
    public String csv {get;set;}
    public KS_Fusion__c fusionHeader {get;set;}
    public KS_Merge_CSVtoFusion_Controller(ApexPages.StandardController stdController) {
        this.fusionHeader = (KS_Fusion__c)stdController.getRecord();
        //fields = '18-IDDUPLI;3-ID;1-IDSF;10-MOVIL;11-EMAIL;9-TELF1;21-MAIN';
        fields = '0-IDDUPLI;2-ID;2-IDSF;6-EMAIL;8-CALLE;10-CIUDAD;11-ESTADO;12-CODPOST;13-PAIS;14-TELF1;15-TELF2;16-TELF3;17-MOVIL';
    } 
    
    // MERGE CONTACT '18-IDDUPLI;3-ID;1-IDSF;10-MOVIL;11-EMAIL;9-TELF1;21-MAIN'
    // MERGE ACCOUNT '0-IDDUPLI;2-ID;2-IDSF,6-EMAIL;8-CALLE;10-CIUDAD;11-ESTADO;12-CODPOST;13-PAIS;14-TELF1;15-TELF2;16-TELF3;17-MOVIL'
    
    private Map<String,Integer> fieldIndex {get;set;}
    private Map<String,sObject> objectMap {get;set;}
    private Map<String,String> objectIndex {get;set;}
    private Map<String,Set<String>> fusionIndex {get;set;}
    private Map<String,String> fusionMain {get;set;}
    
    private Boolean isAcc {get;set;}// = fusionHeader.KS_Tipo__c=='ACCOUNT';
    private Boolean isCon {get;set;}// = fusionHeader.KS_Tipo__c=='CONTACT';
    
    private Set<ID> verifiedID {get;set;}
    
    public void convert() {
        isAcc = fusionHeader.KS_Tipo__c=='ACCOUNT';
        isCon = fusionHeader.KS_Tipo__c=='CONTACT';
        process();
        fusion();
    }
    
    public void process() {
        
        if (fusionHeader==null) {return;}       
        if (fields==null) {return;} if (fields.trim()=='') {return;} if (!fields.contains(';') && !fields.contains('-')) {return;}
        if (csv==null) {return;} if (csv.trim()=='') {return;} if (!csv.contains(';')) {return;}
        
        fieldIndex = new Map<String,Integer>();
        objectMap = new Map<String,sObject>();
        objectIndex = new Map<String,String>();
        fusionIndex = new Map<String,Set<String>>();
        fusionMain = new Map<String,String>();
        
        Boolean isAcc = fusionHeader.KS_Tipo__c=='ACCOUNT';
        Boolean isCon = fusionHeader.KS_Tipo__c=='CONTACT';
        
        System.debug('-- JCAR -- KS_Merge_CSVtoFusion_Controller process -- ACCOUNT? ' + isAcc);
        System.debug('-- JCAR -- KS_Merge_CSVtoFusion_Controller process -- CONTACT? ' + isCon);
        
        if (fusionHeader.KS_Accion__c!='MERGE') {
            if (fusionHeader.KS_Accion__c!='DELETE') {
                processDELETE(); return;
            }
        }
        
        for (String fieldData : fields.split(';')) {
            if (!fieldData.contains('-')) {continue;}
            if (fieldData.split('-').size()!=2) {continue;}
            if (!fieldData.split('-').get(0).isNumeric()) {continue;}
            fieldIndex.put(fieldData.split('-').get(1), Integer.valueOf(fieldData.split('-').get(0)));
        }
        System.debug('-- JCAR -- KS_Merge_CSVtoFusion_Controller process -- ' + fieldIndex.size() + ' TOTAL FIELDS ' + fieldIndex);
        
        verifiedID = new Set<ID>();
        Set<ID> verifyID = new Set<ID>();
        
        for (String rowDataStr : csv.split('\r\n'))  {

            if (!rowDataStr.contains(';')) {continue;}
            
            //18-IDDUPLI;3-ID;1-IDSF;10-MOVIL;11-EMAIL;9-TELF1;21-MAIN
            //0-IDDUPLI;2-ID;3-IDSF;6-EMAIL;8-CALLE;10-CIUDAD;11-ESTADO;12-CODPOST;13-PAIS;14-TELF1;15-TELF2;16-TELF3;17-MOVIL
            //IDDUPLI identifica el grupo de duplicados, ID es el identificador interno de cada objeto, y con ello, de ROW

            Account acc = new Account(); 
            Contact con = new Contact();
            
            if (!fieldIndex.containsKey('ID')) {continue;}
            if (!fieldIndex.containsKey('IDSF')) {continue;}
            if (!fieldIndex.containsKey('IDDUPLI')) {continue;}
            if (isCon&&!fieldIndex.containsKey('MAIN')) {continue;}

            List<String> rowData = rowDataStr.split(';',-1);
            String IDROW = rowData.get(fieldIndex.get('ID'));
            if (isAcc) { try { acc.ID = IDROW; } catch (Exception ex){} } 
            else if(isCon) { try { con.ID = IDROW; } catch (Exception ex){} }
            
            String IDDUPLI = rowData.get(fieldIndex.get('IDDUPLI'));
            Set<String> fusionIDs = new Set<String>();
            if (fusionIndex.containsKey(IDDUPLI)) { fusionIDs = fusionIndex.get(IDDUPLI); }
            fusionIDs.add(IDROW); fusionIndex.put(IDDUPLI, fusionIDs);
            
            verifyID.add(IDROW);

            String IDSF = rowData.get(fieldIndex.get('IDSF'));
            System.debug('-- JCAR -- KS_Merge_CSVtoFusion_Controller process -- IDDUPLI? ' + IDDUPLI);
            System.debug('-- JCAR -- KS_Merge_CSVtoFusion_Controller process -- IDROW? ' + IDROW);
            System.debug('-- JCAR -- KS_Merge_CSVtoFusion_Controller process -- IDSF? ' + IDSF);
            System.debug('-- JCAR -- KS_Merge_CSVtoFusion_Controller process -- rowData? ' + rowData);
            
            if (!fusionMain.containsKey(IDDUPLI)) { 
                
                // MERGE ACCOUNT '0-IDDUPLI;2-ID;2-IDSF,6-EMAIL;8-CALLE;10-CIUDAD;11-ESTADO;12-CODPOST;13-PAIS;14-TELF1;15-TELF2;16-TELF3;17-MOVIL'
                if (isAcc && IDDUPLI == IDROW) {
                    fusionMain.put(IDDUPLI, IDROW); 
                    
                    if (fieldIndex.containsKey('EMAIL')) 
                    { acc.KS_Email__c = rowData.get(fieldIndex.get('EMAIL')); }
                    if (fieldIndex.containsKey('CALLE')) 
                    { acc.BillingStreet = rowData.get(fieldIndex.get('CALLE')); }
                    if (fieldIndex.containsKey('CIUDAD')) 
                    { acc.BillingCity = rowData.get(fieldIndex.get('CIUDAD')); }
                    if (fieldIndex.containsKey('ESTADO')) 
                    { acc.BillingState = rowData.get(fieldIndex.get('ESTADO')); }
                    if (fieldIndex.containsKey('CODPOST')) 
                    { acc.BillingPostalCode = rowData.get(fieldIndex.get('CODPOST')); }
                    if (fieldIndex.containsKey('PAIS')) 
                    { acc.BillingCountryCode = rowData.get(fieldIndex.get('PAIS')); }
                    if (fieldIndex.containsKey('TELF1')) 
                    { acc.Phone = rowData.get(fieldIndex.get('TELF1')); }
                    if (fieldIndex.containsKey('TELF2')) 
                    { acc.KS_N_de_telefono_2__c = rowData.get(fieldIndex.get('TELF2')); }
                    if (fieldIndex.containsKey('TELF3')) 
                    { acc.KS_N_de_telefono_3__c = rowData.get(fieldIndex.get('TELF3')); }
                    if (fieldIndex.containsKey('CANAL')) 
                    { acc.KS_Canal__c = rowData.get(fieldIndex.get('CANAL')); }
                    if (fieldIndex.containsKey('ACTIV')) 
                    { acc.KS_Actividad__c = rowData.get(fieldIndex.get('ACTIV')); }
                    if (fieldIndex.containsKey('SUBACTIV')) 
                    { acc.KS_Subactividad__c = rowData.get(fieldIndex.get('SUBACTIV')); }
                    if (fieldIndex.containsKey('SECTOR')) 
                    { acc.KS_Sector__c = rowData.get(fieldIndex.get('SECTOR')); }    
                    
                //18-IDDUPLI;3-ID;1-IDSF;10-MOVIL;11-EMAIL;9-TELF1;21-MAIN    
                } else if (isCon && rowData.get(fieldIndex.get('MAIN')) == 'SI') {
                    fusionMain.put(IDDUPLI, IDROW); 
                    
                    if (fieldIndex.containsKey('TELF1')) 
                    { con.Phone = rowData.get(fieldIndex.get('TELF1')); }
                    if (fieldIndex.containsKey('TELF2')) 
                    { con.OtherPhone = rowData.get(fieldIndex.get('TELF2')); }
                    if (fieldIndex.containsKey('MOVIL')) 
                    { con.MobilePhone = rowData.get(fieldIndex.get('MOVIL')); }
                    if (fieldIndex.containsKey('EMAIL')) 
                    { con.Email = rowData.get(fieldIndex.get('EMAIL')); }
                    if (fieldIndex.containsKey('FUNCION')) 
                    { con.KS_Funcion_en_empresa__c = rowData.get(fieldIndex.get('FUNCION')); }
                    if (fieldIndex.containsKey('IDIOMA')) 
                    { con.KS_Idioma__c = rowData.get(fieldIndex.get('IDIOMA')); }
                }
            }
            
            objectIndex.put(IDROW, IDSF);
            if (isAcc) { objectMap.put(IDROW, acc); } else if(isCon) { objectMap.put(IDROW, con); }
        }
        
        System.debug('-- JCAR -- KS_Merge_CSVtoFusion_Controller process -- ' + fusionIndex.size() + ' - TOTAL FUSION INDEX ' + fusionIndex.keySet());
        System.debug('-- JCAR -- KS_Merge_CSVtoFusion_Controller process -- ' + objectIndex.size() + ' - TOTAL OBJECTS INDEX ' + objectIndex.keySet());
        System.debug('-- JCAR -- KS_Merge_CSVtoFusion_Controller process -- ' + objectMap.size() + ' - TOTAL OBJECTS ' + objectMap.keySet());
        System.debug('-- JCAR -- KS_Merge_CSVtoFusion_Controller process -- ' + fusionMain.size() + ' - TOTAL FUSION MAIN ' + fusionMain);
        
        if (isAcc) { for (Account obj : [SELECT ID FROM Account WHERE ID in :verifyID]) { verifiedID.add(obj.ID); } }
        if (isCon) { for (Contact obj : [SELECT ID FROM Contact WHERE ID in :verifyID]) { verifiedID.add(obj.ID); } }
    }
    
    public void processDELETE() {
        System.debug('-- JCAR -- KS_Merge_CSVtoFusion_Controller processDELETE!!');
        
        fusionLst = new List<KS_Fusion__c>();
        for (String rowDataStr : csv.split('\r\n'))  {
            
            rowDataStr = rowDataStr.trim();
            if (rowDataStr.contains(';')) {rowDataStr = rowDataStr.split(';')[0];}
            KS_Fusion__c fus = new KS_Fusion__c();
            fus.KS_Id_Principal__c = rowDataStr;
            fus.KS_Accion__c = fusionHeader.KS_Accion__c;
            fus.KS_Tipo__c = fusionHeader.KS_Tipo__c;
            fusionLst.add(fus);
        }
        System.debug('-- JCAR -- KS_Merge_CSVtoFusion_Controller processDELETE fusion -- ' + fusionLst.size() + ' - TOTAL FUSION LIST ' + fusionLst);
        insert fusionLst;
    }
    
    private List<KS_Fusion__c> fusionLst {get;set;}
    
    public void fusion() {
        fusionLst = new List<KS_Fusion__c>();
        for (String IDDUPLI : fusionIndex.keySet()) {
            Set<String> fusionIDs = fusionIndex.get(IDDUPLI);
            for (String IDROW : fusionIDs) {
                String IDSF = objectIndex.get(IDROW);
                if (IDSF == IDDUPLI && IDROW == fusionMain.get(IDDUPLI)) { continue; }
                
                KS_Fusion__c fus = new KS_Fusion__c();
                fus.KS_Id_Principal__c = fusionMain.get(IDDUPLI);
                fus.KS_Id_Duplicado__c = IDROW;
                fus.KS_Accion__c = fusionHeader.KS_Accion__c;
                fus.KS_Tipo__c = fusionHeader.KS_Tipo__c;
                
                if (!verifiedID.contains(fus.KS_Id_Principal__c)) { continue; }
                if (!verifiedID.contains(fus.KS_Id_Duplicado__c)) { continue; }
                if (fus.KS_Id_Principal__c == fus.KS_Id_Duplicado__c) { continue; }
                if (isAcc) {
                    
                    Account acc = (Account)objectMap.get(fusionMain.get(IDDUPLI));
                    if (acc.KS_Email__c != null) 
                    { fus.KS_Acc_Correo__c = acc.KS_Email__c; }
                    if (acc.BillingStreet != null) 
                    { fus.KS_Acc_Calle__c = acc.BillingStreet; }
                    if (acc.BillingCity != null) 
                    { fus.KS_Acc_Ciudad__c = acc.BillingCity; }
                    if (acc.BillingState != null) 
                    { fus.KS_Acc_Estado_Provincia__c = acc.BillingState; }
                    if (acc.BillingPostalCode != null) 
                    { fus.KS_Acc_Codigo_Postal__c = acc.BillingPostalCode; }
                    if (acc.BillingCountryCode != null) 
                    { fus.KS_Acc_Pais__c = acc.BillingCountryCode; }
                    if (acc.Phone != null) 
                    { fus.KS_Acc_Telefono__c = acc.Phone; }
                    if (acc.KS_N_de_telefono_2__c != null) 
                    { fus.KS_Acc_Telefono_2__c = acc.KS_N_de_telefono_2__c; }
                    if (acc.KS_N_de_telefono_3__c != null) 
                    { fus.KS_Acc_Telefono_3__c = acc.KS_N_de_telefono_3__c; }
                    if (acc.KS_Canal__c != null) 
                    { fus.KS_Acc_Canal__c = acc.KS_Canal__c; }
                    if (acc.KS_Actividad__c != null) 
                    { fus.KS_Acc_Actividad__c = acc.KS_Actividad__c; }
                    if (acc.KS_Subactividad__c != null) 
                    { fus.KS_Acc_Subactividad__c = acc.KS_Subactividad__c; }
                    if (acc.KS_Sector__c != null) 
                    { fus.KS_Acc_Sector__c = acc.KS_Sector__c; }
                    
                } else if (isCon) {
                    Contact con = (Contact)objectMap.get(fusionMain.get(IDDUPLI));
                    if (con.Phone != null) 
                    { fus.KS_Ctc_Telefono__c = con.Phone; }
                    if (con.OtherPhone != null) 
                    { fus.KS_Ctc_Telefono_Particular__c = con.OtherPhone; }
                    if (con.MobilePhone != null) 
                    { fus.KS_Ctc_Movil__c = con.MobilePhone; }
                    if (con.Email != null) 
                    { fus.KS_Ctc_Correo__c = con.Email; }
                    if (con.KS_Funcion_en_empresa__c != null) 
                    { fus.KS_Ctc_Funcion_en_empresa__c = con.KS_Funcion_en_empresa__c; }
                    if (con.KS_Idioma__c != null) 
                    { fus.KS_Ctc_Idioma__c = con.KS_Idioma__c; }
                }
                
                fusionLst.add(fus);
            }
        }
        System.debug('-- JCAR -- KS_Merge_CSVtoFusion_Controller fusion -- ' + fusionLst.size() + ' - TOTAL FUSION LIST ' + fusionLst);
        insert fusionLst;
    }
}