src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KS_Canal_SAP__c</fullName>
        <label>Canal SAP</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Canal_de_distribucion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Id_Salesforce__c</fullName>
        <displayFormat>ID-{0000000}</displayFormat>
        <externalId>true</externalId>
        <label>Id Salesforce</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>KS_OC_Fluvia_Export__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OC Fluvia Export</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_OC_Fluvia_Nacional__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OC Fluvia Nacional</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_OC_Simon_Export__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OC Simon Export</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_OC_Simon_Nacional__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OC Simon Nacional</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Organizacion_Ventas__c</fullName>
        <label>Marcas comerciales</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizaciones_de_cuentas__c</fullName>
        <label>Organizaciones de cuentas</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Responsable_FL31__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable FLUVIA</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UsuariosFL31</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Responsable_IE20__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable LIGHTING</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UsuariosIE20</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Responsable_SI10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable SIMON</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UsuariosSI10</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Sector__c</fullName>
        <label>Sector</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>KS_Actividad__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Sector</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>KS_Lead</fullName>
        <active>true</active>
        <description>Tipo de registro, para cuentas de tipo Candidatos</description>
        <label>Cuenta</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/KS_Conf_Organizacion_Cliente__mdt.object
<CustomObject>
    <fields>
        <fullName>KS_Canal_SAP__c</fullName>
        <label>Canal SAP</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Lista_de_precios__c</fullName>
        <label>Lista de precios</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <label>Organizacion de ventas</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Sector__c</fullName>
        <label>Sector</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Organizacion Cliente</label>
    <pluralLabel>Organizaciones Clientes</pluralLabel>
</CustomObject>

src/objects/KS_Estructura_Geografica__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto donde se recoge la configuración de regiones y areas para cada organización</description>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_CPDesde__c</fullName>
        <label>CPDesde</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_CPHasta__c</fullName>
        <label>CPHasta</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_CountryCode__c</fullName>
        <label>CountryCode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ISOCountryCodes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Delegacion__c</fullName>
        <label>Delegación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Delegacion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Zona__c</fullName>
        <label>Zona</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Zona_Geog</valueSetName>
        </valueSet>
    </fields>
    <label>Estructura Geografica</label>
    <nameField>
        <label>Estructura Geografica</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estructuras Geograficas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Organizacion_Cliente__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto vinculado con las cuentas (marcas) que muestra las organizaciones de ventas para cada cliente</description>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Canal_de_distribucion__c</fullName>
        <label>Canal de distribución</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Canal_de_distribucion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Cliente_Dest_Mercancias__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente Dest. Mercancias</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Clientes Dest. Mercancias</relationshipLabel>
        <relationshipName>Clientes_Dest_Mercancias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Cliente_Distribucion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente Distribución</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3) OR 4</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Distribuidores_SAP</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Lead</value>
            </filterItems>
            <filterItems>
                <field>Account.KS_Canal__c</field>
                <operation>equals</operation>
                <value>Distribuidores CRM</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Distribuidores CRM</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marcas Comerciales</relationshipLabel>
        <relationshipName>Organizaciones_Cliente</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Cliente_solicitante__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente solicitante</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marcas Comerciales</relationshipLabel>
        <relationshipName>Clientes_solicitantes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Delegacion__c</fullName>
        <label>Delegación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Delegacion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_ID_Organizacion_Cliente__c</fullName>
        <externalId>true</externalId>
        <label>ID Organizacion Cliente</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>KS_Lista_de_precios__c</fullName>
        <label>Lista de precios</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Lista_de_precios</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Oficinas_de_ventas__c</fullName>
        <label>Oficinas de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Oficinas_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Responsable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ResponablesOrgCliente</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Sector_Distribuidor__c</fullName>
        <label>Sector (Distribuidor)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Tipo_Sector</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Sociedad__c</fullName>
        <label>Sociedad</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Sociedad</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Zona__c</fullName>
        <label>Zona</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Zona_Geog</valueSetName>
        </valueSet>
    </fields>
    <label>Organización Cliente</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Nombre de Organización Cliente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizaciones Cliente</pluralLabel>
    <recordTypes>
        <fullName>KS_OrgClie_NOSAP</fullName>
        <active>true</active>
        <description>Origen Manual</description>
        <label>Organización Cliente</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/ISOCountryCodes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AS</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BQ</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <default>true</default>
        <label>ES</label>
    </customValue>
    <description>EN USO --&gt; Estructuras geográficas / Autorizaciones Ofertas</description>
    <masterLabel>ISOCountryCodes</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Area.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1010</fullName>
    </customValue>
    <customValue>
        <fullName>1020</fullName>
    </customValue>
    <customValue>
        <fullName>1021</fullName>
    </customValue>
    <customValue>
        <fullName>1030</fullName>
    </customValue>
    <customValue>
        <fullName>1040</fullName>
    </customValue>
    <customValue>
        <fullName>1050</fullName>
    </customValue>
    <customValue>
        <fullName>1060</fullName>
    </customValue>
    <customValue>
        <fullName>INTE</fullName>
    </customValue>
    <description>SAP. IDs SAP de Área</description>
    <masterLabel>Área</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Canal_de_distribucion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>Nacional</fullName>
        <isActive>false</isActive>
        <label>Nacional</label>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente - Jerarquia Cliente - Producto --&gt; CARGADO</description>
    <masterLabel>Canal de distribución</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Delegacion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>009</fullName>
    </customValue>
    <customValue>
        <fullName>010</fullName>
    </customValue>
    <customValue>
        <fullName>011</fullName>
    </customValue>
    <customValue>
        <fullName>012</fullName>
    </customValue>
    <customValue>
        <fullName>013</fullName>
    </customValue>
    <customValue>
        <fullName>015</fullName>
    </customValue>
    <customValue>
        <fullName>017</fullName>
    </customValue>
    <customValue>
        <fullName>018</fullName>
    </customValue>
    <customValue>
        <fullName>019</fullName>
    </customValue>
    <customValue>
        <fullName>020</fullName>
    </customValue>
    <customValue>
        <fullName>021</fullName>
    </customValue>
    <customValue>
        <fullName>023</fullName>
    </customValue>
    <customValue>
        <fullName>024</fullName>
    </customValue>
    <customValue>
        <fullName>025</fullName>
    </customValue>
    <customValue>
        <fullName>026</fullName>
    </customValue>
    <customValue>
        <fullName>027</fullName>
    </customValue>
    <customValue>
        <fullName>028</fullName>
    </customValue>
    <customValue>
        <fullName>029</fullName>
    </customValue>
    <customValue>
        <fullName>030</fullName>
    </customValue>
    <customValue>
        <fullName>031</fullName>
    </customValue>
    <customValue>
        <fullName>032</fullName>
    </customValue>
    <customValue>
        <fullName>033</fullName>
    </customValue>
    <customValue>
        <fullName>034</fullName>
    </customValue>
    <customValue>
        <fullName>035</fullName>
    </customValue>
    <customValue>
        <fullName>036</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <description>SAP. IDs SAP de Delegación</description>
    <masterLabel>Delegación</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Lista_de_precios.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>00</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>EC</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>PU</fullName>
    </customValue>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <customValue>
        <fullName>E0</fullName>
    </customValue>
    <customValue>
        <fullName>T0</fullName>
    </customValue>
    <customValue>
        <fullName>T1</fullName>
    </customValue>
    <customValue>
        <fullName>T2</fullName>
    </customValue>
    <customValue>
        <fullName>T3</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
    </customValue>
    <customValue>
        <fullName>B2</fullName>
    </customValue>
    <customValue>
        <fullName>B3</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente --&gt; CARGADO</description>
    <masterLabel>Lista de precios</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Oficinas_de_ventas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>0090</fullName>
    </customValue>
    <customValue>
        <fullName>1010</fullName>
    </customValue>
    <customValue>
        <fullName>1020</fullName>
    </customValue>
    <customValue>
        <fullName>1021</fullName>
    </customValue>
    <customValue>
        <fullName>1030</fullName>
    </customValue>
    <customValue>
        <fullName>1040</fullName>
    </customValue>
    <customValue>
        <fullName>1050</fullName>
    </customValue>
    <customValue>
        <fullName>1060</fullName>
    </customValue>
    <customValue>
        <fullName>5010</fullName>
    </customValue>
    <customValue>
        <fullName>5020</fullName>
    </customValue>
    <customValue>
        <fullName>5030</fullName>
    </customValue>
    <customValue>
        <fullName>5040</fullName>
    </customValue>
    <customValue>
        <fullName>5050</fullName>
    </customValue>
    <customValue>
        <fullName>5060</fullName>
    </customValue>
    <customValue>
        <fullName>5210</fullName>
    </customValue>
    <customValue>
        <fullName>5BEL</fullName>
    </customValue>
    <customValue>
        <fullName>B000</fullName>
    </customValue>
    <customValue>
        <fullName>BR01</fullName>
    </customValue>
    <customValue>
        <fullName>BR02</fullName>
    </customValue>
    <customValue>
        <fullName>BR03</fullName>
    </customValue>
    <customValue>
        <fullName>BR04</fullName>
    </customValue>
    <customValue>
        <fullName>BR05</fullName>
    </customValue>
    <customValue>
        <fullName>BR06</fullName>
    </customValue>
    <customValue>
        <fullName>BRDE</fullName>
    </customValue>
    <customValue>
        <fullName>BRNA</fullName>
    </customValue>
    <customValue>
        <fullName>DELE</fullName>
    </customValue>
    <customValue>
        <fullName>FINT</fullName>
    </customValue>
    <customValue>
        <fullName>IN01</fullName>
    </customValue>
    <customValue>
        <fullName>IN02</fullName>
    </customValue>
    <customValue>
        <fullName>INTE</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente --&gt; CARGADO</description>
    <masterLabel>Oficinas de ventas</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Organizacion_de_ventas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>FL31</fullName>
    </customValue>
    <customValue>
        <fullName>GI50</fullName>
    </customValue>
    <customValue>
        <fullName>IE20</fullName>
    </customValue>
    <customValue>
        <fullName>MA15</fullName>
    </customValue>
    <customValue>
        <fullName>MA16</fullName>
    </customValue>
    <customValue>
        <fullName>MX24</fullName>
    </customValue>
    <customValue>
        <fullName>MX25</fullName>
    </customValue>
    <customValue>
        <fullName>MX26</fullName>
    </customValue>
    <customValue>
        <fullName>SI10</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente / Jerarquia Cliente / Producto / Autorizaciones Oferta --&gt; CARGADO</description>
    <masterLabel>Organizacion de ventas</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Sector.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Residencial</fullName>
    </customValue>
    <customValue>
        <fullName>Terciario</fullName>
    </customValue>
    <customValue>
        <fullName>Hotelero</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Otros</fullName>
    </customValue>
    <customValue>
        <fullName>Edificios administrativos</fullName>
        <isActive>false</isActive>
        <label>Edificios administrativos</label>
    </customValue>
    <customValue>
        <fullName>Industrial (Naves, Fábricas, etc...)</fullName>
        <isActive>false</isActive>
        <label>Industrial (Naves, Fábricas, etc...)</label>
    </customValue>
    <customValue>
        <fullName>Educación</fullName>
        <isActive>false</isActive>
        <label>Educación</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en cuentas</description>
    <masterLabel>Sector</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Sociedad.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>BR17</fullName>
    </customValue>
    <customValue>
        <fullName>BR18</fullName>
    </customValue>
    <customValue>
        <fullName>FL31</fullName>
    </customValue>
    <customValue>
        <fullName>GI50</fullName>
    </customValue>
    <customValue>
        <fullName>IE20</fullName>
    </customValue>
    <customValue>
        <fullName>IN19</fullName>
    </customValue>
    <customValue>
        <fullName>MA15</fullName>
    </customValue>
    <customValue>
        <fullName>MA16</fullName>
    </customValue>
    <customValue>
        <fullName>MX01</fullName>
    </customValue>
    <customValue>
        <fullName>MX24</fullName>
    </customValue>
    <customValue>
        <fullName>MX25</fullName>
    </customValue>
    <customValue>
        <fullName>MX26</fullName>
    </customValue>
    <customValue>
        <fullName>SI10</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente --&gt; CARGADO</description>
    <masterLabel>Sociedad</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Tipo_Sector.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <customValue>
        <fullName>40</fullName>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>60</fullName>
    </customValue>
    <customValue>
        <fullName>70</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente - Jerarquia Cliente - Producto --&gt; CARGADO</description>
    <masterLabel>Tipo Sector (SAP)</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Zona_Geog.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>23</fullName>
    </customValue>
    <customValue>
        <fullName>24</fullName>
    </customValue>
    <customValue>
        <fullName>25</fullName>
    </customValue>
    <customValue>
        <fullName>26</fullName>
    </customValue>
    <customValue>
        <fullName>27</fullName>
    </customValue>
    <customValue>
        <fullName>28</fullName>
    </customValue>
    <customValue>
        <fullName>29</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <description>SAP. En Uso en Oportunidaes/Obras</description>
    <masterLabel>Zona Geog.</masterLabel>
</GlobalValueSet>

src/classes/KS_AccountTrigger.cls
public without sharing class KS_AccountTrigger extends KS_TriggerController {
 
    public KS_AccountTrigger (Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate,
            List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems)
    {
        super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);                 
    }

    public static Map<ID,Boolean> accInUse = new Map<ID,Boolean>();
    
    protected override void runAfterInsert() { executeAfterInsert(); }
    protected override void runAfterUpdate() { executeAfterUpdate(); }
    
    //public void executeAfterInsert() { KS_AccountTrigger.futureUpdate(mapNewItems.keySet()); }
    public void executeAfterInsert() { executeAfterUpsert(); executeNormalizacion(); }
    public void executeAfterUpdate() { executeAfterUpsert(); executeNormalizacion(); }
    
    public void executeAfterUpsert() {

        System.debug('----------------------------------------JCAR - isBatch? : ' + System.isBatch());
        if (System.isBatch()) {return;}
        
        System.debug('----------------------------------------JCAR - isFuture? : ' + System.isFuture());
        if (System.isFuture()) {return;}
        
        Map<String,ID> recordTypes = new Map<String,ID>();
        List<RecordType> rtLst = [SELECT ID,DeveloperName FROM RecordType];
        for (RecordType rt : rtLst) {
            recordTypes.put(rt.DeveloperName, rt.ID);
        }
        
        //Mapeos de configuraciones para ORG:Clientes
        List<KS_Conf_Organizacion_Cliente__mdt> orgConfLst = [SELECT Id, DeveloperName, KS_Organizacion_de_ventas__c, KS_Canal_SAP__c, KS_Sector__c, KS_Lista_de_precios__c FROM KS_Conf_Organizacion_Cliente__mdt];
        Map<ID,KS_Conf_Organizacion_Cliente__mdt> orgConfObjt = new  Map<ID,KS_Conf_Organizacion_Cliente__mdt>(orgConfLst);
        Map<string,string> orgConfMap = new Map<string,string>();
        Map<string,string> orgConfGeoMap = new Map<string,string>();
        for(KS_Conf_Organizacion_Cliente__mdt cnorgcli : orgConfLst)
        {
            orgConfMap.put(cnorgcli.DeveloperName,cnorgcli.Id);
            orgConfGeoMap.put(cnorgcli.DeveloperName+'__c',cnorgcli.KS_Organizacion_de_ventas__c);
        }
        
        // MAPEO CUENTAS LEAD
       
        List<Account> accounts = (List<Account>)lstNewItems;
        Map<ID,Account> leads = new Map<ID,Account>();
        Set<String> mapSAP2Vent = new Set<String>();
        
        for (Account acc : accounts) {
            if (KS_OrgCliente_Trigger.accInUse.containsKey(acc.ID)) {
                if (!Test.isRunningTest()) { System.debug('-- JCAR -- --------------- ALERTA DE RECURSIVIDAD EN CUENTA ' + acc.KS_Id_Salesforce__c + ' - ' + acc.ID + ' - ' + acc.Name); }
                //continue;
            }
            
            if (Test.isRunningTest() && KS_TEST_Debug.isRunning) { acc.Name.addError('TEST_Debug ERROR'); }
            
            if (acc.RecordTypeID == recordTypes.get('KS_Lead')) {
                
                if (!accInUse.containsKey(acc.ID)) { leads.put(acc.ID, acc); }
                accInUse.put(acc.ID, true);
                
                if(acc.KS_OC_Fluvia_Export__c == true)
                {
                    Schema.DescribeFieldResult F = Account.KS_OC_Fluvia_Export__c.getDescribe();
                    string fieldName = F.getLocalName();
                    mapSAP2Vent.add(orgConfGeoMap.get(fieldname));
                }
                if(acc.KS_OC_Fluvia_Nacional__c == true)
                {
                    Schema.DescribeFieldResult F = Account.KS_OC_Fluvia_Nacional__c.getDescribe();
                    string fieldName = F.getLocalName();
                    mapSAP2Vent.add(orgConfGeoMap.get(fieldname));
                }
                if(acc.KS_OC_Simon_Export__c == true)
                {
                    Schema.DescribeFieldResult F = Account.KS_OC_Simon_Export__c.getDescribe();
                    string fieldName = F.getLocalName();
                    mapSAP2Vent.add(orgConfGeoMap.get(fieldname));
                }
                if(acc.KS_OC_Simon_Nacional__c == true)
                {
                    Schema.DescribeFieldResult F = Account.KS_OC_Simon_Nacional__c.getDescribe();
                    string fieldName = F.getLocalName();
                    mapSAP2Vent.add(orgConfGeoMap.get(fieldname));
                }
            }
        }
        
        
        // MAPEOS Y PROCESOS PARA LEAD
        if (!leads.isEmpty()) {
                        
            Set<ID> isSI10 = new Set<ID>(); // SIMON
            Set<ID> isFL31 = new Set<ID>(); // FLUVIA
            Set<ID> isIE20 = new Set<ID>(); // LIGHTING

            List<KS_Organizacion_Cliente__c> newOrgClie = new List<KS_Organizacion_Cliente__c>();
            
            // MAPEO ORG.CLIENTE NUEVAS Y EXISTENTES
            List<ID> accID = new List<ID>(); 
            accID.addAll(leads.keySet());
            
            List<KS_Organizacion_Cliente__c> oCLst = [SELECT ID, KS_Cliente_Distribucion__c, 
                                                      KS_Organizacion_de_ventas__c, KS_Canal_de_distribucion__c, 
                                                      KS_Sector_Distribuidor__c FROM KS_Organizacion_Cliente__c
                                                      WHERE KS_Cliente_Distribucion__c IN :accID];
            //Mapeo Estructuras Geográficas
            List<KS_Estructura_Geografica__c> esGeogLst = [SELECT Id, KS_CPDesde__c, KS_CPHasta__c, KS_Delegacion__c, KS_Area__c, KS_Zona__c, KS_Organizacion_de_ventas__c, KS_CountryCode__c FROM KS_Estructura_Geografica__c WHERE KS_Organizacion_de_ventas__c in :mapSAP2Vent];
            
            for (Account acc : leads.values()) {
                
                Account accOLD = new Account();
                if (isUpdate) {
                    accOLD = (Account) mapOldItems.get(acc.ID);
                    //if (acc.KS_Organizaciones_de_cuentas__c != null && acc.KS_Organizacion_Ventas__c == accOLD.KS_Organizacion_Ventas__c) {
                    if (acc.KS_Organizaciones_de_cuentas__c != null && acc.KS_OC_Simon_Nacional__c == accOLD.KS_OC_Simon_Nacional__c && acc.KS_OC_Fluvia_Nacional__c == accOLD.KS_OC_Fluvia_Nacional__c && acc.KS_OC_Simon_Export__c == accOLD.KS_OC_Simon_Export__c && acc.KS_OC_Fluvia_Export__c == accOLD.KS_OC_Fluvia_Export__c) 
                    {
                        system.debug('Entro en el if');
                        continue;
                    }
                }
                
                
                
                /*
                String marcas = acc.KS_Organizacion_Ventas__c;
                String[] marcasA = acc.KS_Organizacion_Ventas__c.split(';');
                
                for (KS_Organizacion_Cliente__c oc : oCLst) {
                    String marca = oc.KS_Organizacion_de_ventas__c;
                    
                    // Detectamos que existe ya una org cliente para esa cuenta lead
                    if (oc.KS_Cliente_Distribucion__c == acc.ID) {
                        if (marca == 'SI10') { isSI10.add(acc.ID); }
                        if (marca == 'FL31') { isFL31.add(acc.ID); }
                        if (marca == 'IE20') { isIE20.add(acc.ID); }
                    }
                }*/
                
                //Miro las organizaciones de cliente a crear en base a los checkboxes. 
                List<string> organizaciones = new List<string>();
                system.debug('-- JCAR ------------------------------------------ organizaciones?' + 
                             ' - KS_OC_Simon_Nacional__c ' + acc.KS_OC_Simon_Nacional__c + 'isChanged? ' + (acc.KS_OC_Simon_Nacional__c != accOLD.KS_OC_Simon_Nacional__c) +
                             ' - KS_OC_Simon_Export__c ' + acc.KS_OC_Simon_Export__c + 'isChanged? ' + (acc.KS_OC_Simon_Export__c != accOLD.KS_OC_Simon_Export__c) +
                             ' - KS_OC_Fluvia_Nacional__c ' + acc.KS_OC_Fluvia_Nacional__c + 'isChanged? ' + (acc.KS_OC_Fluvia_Nacional__c != accOLD.KS_OC_Fluvia_Nacional__c) +
                             ' - KS_OC_Fluvia_Export__c ' + acc.KS_OC_Fluvia_Export__c + 'isChanged? ' + (acc.KS_OC_Fluvia_Export__c != accOLD.KS_OC_Fluvia_Export__c)
                            );
                if(acc.KS_OC_Fluvia_Export__c == true && acc.KS_OC_Fluvia_Export__c != accOLD.KS_OC_Fluvia_Export__c)
                {
                    Schema.DescribeFieldResult F = Account.KS_OC_Fluvia_Export__c.getDescribe();
                    string fieldName = F.getLocalName();
                    organizaciones.add(fieldname.removeEnd('__c'));
                }
                if(acc.KS_OC_Fluvia_Nacional__c == true && acc.KS_OC_Fluvia_Nacional__c != accOLD.KS_OC_Fluvia_Nacional__c)
                {
                    Schema.DescribeFieldResult F = Account.KS_OC_Fluvia_Nacional__c.getDescribe();
                    string fieldName = F.getLocalName();
                    organizaciones.add(fieldname.removeEnd('__c'));
                }
                if(acc.KS_OC_Simon_Export__c == true && acc.KS_OC_Simon_Export__c != accOLD.KS_OC_Simon_Export__c)
                {
                    Schema.DescribeFieldResult F = Account.KS_OC_Simon_Export__c.getDescribe();
                    string fieldName = F.getLocalName();
                    organizaciones.add(fieldname.removeEnd('__c'));
                }
                if(acc.KS_OC_Simon_Nacional__c == true && acc.KS_OC_Simon_Nacional__c != accOLD.KS_OC_Simon_Nacional__c)
                {
                    Schema.DescribeFieldResult F = Account.KS_OC_Simon_Nacional__c.getDescribe();
                    string fieldName = F.getLocalName();
                    organizaciones.add(fieldname.removeEnd('__c'));
                }
                system.debug('-- JCAR ------------------------------------------ ' + organizaciones.size() + ' organizaciones:' + organizaciones);
                
                // Miramos cuales crear nuevas
                for (String marca : organizaciones) {
                    
                    String countryS = acc.ShippingCountryCode != null ? acc.ShippingCountryCode : acc.BillingCountryCode;
            		Boolean validCountry = (countryS == 'ES' || countryS == 'PT' || countryS == 'AD');
            		String postalCodeS = acc.ShippingPostalCode != null ? acc.ShippingPostalCode : acc.BillingPostalCode;
                    
                    string OficinaVentas = EstructGeo(postalCodeS,countryS,validCountry,esGeogLst);
                    //system.debug('Otro Mapa: ' + orgConfObjt);
                    //system.debug('Mapa: ' + orgConfMap);
                    //system.debug('Marca: ' + marca);
                    KS_Organizacion_Cliente__c oc = new KS_Organizacion_Cliente__c();
                    KS_Conf_Organizacion_Cliente__mdt conf = orgConfObjt.get(orgConfMap.get(marca));
                    
                    String idacc = 
                        KS_OrgCliente_Util.buildID(
                            acc.KS_Id_Salesforce__c,
                            acc.KS_Id_Salesforce__c, 
                            acc.KS_Id_Salesforce__c, 
                            conf.KS_Organizacion_de_ventas__c, 
                            conf.KS_Canal_SAP__c, 
                            conf.KS_Sector__c, 
                            OficinaVentas);
                                        
                    oc.KS_Cliente_Distribucion__c = acc.ID;
                    oc.KS_Cliente_solicitante__c = acc.ID;
                    oc.KS_Cliente_Dest_Mercancias__c = acc.ID;
                    oc.KS_ID_Organizacion_Cliente__c = idacc;
                    oc.KS_Oficinas_de_ventas__c = OficinaVentas;

                    oc.KS_Organizacion_de_ventas__c = conf.KS_Organizacion_de_ventas__c;
                    oc.KS_Sociedad__c = conf.KS_Organizacion_de_ventas__c;
                    oc.KS_Canal_de_distribucion__c = conf.KS_Canal_SAP__c;
                    oc.KS_Sector_Distribuidor__c = conf.KS_Sector__c;
                    oc.KS_Lista_de_precios__c = conf.KS_Lista_de_precios__c;
                    oc.RecordTypeId = recordTypes.get('KS_OrgClie_NOSAP');

                    if (!accInUse.containsKey(acc.ID)) {
                        accInUse.put(acc.ID, true);
                    }
                    newOrgClie.add(oc);
                    
                    /*
                    if (marca == 'SI10' && !isSI10.contains(acc.ID)) 
                    { isSI10.add(acc.ID); newOrgClie.add(oc); }
                    if (marca == 'FL31' && !isFL31.contains(acc.ID)) 
                    { isFL31.add(acc.ID); newOrgClie.add(oc); }
                    if (marca == 'IE20' && !isIE20.contains(acc.ID)) 
                    { isIE20.add(acc.ID); newOrgClie.add(oc); }
					*/
                }
            }
            
            if (!Test.isRunningTest()) { System.debug('-- JCAR ---------------------------------- - UPSERT newOrgClie? ' + newOrgClie.size() + ' - ' + newOrgClie); }
            if (!newOrgClie.isEmpty()) { 
                
                Schema.DescribeFieldResult field = KS_Organizacion_Cliente__c.KS_ID_Organizacion_Cliente__c.getDescribe();
                Schema.sObjectField idSAP = field.getSObjectField();
                Database.UpsertResult[] upsertResult = Database.upsert(newOrgClie, idSAP, true);                  
                //upsert newOrgClie; 
            }
            
            if (!Test.isRunningTest()) {future_setResponsablesLead(leads.keySet());}
            
            
            
/*            oCLst = [SELECT ID, KS_Cliente_Distribucion__c, KS_Responsable__c,
                     KS_Organizacion_de_ventas__c, KS_Canal_de_distribucion__c, 
                     KS_Sector_Distribuidor__c FROM KS_Organizacion_Cliente__c
                     WHERE KS_Cliente_Distribucion__c IN :accID];*/
            
            if (!Test.isRunningTest()) { System.debug('-------------------------JCAR - userProfile - ' + getProfile()); }
            
        }
    }
    
    public void executeNormalizacion() {
        
        System.debug('-------------------------JCAR - accInUse - ' + accInUse);
        if (accInUse.isEmpty()) {
            
            if (!KS_Normalizacion_Utils.getConfigurationFlag('NormalizacionCuentaStatus')) {return;}
            
            accInUse = accInUse != null ? accInUse : new Map<ID,Boolean>();
            for (ID key : mapNewItems.keySet()) { accInUse.put(key,true); }
            KS_Normalizacion_Utils.executeNormalizacion(Account.class.getName(), lstNewItems);
        }
    }
    
    @future(callout=true)
    public static void future_setResponsablesLead(Set<ID> accounts) {
		
        if (Test.isRunningTest()) {return;}
        System.debug('-------------------------JCAR - future_setResponsablesLead');
        
        Map<ID, Account> accUPDATE = new Map<ID, Account>();
        List<ID> accID = new List<ID>(); accID.addAll(accounts);
        List<KS_Organizacion_Cliente__c> oCLst = [SELECT ID, KS_Cliente_Distribucion__c, KS_Cliente_solicitante__c, 
                                                  KS_Responsable__c, KS_Organizacion_de_ventas__c, KS_Canal_de_distribucion__c, 
                                                  KS_Sector_Distribuidor__c FROM KS_Organizacion_Cliente__c
                                                  WHERE KS_Responsable__c != NULL AND 
                                                  (KS_Cliente_Distribucion__c IN :accID OR
                                                   (KS_Cliente_solicitante__c IN :accID AND KS_Cliente_Distribucion__c = null)
                                                  )
                                                  ];
        
        System.debug('-- JCAR ---------------------------------- - SELECT oCLst? ' + oCLst.size() + ' - ' + oCLst);
        for (KS_Organizacion_Cliente__c oC : oCLst) {
            
            Account acc = new Account();
            acc.ID = oC.KS_Cliente_Distribucion__c;
            acc.ID = acc.ID != null ? acc.ID : oC.KS_Cliente_solicitante__c;            
            if (accUPDATE.containsKey(acc.ID)) { acc = accUPDATE.get(acc.ID); }
            
            String marca = oC.KS_Organizacion_de_ventas__c;
            if (marca == 'SI10' && acc.KS_Responsable_SI10__c != oC.KS_Responsable__c)
            { acc.KS_Responsable_SI10__c = oC.KS_Responsable__c; accUPDATE.put(acc.ID, acc); }
            if (marca == 'FL31' && acc.KS_Responsable_FL31__c != oC.KS_Responsable__c)
            { acc.KS_Responsable_FL31__c = oC.KS_Responsable__c; accUPDATE.put(acc.ID, acc); }
            if (marca == 'IE20' && acc.KS_Responsable_IE20__c != oC.KS_Responsable__c)
            { acc.KS_Responsable_IE20__c = oC.KS_Responsable__c; accUPDATE.put(acc.ID, acc); }            
        }
        
        System.debug('-- JCAR ---------------------------------- - UPDATE accUPDATE? ' + accUPDATE.size() + ' - ' + accUPDATE);
        if (!accUPDATE.isEmpty()) { update accUPDATE.values(); }
    }
    
    /*
    @future(callout=true)
    public static void futureUpdate(Set<ID> accounts) {
        System.debug('-- JCAR ---------------------------------- - isRunningTest? : ' + Test.isRunningTest());
        if (Test.isRunningTest()) {return;}
        System.debug('-- JCAR ---------------------------------- - futureUpdate.accounts? ' + accounts.size() + ' accounts - ' + accounts);
        List<ID> ids = new List<ID>(); ids.addAll(accounts);
    	TerritoryMangRule.fireTerritoryManagementViaSoap(ids);
    }
    
    public void executeBeforeUpdate() {
        
        Map<String,ID> recordTypes = new Map<String,ID>();
        List<RecordType> rtLst = [SELECT ID,DeveloperName FROM RecordType];
        for (RecordType rt : rtLst) {
            recordTypes.put(rt.DeveloperName, rt.ID);
        }        
        List<Account> accounts = (List<Account>)lstNewItems;
        List<Account> cuentas = new List<Account>();
        
        Set<ID> cuentasID = new Set<ID>();
        Map<ID,List<String>> marcasCuenta = new Map<ID,List<String>>();
        Set<String> marcas = new Set<String>();
        Map<ID, String> areaCuenta = new Map<ID, String>();
        
        System.debug('-- JCAR ---------------------------------- - executeAfterInsert.accounts? ' + accounts.size() + ' accounts - ' + accounts);
        //KS_Lead
        for (Account acc : accounts) {
            if ( acc.RecordTypeID == recordTypes.get('KS_Lead') && acc.KS_Organizaciones_de_cuentas__c != null && acc.KS_Organizaciones_de_cuentas__c != '') {
                cuentas.add(acc);
                List<String> mrcs = new List<String>();
                for (String s : acc.KS_Organizaciones_de_cuentas__c.split(';')) {
                    if (s.trim() != '') {
                        marcas.add( s.split('-')[0] );
                        areaCuenta.put(acc.ID, s.split('-')[3]);
                    }
                }
                marcasCuenta.put(acc.ID, mrcs);
            }
        }
        if (!cuentas.isEmpty() && !marcas.isEmpty() && !marcasCuenta.isEmpty()) {
        	KS_Aprobaciones_Controller.setAprobacionesCuenta(cuentas, marcas, marcasCuenta, areaCuenta);
            //update cuentas; // En un before la actualización ocurre por si sola
        }
    }*/  
    
    private String getProfile() {
        List<Profile> profLst = [SELECT ID,Name FROM Profile];
        for (Profile prof : profLst) {
            if (prof.ID == userInfo.getProfileId()) { return prof.Name; }
        }
        return '';
    }
    public string EstructGeo(string postalCodeS,string countryS,Boolean validCountry,List<KS_Estructura_Geografica__c> esGeogLst)
    {
        string retorno = '';
        Boolean next = false; Integer i = 0;
        while (!next && i<esGeogLst.size() && validCountry && postalCodeS != null) {
            
            KS_Estructura_Geografica__c eg = esGeogLst.get(i);
            String dsd = eg.KS_CPDesde__c;
            String hst = eg.KS_CPHasta__c;
            
            if (eg.KS_CountryCode__c == countryS && (countryS == 'AD' || countryS == 'ES') ) { // ANDORRA || ESPAÑA

                next = postalCodeS.startsWithIgnoreCase(dsd.substring(0,2));
                
            } else if (countryS == 'PT' && eg.KS_CountryCode__c == countryS) { // PORTUGAL
                
                if (dsd.split('-')[0].isNumeric() && hst.split('-')[0].isNumeric() && postalCodeS.split('-')[0].split(' ')[0].isNumeric()) {
                    Integer z = Integer.valueOf(postalCodeS.split('-')[0].split(' ')[0]);
                    Integer x = Integer.valueOf(dsd.split('-')[0]);
                    Integer y = Integer.valueOf(hst.split('-')[0]);
                    next = (z >= x && z <= y);
                }
                
            } else { // Internacional, se sigue otra lógica
                
                next = eg.KS_CountryCode__c == countryS && countryS == eg.KS_Delegacion__c && eg.KS_Area__c == 'INTE';
            }
            
            if (next) { // se ha encontrado un CP
                //mapPC2EG.put(postalCodeS, eg);
                retorno = eg.KS_Area__c;
                
            }
            i++;
        }
        return retorno;
    }
}