src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KS_Actividad__c</fullName>
        <label>Actividad</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Actividad</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <label>Canal</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KS_Actividad__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Canal</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Grupo_de_ctas_deudor__c</fullName>
        <label>Grupo de ctas. deudor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Grupo_de_ctas_deudor</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Id_SAP__c</fullName>
        <externalId>true</externalId>
        <label>Id SAP</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>KS_Idioma__c</fullName>
        <label>Idioma</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Idiomas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_N_de_telefono_2__c</fullName>
        <label>Nº de telefono 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>KS_N_identificacion_fiscal_suplementario__c</fullName>
        <label>Nº identificación fiscal suplementario</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Nombre_2__c</fullName>
        <label>Nombre Fiscal</label>
        <length>71</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Numero_de_identificacion_fiscal_1__c</fullName>
        <label>NIF</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Tipo__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Tipo</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>KS_Distribuidores_SAP</fullName>
        <active>true</active>
        <description>Tipo de registro para albergar clientes distribuidores provenientes de SAP</description>
        <label>Distribuidores SAP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>KS_Idioma__c</fullName>
        <label>Idioma</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Idiomas</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KS_Estructura_Geografica__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto donde se recoge la configuración de regiones y areas para cada organización</description>
    <label>Estructura Geografica</label>
    <nameField>
        <label>Estructura Geografica</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estructuras Geograficas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Fusion__c.object
<CustomObject>
    <fields>
        <fullName>KS_Acc_Actividad__c</fullName>
        <label>KS_Acc_Actividad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Calle__c</fullName>
        <label>KS_Acc_Calle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Canal__c</fullName>
        <label>KS_Acc_Canal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Ciudad__c</fullName>
        <label>KS_Acc_Ciudad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Codigo_Postal__c</fullName>
        <label>KS_Acc_Codigo_Postal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Correo__c</fullName>
        <label>KS_Acc_Correo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Estado_Provincia__c</fullName>
        <label>KS_Acc_Estado_Provincia</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Pais__c</fullName>
        <label>KS_Acc_Pais</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Sector__c</fullName>
        <label>KS_Acc_Sector</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Subactividad__c</fullName>
        <label>KS_Acc_Subactividad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Telefono_2__c</fullName>
        <label>KS_Acc_Telefono_2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Telefono_3__c</fullName>
        <label>KS_Acc_Telefono_3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Telefono__c</fullName>
        <label>KS_Acc_Telefono</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Accion__c</fullName>
        <label>KS_Accion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MERGE</fullName>
                </value>
                <value>
                    <fullName>DELETE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Ctc_Calle__c</fullName>
        <label>KS_Ctc_Calle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Cargo__c</fullName>
        <label>KS_Ctc_Cargo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Ciudad__c</fullName>
        <label>KS_Ctc_Ciudad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Codigo_Postal__c</fullName>
        <label>KS_Ctc_Codigo_Postal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Correo__c</fullName>
        <label>KS_Ctc_Correo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Estado_Provincia__c</fullName>
        <label>KS_Ctc_Estado_Provincia</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Funcion_en_empresa__c</fullName>
        <label>KS_Ctc_Funcion_en_empresa</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Idioma__c</fullName>
        <label>KS_Ctc_Idioma</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Movil__c</fullName>
        <label>KS_Ctc_Movil</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Pais__c</fullName>
        <label>KS_Ctc_Pais</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Telefono_Particular__c</fullName>
        <label>KS_Ctc_Telefono_Particular</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Telefono__c</fullName>
        <label>KS_Ctc_Telefono</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Id_Duplicado_2__c</fullName>
        <label>KS_Id_Duplicado_2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Id_Duplicado__c</fullName>
        <label>KS_Id_Duplicado</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Id_Principal__c</fullName>
        <label>KS_Id_Principal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Tipo__c</fullName>
        <label>KS_Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACCOUNT</fullName>
                </value>
                <value>
                    <fullName>CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fusion</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Fusion ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fusiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Obra__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Es el objeto superior que agrega las ofertas (oportunidades)</description>
    <fields>
        <fullName>KS_Actividad__c</fullName>
        <label>ID Actividad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Obra</label>
    <nameField>
        <label>Nombre de Obra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Obras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Organizacion_Cliente__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto vinculado con las cuentas (marcas) que muestra las organizaciones de ventas para cada cliente</description>
    <label>Organización Cliente</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Nombre de Organización Cliente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizaciones Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <formula>TEXT(KS_Organizacion_Cliente__r.KS_Canal_de_distribucion__c)</formula>
        <label>Canal</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>KS_Obra__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Oportunidades</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KS_Obra__c</referenceTo>
        <relationshipLabel>Ofertas</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Organizacion_Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marca Comercial</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>KS_Organizacion_Cliente__c.KS_Cliente_solicitante__c</field>
                <operation>equals</operation>
                <valueField>$Source.KS_Distribuidor__c</valueField>
            </filterItems>
            <filterItems>
                <field>KS_Organizacion_Cliente__c.KS_Cliente_Distribucion__c</field>
                <operation>equals</operation>
                <valueField>$Source.KS_Distribuidor__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KS_Organizacion_Cliente__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Idiomas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ES</fullName>
        <default>true</default>
        <label>ES</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
    </customValue>
    <customValue>
        <fullName>ZF</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>CAT</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Contactos / Cliente Distribucion --&gt; CARGADO</description>
    <masterLabel>Idiomas</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Actividad.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alojamiento Turístico</fullName>
    </customValue>
    <customValue>
        <fullName>Arquitectura</fullName>
    </customValue>
    <customValue>
        <fullName>Bancos y cajas</fullName>
    </customValue>
    <customValue>
        <fullName>Centros comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Compañías de Seguros</fullName>
    </customValue>
    <customValue>
        <fullName>Consultoras Inmobiliarias</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidor</fullName>
    </customValue>
    <customValue>
        <fullName>Educación</fullName>
    </customValue>
    <customValue>
        <fullName>Gran empresa Privada</fullName>
    </customValue>
    <customValue>
        <fullName>Ingeniería</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Integrador</fullName>
    </customValue>
    <customValue>
        <fullName>Interiorista</fullName>
    </customValue>
    <customValue>
        <fullName>Laboratorio</fullName>
    </customValue>
    <customValue>
        <fullName>Moda y Complementos</fullName>
    </customValue>
    <customValue>
        <fullName>Organismos Oficiales</fullName>
    </customValue>
    <customValue>
        <fullName>Reformistas</fullName>
    </customValue>
    <customValue>
        <fullName>Restauración</fullName>
    </customValue>
    <customValue>
        <fullName>Sanidad</fullName>
    </customValue>
    <customValue>
        <fullName>TEI</fullName>
    </customValue>
    <customValue>
        <fullName>Alimentación</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion/Gremio Instaladores</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion DME</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion Domoticas</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones EE y VE</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones Prensa</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones Sectorial</fullName>
    </customValue>
    <customValue>
        <fullName>Asociacion Light Designers e iluminacion</fullName>
    </customValue>
    <customValue>
        <fullName>Automoción</fullName>
    </customValue>
    <customValue>
        <fullName>Bienestar</fullName>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en cuentas</description>
    <masterLabel>Actividad</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Canal.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Distribuidores CRM</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Prescriptores</fullName>
    </customValue>
    <customValue>
        <fullName>Clientes finales</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidores SAP</fullName>
    </customValue>
    <customValue>
        <fullName>Varios</fullName>
        <isActive>false</isActive>
        <label>Varios</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en Cuentas</description>
    <masterLabel>Canal</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Grupo_de_ctas_deudor.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
    </customValue>
    <customValue>
        <fullName>0002</fullName>
    </customValue>
    <customValue>
        <fullName>0003</fullName>
    </customValue>
    <customValue>
        <fullName>0004</fullName>
    </customValue>
    <customValue>
        <fullName>0012</fullName>
    </customValue>
    <customValue>
        <fullName>Z001</fullName>
    </customValue>
    <customValue>
        <fullName>Z010</fullName>
    </customValue>
    <customValue>
        <fullName>Z011</fullName>
    </customValue>
    <customValue>
        <fullName>Z014</fullName>
    </customValue>
    <customValue>
        <fullName>Z015</fullName>
    </customValue>
    <customValue>
        <fullName>ZE01</fullName>
    </customValue>
    <customValue>
        <fullName>ZEXT</fullName>
    </customValue>
    <customValue>
        <fullName>ZINT</fullName>
    </customValue>
    <customValue>
        <fullName>Z009</fullName>
    </customValue>
    <customValue>
        <fullName>Z012</fullName>
    </customValue>
    <customValue>
        <fullName>Z013</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Cliente Distribucion --&gt; CARGADO</description>
    <masterLabel>Grupo de ctas. deudor</masterLabel>
</GlobalValueSet>

src/globalValueSets/Tipo.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Punto de venta</fullName>
    </customValue>
    <customValue>
        <fullName>Punto de compra</fullName>
    </customValue>
    <customValue>
        <fullName>Central compras</fullName>
    </customValue>
    <customValue>
        <fullName>Público</fullName>
    </customValue>
    <customValue>
        <fullName>Privado</fullName>
    </customValue>
    <customValue>
        <fullName>Explotación</fullName>
    </customValue>
    <description>SEGMENTACIÓN. Variable usada en segmentación de cuentas.</description>
    <masterLabel>Tipo</masterLabel>
</GlobalValueSet>

src/classes/KS_TEST_MergeTool_MergeAuto.cls
@isTest
private class KS_TEST_MergeTool_MergeAuto
{
	@testSetUp
	static void DataSetUp()
	{
        KS_Trigger_Test.disableTrigger();
		KS_TEST_FUNCTIONS func  = new KS_TEST_FUNCTIONS();
		Map<String, ID> rd = KS_TEST_FUNCTIONS.getRecordTypeStatic();
		Account acc = func.createAccDistribuidor(rd);
		//Accounts de merge
		Account acc2 = new Account();
        ID rt = rd.get('KS_Distribuidores_SAP');
        acc2.RecordTypeId = rt;
        
        acc2.Name = 'Test Cuenta2';
        acc2.KS_Id_SAP__c = 'IDSAPTEST1232';
        acc2.Phone = '666666662';
        acc2.BillingCountryCode = 'ES';
        acc2.BillingCity = 'Barcelona';
        acc2.BillingPostalCode = '08907';
        acc2.BillingStreet = 'Calle de gracia';
        acc2.KS_Grupo_de_ctas_deudor__c = '0001';
        acc2.KS_Idioma__c = 'ES';
        acc2.KS_Nombre_2__c = 'Cliente Distribuidor TEST2';
        acc2.KS_N_identificacion_fiscal_suplementario__c = '1';
        acc2.KS_Numero_de_identificacion_fiscal_1__c = '1';
        acc2.KS_N_de_telefono_2__c = '1';
        acc2.KS_Actividad__c = 'Distribuidor';
        acc2.KS_Canal__c = 'Distribuidores SAP';
		insert acc2;

		Account acc3 = new Account();
        acc3.RecordTypeId = rt;
        
        acc3.Name = 'Test Cuenta3';
        acc3.KS_Id_SAP__c = 'IDSAPTEST123';
        acc3.Phone = '66666666';
        acc3.BillingCountryCode = 'ES';
        acc3.BillingCity = 'Barcelona';
        acc3.BillingPostalCode = '08907';
        acc3.BillingStreet = 'Calle de gracia';
        acc3.KS_Grupo_de_ctas_deudor__c = '0001';
        acc3.KS_Idioma__c = 'ES';
        acc3.KS_Nombre_2__c = 'Cliente Distribuidor TEST23';
        acc3.KS_N_identificacion_fiscal_suplementario__c = '1';
        acc3.KS_Numero_de_identificacion_fiscal_1__c = '1';
        acc3.KS_N_de_telefono_2__c = '1';
        acc3.KS_Actividad__c = 'Distribuidor';
        acc3.KS_Canal__c = 'Distribuidores SAP';
		insert acc3;


		//Contactos para borrar
		Contact c1 = func.createContact(acc);
		Contact c2 = new Contact();
		c2.AccountId = acc.id;
        c2.Salutation = 'Sr.';
		c2.FirstName = 'Pruebo2';
        c2.LastName = 'Testeo';
		insert c2;

		Contact c3 = new Contact();
		c3.AccountId = acc.id;
        c3.Salutation = 'Sr.';
		c3.FirstName = 'Pruebo3';
        c3.LastName = 'Testez3';
		insert c3;

		//Contactos que darán error. 
		Contact c4 = new Contact();
		c4.AccountId = acc.id;
        c4.Salutation = 'Sr.';
		c4.FirstName = 'Pruebo4';
        c4.LastName = 'Testez4';
		insert c4;

		//Contactos que se fusionan
		Contact fusion1 = new Contact();
		fusion1.AccountId = acc.id;
        fusion1.Salutation = 'Sr.';
		fusion1.FirstName = 'fusion1';
        fusion1.LastName = 'Testeo';
		insert fusion1;
		Contact fusion2 = new Contact();
		fusion2.AccountId = acc.id;
        fusion2.Salutation = 'Sr.';
		fusion2.FirstName = 'fusion2';
        fusion2.LastName = 'Testeo';
		insert fusion2;
		Contact fusion3 = new Contact();
		fusion3.AccountId = acc.id;
        fusion3.Salutation = 'Sr.';
		fusion3.FirstName = 'fusion3';
        fusion3.LastName = 'Testeo';
		insert fusion3;
		
		KS_Estructura_Geografica__c geo = func.createEstructuraGeografica(acc);
		KS_Organizacion_Cliente__c orgAcc = func.createAccDistribuidorOrganizacion(acc, geo);
		KS_Obra__c obra = func.createObra(rd);
		Pricebook2 pbS = func.createPricebook();
		Opportunity oferta = func.createOferta(acc, orgAcc, obra,pbS);
		func.createOfertaPendiente(oferta);
		func.createTaskforContact(c4);
		func.createEventforContact(c4);
		func.createReporteforContact(c4);
		func.createIntervinientesforContact(c4,obra,acc);

		List<KS_Fusion__c> fusionLSt = new List<KS_Fusion__c>();
		KS_Fusion__c fu1 = new KS_Fusion__c();
		fu1.KS_Id_Principal__c = c1.Id;
		fu1.KS_Accion__c = 'DELETE';
		fusionLSt.add(fu1);
		KS_Fusion__c fu2 = new KS_Fusion__c();
		fu2.KS_Id_Principal__c = c2.Id;
		fu2.KS_Accion__c = 'DELETE';
		fusionLSt.add(fu2);
		KS_Fusion__c fu3 = new KS_Fusion__c();
		fu3.KS_Id_Principal__c = c3.Id;
		fu3.KS_Accion__c = 'DELETE';
		fusionLSt.add(fu3);
		KS_Fusion__c fu4 = new KS_Fusion__c();
		fu4.KS_Id_Principal__c = c4.Id;
		fu4.KS_Accion__c = 'DELETE';
		fusionLSt.add(fu4);

		//Fusion ok
		KS_Fusion__c fusionCn = new KS_Fusion__c();
		fusionCn.KS_Id_Principal__c = fusion1.Id;
		fusionCn.KS_Id_Duplicado__c = fusion2.Id;
		fusionCn.KS_Id_Duplicado_2__c = fusion3.Id;
		fusionCn.KS_Ctc_Calle__c = 'Calle';
		fusionCn.KS_Ctc_Cargo__c = 'Cargo';
		fusionCn.KS_Ctc_Ciudad__c = 'Madrid';
		fusionCn.KS_Ctc_Codigo_Postal__c = '28039';
		fusionCn.KS_Ctc_Correo__c = 'correo@correo.com';
		fusionCn.KS_Ctc_Estado_Provincia__c = 'Madrid';
		fusionCn.KS_Ctc_Funcion_en_empresa__c = 'Compras';
		fusionCn.KS_Ctc_Idioma__c = 'ES';
		fusionCn.KS_Ctc_Movil__c = '666666666';
		fusionCn.KS_Ctc_Pais__c = 'España';
		fusionCn.KS_Ctc_Telefono__c = '123456789';
		fusionCn.KS_Ctc_Telefono_Particular__c = '123456789';
		fusionCn.KS_Accion__c = 'MERGE';
		fusionCn.KS_Tipo__c = 'CONTACT';
		fusionLSt.add(fusionCn);

		//Fusion Accounts
		KS_Fusion__c fusionAcc = new KS_Fusion__c();
		fusionAcc.KS_Id_Principal__c = acc.Id;
		fusionAcc.KS_Id_Duplicado__c = acc2.Id;
		fusionAcc.KS_Id_Duplicado_2__c = acc3.Id;
		fusionAcc.KS_Acc_Actividad__c = 'Distribuidor';
		fusionAcc.KS_Acc_Calle__c = 'Calle';
		fusionAcc.KS_Acc_Canal__c = 'Distribuidores SAP';
		fusionAcc.KS_Acc_Ciudad__c = 'Madrid';
		fusionAcc.KS_Acc_Codigo_Postal__c = '28039';
		fusionAcc.KS_Acc_Correo__c= 'correo@correo.com';
		fusionAcc.KS_Acc_Estado_Provincia__c = 'Madrid';
		fusionAcc.KS_Acc_Pais__c = 'España';
		fusionAcc.KS_Acc_Sector__c = 'Residencial';
		fusionAcc.KS_Acc_Subactividad__c = 'Eléctrico';
		fusionAcc.KS_Acc_Telefono_2__c = '123456789';
		fusionAcc.KS_Acc_Telefono_3__c = '123456780';
		fusionAcc.KS_Acc_Telefono__c = '012345678';
		fusionAcc.KS_Accion__c = 'MERGE';
		fusionAcc.KS_Tipo__c = 'ACCOUNT';
		
		fusionLSt.add(fusionAcc);
		insert fusionLSt;
        KS_Trigger_Test.enableTrigger();

	}
	@isTest
	static void itShould_DeleteContacts()
	{
		KS_Batch_MergeTool_DeleteContacts del = new KS_Batch_MergeTool_DeleteContacts();
        ID batchprocessid = Database.executeBatch(del);
	}
	@isTest
	static void itShould_MergeContacts()
	{
		KS_Batch_MergeTool_MergeContacts mrgCn = new KS_Batch_MergeTool_MergeContacts();
        ID batchprocessid = Database.executeBatch(mrgCn);
	}
	@isTest
	static void itShould_MergeAccounts()
	{
		KS_Batch_MergeTool_MergeAccounts mrgAcc = new KS_Batch_MergeTool_MergeAccounts();
        ID batchprocessid = Database.executeBatch(mrgAcc);
	}
}