src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KS_Canal_SAP__c</fullName>
        <label>Canal SAP</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Canal_de_distribucion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <label>Canal</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KS_Actividad__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Canal</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizacion_Ventas__c</fullName>
        <label>Marcas comerciales</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizaciones_de_cuentas__c</fullName>
        <label>Organizaciones de cuentas</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Responsable_FL31__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable FLUVIA</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UsuariosFL31</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Responsable_IE20__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable LIGHTING</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UsuariosIE20</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Responsable_SI10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable SIMON</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UsuariosSI10</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Sector_SAP__c</fullName>
        <label>Sector SAP</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Tipo_Sector</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>KS_Lead</fullName>
        <active>true</active>
        <description>Tipo de registro, para cuentas de tipo Candidatos</description>
        <label>Cuenta</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/KS_Organizacion_Cliente__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto vinculado con las cuentas (marcas) que muestra las organizaciones de ventas para cada cliente</description>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Cliente_Distribucion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente Distribución</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3) OR 4</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Distribuidores_SAP</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Lead</value>
            </filterItems>
            <filterItems>
                <field>Account.KS_Canal__c</field>
                <operation>equals</operation>
                <value>Distribuidores CRM</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Distribuidores CRM</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marcas Comerciales</relationshipLabel>
        <relationshipName>Organizaciones_Cliente</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Sector_Distribuidor__c</fullName>
        <label>Sector (Distribuidor)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Tipo_Sector</valueSetName>
        </valueSet>
    </fields>
    <label>Organización Cliente</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Nombre de Organización Cliente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizaciones Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Territory2.object
<CustomObject>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <label>Canal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Canal_de_distribucion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizacion_Ventas__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Sector_Distribuidor__c</fullName>
        <label>Sector (Distribuidor)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Tipo_Sector</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/globalValueSets/KS_Area.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1010</fullName>
    </customValue>
    <customValue>
        <fullName>1020</fullName>
    </customValue>
    <customValue>
        <fullName>1021</fullName>
    </customValue>
    <customValue>
        <fullName>1030</fullName>
    </customValue>
    <customValue>
        <fullName>1040</fullName>
    </customValue>
    <customValue>
        <fullName>1050</fullName>
    </customValue>
    <customValue>
        <fullName>1060</fullName>
    </customValue>
    <customValue>
        <fullName>INTE</fullName>
    </customValue>
    <description>SAP. IDs SAP de Área</description>
    <masterLabel>Área</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Canal.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Distribuidores CRM</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Prescriptores</fullName>
    </customValue>
    <customValue>
        <fullName>Clientes finales</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidores SAP</fullName>
    </customValue>
    <customValue>
        <fullName>Varios</fullName>
        <isActive>false</isActive>
        <label>Varios</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en Cuentas</description>
    <masterLabel>Canal</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Canal_de_distribucion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>Nacional</fullName>
        <isActive>false</isActive>
        <label>Nacional</label>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente - Jerarquia Cliente - Producto --&gt; CARGADO</description>
    <masterLabel>Canal de distribución</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Organizacion_de_ventas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>FL31</fullName>
    </customValue>
    <customValue>
        <fullName>GI50</fullName>
    </customValue>
    <customValue>
        <fullName>IE20</fullName>
    </customValue>
    <customValue>
        <fullName>MA15</fullName>
    </customValue>
    <customValue>
        <fullName>MA16</fullName>
    </customValue>
    <customValue>
        <fullName>MX24</fullName>
    </customValue>
    <customValue>
        <fullName>MX25</fullName>
    </customValue>
    <customValue>
        <fullName>MX26</fullName>
    </customValue>
    <customValue>
        <fullName>SI10</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente / Jerarquia Cliente / Producto / Autorizaciones Oferta --&gt; CARGADO</description>
    <masterLabel>Organizacion de ventas</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Tipo_Sector.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <customValue>
        <fullName>40</fullName>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>60</fullName>
    </customValue>
    <customValue>
        <fullName>70</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente - Jerarquia Cliente - Producto --&gt; CARGADO</description>
    <masterLabel>Tipo Sector (SAP)</masterLabel>
</GlobalValueSet>

src/classes/KS_LeadAccountApproval_Controller.cls
global without sharing class KS_LeadAccountApproval_Controller {

    public Account lead {get;set;}

    public Boolean error {get;set;}
    public String errorMSG {get;set;}
    
    public String url {get;set;}
    public Boolean getRedirect() {
        return url != null && url != '';
    }
    
    public Boolean sendToApprove {get;set;}
    
    public KS_LeadAccountApproval_Controller(ApexPages.StandardController controller) {
        
        sendToApprove = false;
        
        lead = (Account)controller.getRecord();
        if (lead!=null && lead.ID!=null) {
            
            Map<String,ID> recordTypes = new Map<String,ID>();
            List<RecordType> rtLst = [SELECT ID,DeveloperName FROM RecordType];
            for (RecordType rt : rtLst) {
                recordTypes.put(rt.DeveloperName, rt.ID);
            }
            
            lead = [SELECT ID, KS_Canal_SAP__c, KS_Sector_SAP__c, KS_Organizaciones_de_cuentas__c, RecordTypeID 
                    FROM Account WHERE ID = :lead.ID];
            if (lead.RecordTypeID != recordTypes.get('KS_Lead')) { // ERROR: Cuenta no tipo lead
                error = true;
                errorMSG = 'ERROR: Account not Lead type';
                url = '';
                return;
            }
            
            if (lead.KS_Organizaciones_de_cuentas__c != null && lead.KS_Organizaciones_de_cuentas__c != '') {
                
                String aprov = ApexPages.currentPage().getParameters().get('send');
                sendToApprove = aprov != null && aprov == 'true';
                //calcularAprobacion();
                //update lead;
            
            } else { // ERROR: No está listo para ser aprobado, redirect a página de cuenta
                error = true;
                errorMSG = 'ERROR: Account not prepared to approve';
            }

        } else { // ERROR: No existe la cuenta, redirect a página de lista de cuentas
            error = true;
            errorMSG = 'ERROR: Account not found';
            url = '';
            return;
        }
        
        error = false;
        //url = '/'+lead.ID;
    }
    
    public void calcularAprobacion() {
		
        Map<String,ID> terrType = new Map<String,ID>();
        List<Territory2Type> terrLst = [SELECT ID, DeveloperName FROM Territory2Type];
        for (Territory2Type tp : terrLst) {
            terrType.put(tp.DeveloperName, tp.ID);
        }
        
        List<String> orgVentas = new List<String>();
        String area = '';
        
        List<KS_Organizacion_Cliente__c> ocLst = [SELECT ID,KS_Area__c,KS_Organizacion_de_Ventas__c
                                                  FROM KS_Organizacion_Cliente__c
                                                  WHERE KS_Cliente_Distribucion__c = :lead.ID];
        for (KS_Organizacion_Cliente__c oc : ocLst) {
            orgVentas.add(oc.KS_Organizacion_de_Ventas__c);
            area = oc.KS_Area__c;
        }
        
        List<UserTerritory2Association> utaLst = 
            [SELECT Id, UserId, Territory2Id, RoleInTerritory2, 
             Territory2.KS_Organizacion_Ventas__c
             FROM UserTerritory2Association 
             WHERE RoleInTerritory2 = 'JAR'
             AND Territory2.KS_Organizacion_Ventas__c IN :orgVentas
             AND Territory2.KS_Canal__c = :lead.KS_Canal_SAP__c
             AND Territory2.KS_Sector_Distribuidor__c = :lead.KS_Sector_SAP__c
             AND Territory2.KS_Area__c = :area
             AND Territory2.Territory2TypeId = :terrType.get('KS_Area')
            ];
        System.debug('----------------------------------------JCAR - ' + utaLst.size() + ' UserTerritory2Association : ' + utaLst);
        for (UserTerritory2Association uta : utaLst) {
            
            String marca = uta.Territory2.KS_Organizacion_Ventas__c;
            ID responsable = uta.UserId;
            if (marca == 'SI10') { lead.KS_Responsable_SI10__c = responsable; }
            if (marca == 'FL31') { lead.KS_Responsable_FL31__c = responsable; }
            if (marca == 'IE20') { lead.KS_Responsable_IE20__c = responsable; }            
        }
        //ID responsable = terrOferta.size()>0 ? terrOferta.get(0).UserId : null;
        
        update lead;
        error = false;
        url = '/'+lead.ID;
        
        if (sendToApprove) {
            Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
            req.setComments('Submitted for approval. Please approve.');
            req.setObjectId(lead.ID);
            Approval.ProcessResult result = Approval.process(req);            
        }
    }
}