src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <label>Canal</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KS_Actividad__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Canal</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_recordType_Name__c</fullName>
        <formula>RecordType.DeveloperName</formula>
        <label>Tipo de registro (Name)</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/KS_Canal.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Distribuidores CRM</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Prescriptores</fullName>
    </customValue>
    <customValue>
        <fullName>Clientes finales</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidores SAP</fullName>
    </customValue>
    <customValue>
        <fullName>Varios</fullName>
        <isActive>false</isActive>
        <label>Varios</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en Cuentas</description>
    <masterLabel>Canal</masterLabel>
</GlobalValueSet>

src/classes/KS_Schedule_AccScoring.cls
global without sharing class KS_Schedule_AccScoring implements Schedulable {
    
    global Integer chunks = 200;
    global KS_Schedule_AccScoring(Integer ch) { chunks = ch != null && ch > 0 ? ch : 200; }
    
    global void execute(SchedulableContext sc) {

        String rt = '(\'Distribuidores CRM\', \'Distribuidores SAP\', \'Clientes finales\', \'Prescriptores\', \'Instalador\')';
        String q = 'SELECT ID, KS_recordType_Name__c, KS_Canal__c FROM Account WHERE KS_Canal__c in '+rt;
        String e = 'Account';
        
        Id batchInstanceId = Database.executeBatch(new KS_Batch_AccScoring(q,e,'',''), chunks);
        System.debug('-------------------------JCAR - BATCH CON ID' + batchInstanceId);
    }
}