src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KS_Tipo__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Tipo</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/KS_Fusion__c.object
<CustomObject>
    <fields>
        <fullName>KS_Acc_Actividad__c</fullName>
        <label>KS_Acc_Actividad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Calle__c</fullName>
        <label>KS_Acc_Calle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Canal__c</fullName>
        <label>KS_Acc_Canal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Ciudad__c</fullName>
        <label>KS_Acc_Ciudad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Codigo_Postal__c</fullName>
        <label>KS_Acc_Codigo_Postal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Correo__c</fullName>
        <label>KS_Acc_Correo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Estado_Provincia__c</fullName>
        <label>KS_Acc_Estado_Provincia</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Pais__c</fullName>
        <label>KS_Acc_Pais</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Sector__c</fullName>
        <label>KS_Acc_Sector</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Subactividad__c</fullName>
        <label>KS_Acc_Subactividad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Telefono_2__c</fullName>
        <label>KS_Acc_Telefono_2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Telefono_3__c</fullName>
        <label>KS_Acc_Telefono_3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Acc_Telefono__c</fullName>
        <label>KS_Acc_Telefono</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Accion__c</fullName>
        <label>KS_Accion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MERGE</fullName>
                </value>
                <value>
                    <fullName>DELETE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Force_Merge__c</fullName>
        <defaultValue>false</defaultValue>
        <label>KS_Force_Merge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Id_Duplicado_2__c</fullName>
        <label>KS_Id_Duplicado_2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Id_Duplicado__c</fullName>
        <label>KS_Id_Duplicado</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Id_Principal__c</fullName>
        <label>KS_Id_Principal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Tipo__c</fullName>
        <label>KS_Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACCOUNT</fullName>
                </value>
                <value>
                    <fullName>CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fusion</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Fusion ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fusiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Tipo.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Punto de venta</fullName>
    </customValue>
    <customValue>
        <fullName>Punto de compra</fullName>
    </customValue>
    <customValue>
        <fullName>Central compras</fullName>
    </customValue>
    <customValue>
        <fullName>Público</fullName>
    </customValue>
    <customValue>
        <fullName>Privado</fullName>
    </customValue>
    <customValue>
        <fullName>Explotación</fullName>
    </customValue>
    <description>SEGMENTACIÓN. Variable usada en segmentación de cuentas.</description>
    <masterLabel>Tipo</masterLabel>
</GlobalValueSet>

src/classes/KS_Batch_MergeTool_MergeAccounts.cls
global class KS_Batch_MergeTool_MergeAccounts implements Database.Batchable<sObject> {
	
	String query = 'SELECT Id, Name, KS_Accion__c, KS_Id_Principal__c, KS_Id_Duplicado__c, KS_Id_Duplicado_2__c, KS_Force_Merge__c,KS_Acc_Calle__c, KS_Acc_Ciudad__c, KS_Acc_Codigo_Postal__c, KS_Acc_Estado_Provincia__c, KS_Acc_Pais__c, KS_Acc_Telefono__c, KS_Acc_Telefono_2__c, KS_Acc_Telefono_3__c, KS_Acc_Correo__c, KS_Acc_Canal__c, KS_Acc_Actividad__c, KS_Acc_Subactividad__c, KS_Acc_Sector__c FROM KS_Fusion__c WHERE KS_Accion__c = \'MERGE\' AND KS_Tipo__c = \'ACCOUNT\'';
	
	global KS_Batch_MergeTool_MergeAccounts() {
		
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) 
	{
        KS_MergeTool_MergeAuto mergeAcc = new KS_MergeTool_MergeAuto();
        System.debug('-- JCAR -- KS_Batch_MergeTool_MergeAccounts ----------------- scope ' 
                     + scope.size() + ' List<sObject> ' + scope);
		mergeAcc.MergeAccounts(scope);
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}