src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <label>Canal</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KS_Actividad__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Canal</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizacion_Ventas__c</fullName>
        <label>Marcas comerciales</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Scoring_Actividad__c</fullName>
        <label>Scoring Actividad Comercial</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Scoring</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Scoring_Negocio__c</fullName>
        <label>Scoring Negocio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Scoring</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Sector__c</fullName>
        <label>Sector</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>KS_Actividad__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Sector</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_recordType_Name__c</fullName>
        <formula>RecordType.DeveloperName</formula>
        <label>Tipo de registro (Name)</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>KS_Distribuidores</fullName>
        <active>true</active>
        <description>Tipo de registro para albergar distribuidores potenciales</description>
        <label>Distribuidores CRM</label>
    </recordTypes>
    <recordTypes>
        <fullName>KS_Distribuidores_SAP</fullName>
        <active>true</active>
        <description>Tipo de registro para albergar clientes distribuidores provenientes de SAP</description>
        <label>Distribuidores SAP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/KS_Condicion_Comercial__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Condiciones comerciales de SAP para el cálculo de precios en ofertas.</description>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <label>Canal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Canal_de_distribucion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Cliente_Jerarquia__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente/Jerarquia</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>KS_Descuentos_Tarifa</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Condicion__c</fullName>
        <label>Condicion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Tipo_Descuento</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Familia__c</fullName>
        <label>Familia</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Familia</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Importe__c</fullName>
        <label>Importe</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>KS_Organizacion_Ventas__c</fullName>
        <label>Organizacion Ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Porcentaje__c</fullName>
        <label>Porcentaje</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>KS_Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Tipo_Sector</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Serie_single__c</fullName>
        <label>Serie</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>001</fullName>
                </value>
                <value>
                    <fullName>002</fullName>
                </value>
                <value>
                    <fullName>003</fullName>
                </value>
                <value>
                    <fullName>004</fullName>
                </value>
                <value>
                    <fullName>005</fullName>
                </value>
                <value>
                    <fullName>006</fullName>
                </value>
                <value>
                    <fullName>007</fullName>
                </value>
                <value>
                    <fullName>008</fullName>
                </value>
                <value>
                    <fullName>009</fullName>
                </value>
                <value>
                    <fullName>010</fullName>
                </value>
                <value>
                    <fullName>011</fullName>
                </value>
                <value>
                    <fullName>012</fullName>
                </value>
                <value>
                    <fullName>013</fullName>
                </value>
                <value>
                    <fullName>014</fullName>
                </value>
                <value>
                    <fullName>015</fullName>
                </value>
                <value>
                    <fullName>016</fullName>
                </value>
                <value>
                    <fullName>017</fullName>
                </value>
                <value>
                    <fullName>018</fullName>
                </value>
                <value>
                    <fullName>019</fullName>
                </value>
                <value>
                    <fullName>020</fullName>
                </value>
                <value>
                    <fullName>021</fullName>
                </value>
                <value>
                    <fullName>022</fullName>
                </value>
                <value>
                    <fullName>023</fullName>
                </value>
                <value>
                    <fullName>024</fullName>
                </value>
                <value>
                    <fullName>025</fullName>
                </value>
                <value>
                    <fullName>026</fullName>
                </value>
                <value>
                    <fullName>027</fullName>
                </value>
                <value>
                    <fullName>028</fullName>
                </value>
                <value>
                    <fullName>029</fullName>
                </value>
                <value>
                    <fullName>030</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Subserie__c</fullName>
        <label>Subserie</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Subserie</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Tarifa__c</fullName>
        <label>Tarifa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Tarifa</valueSetName>
        </valueSet>
    </fields>
    <label>Condicion Comercial</label>
    <nameField>
        <displayFormat>CC{000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones Comerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Organizacion_Cliente__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto vinculado con las cuentas (marcas) que muestra las organizaciones de ventas para cada cliente</description>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Canal_de_distribucion__c</fullName>
        <label>Canal de distribución</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Canal_de_distribucion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Cliente_Dest_Mercancias__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente Dest. Mercancias</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Clientes Dest. Mercancias</relationshipLabel>
        <relationshipName>Clientes_Dest_Mercancias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Cliente_Distribucion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente Distribución</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3) OR 4</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Distribuidores_SAP</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Lead</value>
            </filterItems>
            <filterItems>
                <field>Account.KS_Canal__c</field>
                <operation>equals</operation>
                <value>Distribuidores CRM</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Distribuidores CRM</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marcas Comerciales</relationshipLabel>
        <relationshipName>Organizaciones_Cliente</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Cliente_solicitante__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente solicitante</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marcas Comerciales</relationshipLabel>
        <relationshipName>Clientes_solicitantes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Coordinador__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gestor de cuenta</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Organizaciones_Cliente</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Delegacion__c</fullName>
        <label>Delegación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Delegacion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Estado_Avisos_autom_ticos__c</fullName>
        <formula>IF (  KS_AprobacionRegimenVisitas__c  = TRUE, IMAGE(&quot;/resource/1472593079000/bell_png&quot;, &quot;y&quot;,16,16),

IF (  KS_AprobacionPendiente__c  = TRUE, IMAGE(&quot;/resource/1485575951000/persona_png&quot;, &quot;y&quot;,16,16),
IMAGE(&quot;/resource/1472593163000/calendar_png&quot;, &quot;n&quot;,16,16))

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Estado Avisos-automáticos</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Lista_de_precios__c</fullName>
        <label>Lista de precios</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Lista_de_precios</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Recurrencia__c</fullName>
        <inlineHelpText>Una vez establecida la recurrencia solicite aprobación del registro para que el responsable autorice el régimen de visitas y se generen los avisos automáticos.</inlineHelpText>
        <label>Recurrencia (días)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
                <value>
                    <fullName>365</fullName>
                </value>
                <value>
                    <fullName>---</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Scoring_Actividad__c</fullName>
        <label>Scoring Actividad</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Scoring</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Scoring_IF__c</fullName>
        <label>Scoring IF</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Scoring_AC</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Scoring_Negocio__c</fullName>
        <label>Scoring Negocio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Scoring</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Sector_Distribuidor__c</fullName>
        <label>Sector (Distribuidor)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Tipo_Sector</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Zona__c</fullName>
        <label>Zona</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Zona_Geog</valueSetName>
        </valueSet>
    </fields>
    <label>Organización Cliente</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Nombre de Organización Cliente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizaciones Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/KS_Area.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1010</fullName>
    </customValue>
    <customValue>
        <fullName>1020</fullName>
    </customValue>
    <customValue>
        <fullName>1021</fullName>
    </customValue>
    <customValue>
        <fullName>1030</fullName>
    </customValue>
    <customValue>
        <fullName>1040</fullName>
    </customValue>
    <customValue>
        <fullName>1050</fullName>
    </customValue>
    <customValue>
        <fullName>1060</fullName>
    </customValue>
    <customValue>
        <fullName>INTE</fullName>
    </customValue>
    <description>SAP. IDs SAP de Área</description>
    <masterLabel>Área</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Canal.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Distribuidores CRM</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Prescriptores</fullName>
    </customValue>
    <customValue>
        <fullName>Clientes finales</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidores SAP</fullName>
    </customValue>
    <customValue>
        <fullName>Varios</fullName>
        <isActive>false</isActive>
        <label>Varios</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en Cuentas</description>
    <masterLabel>Canal</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Canal_de_distribucion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>Nacional</fullName>
        <isActive>false</isActive>
        <label>Nacional</label>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente - Jerarquia Cliente - Producto --&gt; CARGADO</description>
    <masterLabel>Canal de distribución</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Delegacion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>009</fullName>
    </customValue>
    <customValue>
        <fullName>010</fullName>
    </customValue>
    <customValue>
        <fullName>011</fullName>
    </customValue>
    <customValue>
        <fullName>012</fullName>
    </customValue>
    <customValue>
        <fullName>013</fullName>
    </customValue>
    <customValue>
        <fullName>015</fullName>
    </customValue>
    <customValue>
        <fullName>017</fullName>
    </customValue>
    <customValue>
        <fullName>018</fullName>
    </customValue>
    <customValue>
        <fullName>019</fullName>
    </customValue>
    <customValue>
        <fullName>020</fullName>
    </customValue>
    <customValue>
        <fullName>021</fullName>
    </customValue>
    <customValue>
        <fullName>023</fullName>
    </customValue>
    <customValue>
        <fullName>024</fullName>
    </customValue>
    <customValue>
        <fullName>025</fullName>
    </customValue>
    <customValue>
        <fullName>026</fullName>
    </customValue>
    <customValue>
        <fullName>027</fullName>
    </customValue>
    <customValue>
        <fullName>028</fullName>
    </customValue>
    <customValue>
        <fullName>029</fullName>
    </customValue>
    <customValue>
        <fullName>030</fullName>
    </customValue>
    <customValue>
        <fullName>031</fullName>
    </customValue>
    <customValue>
        <fullName>032</fullName>
    </customValue>
    <customValue>
        <fullName>033</fullName>
    </customValue>
    <customValue>
        <fullName>034</fullName>
    </customValue>
    <customValue>
        <fullName>035</fullName>
    </customValue>
    <customValue>
        <fullName>036</fullName>
    </customValue>
    <description>SAP. IDs SAP de Delegación</description>
    <masterLabel>Delegación</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Familia.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>B00</fullName>
    </customValue>
    <customValue>
        <fullName>B01</fullName>
    </customValue>
    <customValue>
        <fullName>B02</fullName>
    </customValue>
    <customValue>
        <fullName>B03</fullName>
    </customValue>
    <customValue>
        <fullName>B04</fullName>
    </customValue>
    <customValue>
        <fullName>B05</fullName>
    </customValue>
    <customValue>
        <fullName>B06</fullName>
    </customValue>
    <customValue>
        <fullName>C00</fullName>
    </customValue>
    <customValue>
        <fullName>C01</fullName>
    </customValue>
    <customValue>
        <fullName>C02</fullName>
    </customValue>
    <customValue>
        <fullName>C03</fullName>
    </customValue>
    <customValue>
        <fullName>C04</fullName>
    </customValue>
    <customValue>
        <fullName>C05</fullName>
    </customValue>
    <customValue>
        <fullName>C06</fullName>
    </customValue>
    <customValue>
        <fullName>C07</fullName>
    </customValue>
    <customValue>
        <fullName>C08</fullName>
    </customValue>
    <customValue>
        <fullName>C09</fullName>
    </customValue>
    <customValue>
        <fullName>C10</fullName>
    </customValue>
    <customValue>
        <fullName>C11</fullName>
    </customValue>
    <customValue>
        <fullName>C12</fullName>
    </customValue>
    <customValue>
        <fullName>C13</fullName>
    </customValue>
    <customValue>
        <fullName>C14</fullName>
    </customValue>
    <customValue>
        <fullName>C15</fullName>
    </customValue>
    <customValue>
        <fullName>C16</fullName>
    </customValue>
    <customValue>
        <fullName>C17</fullName>
    </customValue>
    <customValue>
        <fullName>C18</fullName>
    </customValue>
    <customValue>
        <fullName>C19</fullName>
    </customValue>
    <customValue>
        <fullName>C20</fullName>
    </customValue>
    <customValue>
        <fullName>C21</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Producto / Autorizaciones Oferta --&gt; CARGADO</description>
    <masterLabel>Familia</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/KS_Lista_de_precios.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>00</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>EC</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>PU</fullName>
    </customValue>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <customValue>
        <fullName>E0</fullName>
    </customValue>
    <customValue>
        <fullName>T0</fullName>
    </customValue>
    <customValue>
        <fullName>T1</fullName>
    </customValue>
    <customValue>
        <fullName>T2</fullName>
    </customValue>
    <customValue>
        <fullName>T3</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
    </customValue>
    <customValue>
        <fullName>B2</fullName>
    </customValue>
    <customValue>
        <fullName>B3</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente --&gt; CARGADO</description>
    <masterLabel>Lista de precios</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Organizacion_de_ventas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>FL31</fullName>
    </customValue>
    <customValue>
        <fullName>GI50</fullName>
    </customValue>
    <customValue>
        <fullName>IE20</fullName>
    </customValue>
    <customValue>
        <fullName>MA15</fullName>
    </customValue>
    <customValue>
        <fullName>MA16</fullName>
    </customValue>
    <customValue>
        <fullName>MX24</fullName>
    </customValue>
    <customValue>
        <fullName>MX25</fullName>
    </customValue>
    <customValue>
        <fullName>MX26</fullName>
    </customValue>
    <customValue>
        <fullName>SI10</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente / Jerarquia Cliente / Producto / Autorizaciones Oferta --&gt; CARGADO</description>
    <masterLabel>Organizacion de ventas</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Scoring.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>*</fullName>
    </customValue>
    <customValue>
        <fullName>**</fullName>
    </customValue>
    <customValue>
        <fullName>***</fullName>
    </customValue>
    <customValue>
        <fullName>****</fullName>
    </customValue>
    <customValue>
        <fullName>*****</fullName>
    </customValue>
    <customValue>
        <fullName>BC</fullName>
        <isActive>false</isActive>
        <label>BC</label>
    </customValue>
    <customValue>
        <fullName>CB</fullName>
        <isActive>false</isActive>
        <label>CB</label>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
        <isActive>false</isActive>
        <label>CC</label>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
        <isActive>false</isActive>
        <label>BB</label>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
        <isActive>false</isActive>
        <label>BA</label>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
        <isActive>false</isActive>
        <label>AC</label>
    </customValue>
    <customValue>
        <fullName>AB</fullName>
        <isActive>false</isActive>
        <label>AB</label>
    </customValue>
    <customValue>
        <fullName>AA</fullName>
        <isActive>false</isActive>
        <label>AA</label>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <isActive>false</isActive>
        <label>CA</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado en objeto Leads y cuentas</description>
    <masterLabel>Scoring</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Sector.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Residencial</fullName>
    </customValue>
    <customValue>
        <fullName>Terciario</fullName>
    </customValue>
    <customValue>
        <fullName>Hotelero</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Otros</fullName>
    </customValue>
    <customValue>
        <fullName>Edificios administrativos</fullName>
        <isActive>false</isActive>
        <label>Edificios administrativos</label>
    </customValue>
    <customValue>
        <fullName>Industrial (Naves, Fábricas, etc...)</fullName>
        <isActive>false</isActive>
        <label>Industrial (Naves, Fábricas, etc...)</label>
    </customValue>
    <customValue>
        <fullName>Educación</fullName>
        <isActive>false</isActive>
        <label>Educación</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en cuentas</description>
    <masterLabel>Sector</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Subserie.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>003</fullName>
    </customValue>
    <customValue>
        <fullName>004</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>009</fullName>
    </customValue>
    <customValue>
        <fullName>010</fullName>
    </customValue>
    <customValue>
        <fullName>011</fullName>
    </customValue>
    <customValue>
        <fullName>012</fullName>
    </customValue>
    <customValue>
        <fullName>013</fullName>
    </customValue>
    <customValue>
        <fullName>014</fullName>
    </customValue>
    <customValue>
        <fullName>015</fullName>
    </customValue>
    <customValue>
        <fullName>016</fullName>
    </customValue>
    <customValue>
        <fullName>017</fullName>
    </customValue>
    <customValue>
        <fullName>018</fullName>
    </customValue>
    <customValue>
        <fullName>019</fullName>
    </customValue>
    <customValue>
        <fullName>020</fullName>
    </customValue>
    <customValue>
        <fullName>021</fullName>
    </customValue>
    <customValue>
        <fullName>022</fullName>
    </customValue>
    <customValue>
        <fullName>023</fullName>
    </customValue>
    <customValue>
        <fullName>024</fullName>
    </customValue>
    <customValue>
        <fullName>025</fullName>
    </customValue>
    <customValue>
        <fullName>026</fullName>
    </customValue>
    <customValue>
        <fullName>027</fullName>
    </customValue>
    <customValue>
        <fullName>028</fullName>
    </customValue>
    <customValue>
        <fullName>029</fullName>
    </customValue>
    <customValue>
        <fullName>030</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Producto/Autorizaciones Oferta --&gt; CARGADO</description>
    <masterLabel>Subserie</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/KS_Tarifa.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>00</fullName>
    </customValue>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>EC</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>PU</fullName>
    </customValue>
    <customValue>
        <fullName>E0</fullName>
    </customValue>
    <customValue>
        <fullName>T0</fullName>
    </customValue>
    <customValue>
        <fullName>T1</fullName>
    </customValue>
    <customValue>
        <fullName>T2</fullName>
    </customValue>
    <customValue>
        <fullName>T3</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
    </customValue>
    <customValue>
        <fullName>B2</fullName>
    </customValue>
    <customValue>
        <fullName>B3</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Variable que identifica tarifa seleccionada --&gt; CARGADO</description>
    <masterLabel>Tarifa</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Tipo_Descuento.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PR00</fullName>
    </customValue>
    <customValue>
        <fullName>ZDB1</fullName>
    </customValue>
    <customValue>
        <fullName>ZDB2</fullName>
    </customValue>
    <customValue>
        <fullName>ZDVR</fullName>
    </customValue>
    <customValue>
        <fullName>ZDVA</fullName>
    </customValue>
    <customValue>
        <fullName>ZPN0</fullName>
    </customValue>
    <customValue>
        <fullName>ZDA8</fullName>
    </customValue>
    <customValue>
        <fullName>ZDA9</fullName>
    </customValue>
    <customValue>
        <fullName>ZDB5</fullName>
    </customValue>
    <customValue>
        <fullName>ZDA7</fullName>
    </customValue>
    <customValue>
        <fullName>ZDB6</fullName>
    </customValue>
    <customValue>
        <fullName>ZDA6</fullName>
    </customValue>
    <customValue>
        <fullName>ZDB8</fullName>
    </customValue>
    <customValue>
        <fullName>CondicionTEST</fullName>
        <isActive>false</isActive>
        <label>CondicionTEST</label>
    </customValue>
    <description>SAP. Uso --&gt; Tipologias de descuento en tarifas --&gt; CARGADO</description>
    <masterLabel>Tipo Descuento</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Tipo_Sector.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <customValue>
        <fullName>40</fullName>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>60</fullName>
    </customValue>
    <customValue>
        <fullName>70</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente - Jerarquia Cliente - Producto --&gt; CARGADO</description>
    <masterLabel>Tipo Sector (SAP)</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Zona_Geog.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>23</fullName>
    </customValue>
    <customValue>
        <fullName>24</fullName>
    </customValue>
    <customValue>
        <fullName>25</fullName>
    </customValue>
    <customValue>
        <fullName>26</fullName>
    </customValue>
    <customValue>
        <fullName>27</fullName>
    </customValue>
    <customValue>
        <fullName>28</fullName>
    </customValue>
    <customValue>
        <fullName>29</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <description>SAP. En Uso en Oportunidaes/Obras</description>
    <masterLabel>Zona Geog.</masterLabel>
</GlobalValueSet>

src/globalValueSets/Scoring_AC.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AA</fullName>
    </customValue>
    <customValue>
        <fullName>AB</fullName>
    </customValue>
    <customValue>
        <fullName>AC</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BC</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CB</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
    </customValue>
    <customValue>
        <fullName>CD</fullName>
        <isActive>false</isActive>
        <label>CD</label>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
        <isActive>false</isActive>
        <label>BD</label>
    </customValue>
    <customValue>
        <fullName>AD</fullName>
        <isActive>false</isActive>
        <label>AD</label>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
        <isActive>false</isActive>
        <label>DC</label>
    </customValue>
    <customValue>
        <fullName>DB</fullName>
        <isActive>false</isActive>
        <label>DB</label>
    </customValue>
    <customValue>
        <fullName>DD</fullName>
        <isActive>false</isActive>
        <label>DD</label>
    </customValue>
    <customValue>
        <fullName>DA</fullName>
        <isActive>false</isActive>
        <label>DA</label>
    </customValue>
    <description>EN USO --&gt; Cuentas tipo Lead</description>
    <masterLabel>Scoring-AC</masterLabel>
</GlobalValueSet>

src/classes/KS_MarcasCliente_Controller.cls
public without sharing class KS_MarcasCliente_Controller {

    public Account cuenta {get;set;}
    
    public List<KS_Organizacion_Cliente__c> marcas {get;set;}
    public Boolean getHaveMarcas() {
        return marcas != null && !marcas.isEmpty();
    }   
    
    public List<CondicionComercial> condiciones {get;set;}
    public Boolean getHaveCondiciones() {
        return condiciones != null && !condiciones.isEmpty();
    }
    
    public Boolean getIsAdmin() {
        String profName = [Select Name from Profile where Id = :UserInfo.getProfileId()].Name;
        return profName.contains('Admin');
    }
    
    public KS_MarcasCliente_Controller(ApexPages.StandardController controller) {
        
        cuenta = (Account)controller.getRecord();
        if (cuenta.ID != null) {
            
            cuenta = [SELECT ID, KS_recordType_Name__c FROM Account WHERE ID = :cuenta.ID];
            
            // JCAR 170124 - Se crean dos lógicas paralelas, una para Distribuidores (SAP/CRM) y otra para el resto //
            
            if (cuenta.KS_recordType_Name__c == 'KS_Distribuidores_SAP' || cuenta.KS_recordType_Name__c == 'KS_Distribuidores') {
                
                marcas = [SELECT ID, Name, KS_Organizacion_de_ventas__c, KS_Lista_de_precios__c,
                          KS_Canal_de_distribucion__c, KS_Sector_Distribuidor__c,
                          KS_Area__c, KS_Delegacion__c, KS_Zona__c,
                          KS_Scoring_IF__c, KS_Scoring_Negocio__c, KS_Scoring_Actividad__c, KS_Coordinador__c, KS_Recurrencia__c, KS_Estado_Avisos_autom_ticos__c
                          FROM KS_Organizacion_Cliente__c
                          WHERE KS_Cliente_Distribucion__c = :cuenta.ID
                          AND KS_Cliente_Dest_Mercancias__c = :cuenta.ID
                          AND KS_Cliente_solicitante__c = :cuenta.ID];
            } else {
                
                marcas = [SELECT ID, Name, KS_Organizacion_de_ventas__c, KS_Lista_de_precios__c,
                          KS_Canal_de_distribucion__c, KS_Sector_Distribuidor__c,
                          KS_Area__c, KS_Delegacion__c, KS_Zona__c,
                          KS_Scoring_IF__c, KS_Scoring_Negocio__c, KS_Scoring_Actividad__c, KS_Coordinador__c, KS_Recurrencia__c, KS_Estado_Avisos_autom_ticos__c
                          FROM KS_Organizacion_Cliente__c
                          WHERE KS_Cliente_solicitante__c = :cuenta.ID];
            }

            System.debug('-- JCAR ---------------------------------- - KS_MarcasCliente_Controller.marcas? ' + marcas.size() + ' - ' + marcas);
            
            condiciones = new List<CondicionComercial>();
            List<KS_Condicion_Comercial__c> ccLst =  [SELECT ID, KS_Condicion__c, KS_Organizacion_Ventas__c, KS_Canal__c, KS_Sector__c, 
                                                      KS_Familia__c, KS_Serie_single__c, KS_Subserie__c, KS_Tarifa__c, KS_Importe__c, KS_Porcentaje__c 
                                                      FROM KS_Condicion_Comercial__c WHERE KS_Cliente_Jerarquia__c = :cuenta.ID];
            for (KS_Condicion_Comercial__c cc : ccLst) {
                
                CondicionComercial ccN = new CondicionComercial(cc);
                condiciones.add(ccN);
            }
            
            System.debug('-- JCAR ---------------------------------- - KS_MarcasCliente_Controller.condiciones? ' + condiciones.size() + ' - ' + condiciones);
        }        
    }
    
    public class CondicionComercial {
        
        public String condicion {get;set;}
        public String orgVentas {get;set;}
        public String canal {get;set;}
        public String sector {get;set;}
        public String tarifa {get;set;}
        public String familia {get;set;}
        public String serie {get;set;}
        public String subserie {get;set;}
        public Decimal importe {get;set;}
        public Decimal porcentaje {get;set;}
        
        public CondicionComercial(KS_Condicion_Comercial__c cc) {
             
            condicion = cc.KS_Condicion__c;
            orgVentas = cc.KS_Organizacion_Ventas__c;
            canal = cc.KS_Canal__c;
            sector = cc.KS_Sector__c;
            tarifa = cc.KS_Tarifa__c;
            familia = cc.KS_Familia__c;
            serie = cc.KS_Serie_single__c;
            subserie = cc.KS_Subserie__c;
            importe = cc.KS_Importe__c;
            porcentaje = cc.KS_Porcentaje__c;
        }
    }
    
}