src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KS_Aprobado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Aprobado</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/KS_Obra__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Es el objeto superior que agrega las ofertas (oportunidades)</description>
    <label>Obra</label>
    <nameField>
        <label>Nombre de Obra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Obras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>KS_Agente_de_contabilizacion__c</fullName>
        <label>Agente de contabilización</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KS_Contabiliza__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Contabilizacion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Aprobado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Aprobado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Cliente_final__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente final / Prescriptor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Clientes finales, Prescriptores</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Lead</value>
            </filterItems>
            <filterItems>
                <field>Account.KS_Canal__c</field>
                <operation>notEqual</operation>
                <value>Distribuidores CRM, Instalador, Asociaciones</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ofertas (Cliente final)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Contabiliza__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contabiliza</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Creador_Name__c</fullName>
        <formula>CreatedBy.FirstName + &apos; &apos; + CreatedBy.LastName</formula>
        <label>Creador Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Distribuidor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribuidor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Distribuidores</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Distribuidores_SAP</value>
            </filterItems>
            <filterItems>
                <field>Account.KS_Grupo_de_ctas_deudor__c</field>
                <operation>notEqual</operation>
                <value>Destinatarios mercancías</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ofertas (Distribuidor)</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Estado_de_aprobacion__c</fullName>
        <formula>IF( KS_Aprobado__c = TRUE, IMAGE(&quot;/resource/1470384173000/flag_green_png&quot;,&quot;OK&quot;,16,16), IMAGE(&quot;/resource/1470384189000/flag_red_png&quot;,&quot;KO&quot;,16,16) )</formula>
        <label>Estado de aprobación</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Importe_total_fichas__c</fullName>
        <label>Importe neto fichas</label>
        <summarizedField>OpportunityLineItem.KS_Neto_por_ficha__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>KS_Instalador__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instalador</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 4 OR (2 AND 3)</booleanFilter>
            <errorMessage>La cuenta indicada como Instalador no tiene dicha tipología. Tan sólo pueden aceptarse Lead de tipo Instalador o Cuentas de tipo Instalador.</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Instalador, Clientes finales, Prescriptores</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Lead</value>
            </filterItems>
            <filterItems>
                <field>Account.KS_Canal__c</field>
                <operation>equals</operation>
                <value>Instalador</value>
            </filterItems>
            <filterItems>
                <field>Account.Id</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ofertas (Instalador)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Nivel_de_aprobacion_de_4__c</fullName>
        <formula>1+
IF(KS_Nivel2__c = TRUE, 1, 0)
+
IF(KS_Nivel3__c = TRUE, 1, 0)
+
IF(KS_Nivel4__c = TRUE, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nivel de aprobación (de 4)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KS_Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>KS_Obra__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Oportunidades</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KS_Obra__c</referenceTo>
        <relationshipLabel>Ofertas</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Oferta_ID__c</fullName>
        <displayFormat>OF-{00000}</displayFormat>
        <externalId>true</externalId>
        <label>Oferta ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>KS_Protected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Protegido</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Subetapa__c</fullName>
        <label>Subetapa</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Subetapa</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/KS_Contabilizacion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Distribuidor</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente final</fullName>
    </customValue>
    <description>En uso --&gt; Oferta, para indicar el agente donde contabiliza</description>
    <masterLabel>Contabilizacion</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Subetapa.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>S1</fullName>
    </customValue>
    <customValue>
        <fullName>S2</fullName>
    </customValue>
    <customValue>
        <fullName>S3</fullName>
    </customValue>
    <customValue>
        <fullName>Planificación Proyecto</fullName>
    </customValue>
    <customValue>
        <fullName>Desarrollo</fullName>
    </customValue>
    <customValue>
        <fullName>Entrega</fullName>
    </customValue>
    <description>Uso --&gt; Usado en el objeto Oportunidad</description>
    <masterLabel>Subetapa</masterLabel>
</GlobalValueSet>

src/classes/KS_OfertasObra_Controller.cls
public without sharing class KS_OfertasObra_Controller {

    public KS_Obra__c obra {get;set;}
    public List<Oferta> ofertas {get;set;}
    private List<Opportunity> oppLst {get;set;}
    public Boolean getHaveOfertas() {
        return ofertas != null && !ofertas.isEmpty();
    }
    public String getOfertaKeyPrefix() {
        Schema.DescribeSObjectResult R = Opportunity.SObjectType.getDescribe();
        return R.getKeyPrefix();
    }
    public String newOfertaURL {get;set;}
    
    public KS_OfertasObra_Controller(ApexPages.StandardController controller) {
        
        obra = (KS_Obra__c)controller.getRecord();
        if (obra.ID != null) {
            obra = [SELECT ID, Name, CurrencyISOCode FROM KS_Obra__c WHERE ID = :obra.ID];
            // Nombre oferta, nombre cuenta, fecha cierre, contab, etapa, subetapa, importe, aprobación, nivel aprob
            oppLst = [SELECT ID, KS_Oferta_ID__c, Name, CloseDate, KS_Contabiliza__c, StageName, KS_Subetapa__c, KS_Aprobado__c, KS_Protected__c, 
                      KS_Importe_total_fichas__c, KS_Estado_de_aprobacion__c, KS_Nivel_de_aprobacion_de_4__c, KS_Creador_Name__c,
                      KS_Distribuidor__c, KS_Distribuidor__r.Name, KS_Instalador__c, KS_Instalador__r.Name, KS_Cliente_final__c, KS_Cliente_final__r.Name, 
                      KS_Agente_de_contabilizacion__c
                      FROM Opportunity WHERE KS_Obra__c = :obra.ID];
            
            System.debug('-- JCAR ---------------------------------- - KS_OfertasObra_Controller.ofertas? ' + oppLst.size() + ' - ' + oppLst);
            
            ofertas = new List<Oferta>();
            for (Opportunity opp : oppLst) {
                Oferta ofer = new Oferta(opp, obra);
                ofertas.add(ofer);
            }
            
            System.debug('-- JCAR ---------------------------------- - KS_OfertasObra_Controller.ofertas? ' + ofertas.size() + ' - ' + ofertas);
            
            newOfertaURL = '/setup/ui/recordtypeselect.jsp?ent=Opportunity&retURL=%2F' + obra.ID;
            newOfertaURL += '&save_new_url=%2F' + getOfertaKeyPrefix();
            newOfertaURL += '%2Fe%3FCF00N58000009JIpt%3D' + String.escapeSingleQuotes(obra.Name);
			newOfertaURL += '%26CF00N58000009JIpt_lkid%3D' + obra.ID;
            newOfertaURL += '%26retURL%3D%252F' + obra.ID;
        }
    }
    
    public Class Oferta {
        
        public String idopp {get;set;}
        public String cod {get;set;}
        public String name {get;set;}
        public String fecha {get;set;}
        public Boolean protegido {get;set;}
        public Boolean contabiliza {get;set;}
        public String contabilizador {get;set;}
        public String contabilizadorName {get;set;}
        public String contabilizadorID {get;set;}        
        public String etapa {get;set;}
        public String subetapa {get;set;}
        public String importe {get;set;}
        public Boolean aprobacion {get;set;}
        public String aprobacionNivel {get;set;}
        public String creator {get;set;}

        public Oferta(Opportunity opp, KS_Obra__c obra) {
            
            idopp = opp.ID;
            cod = opp.KS_Oferta_ID__c;
            name = opp.Name;
            fecha = opp.CloseDate.format();
            protegido = opp.KS_Protected__c;
            contabiliza = opp.KS_Contabiliza__c;
            etapa = opp.StageName;
            subetapa = opp.KS_Subetapa__c;
            importe = obra.CurrencyISOCode + ' ' + opp.KS_Importe_total_fichas__c.format();
            aprobacion = opp.KS_Aprobado__c;
            aprobacionNivel = opp.KS_Nivel_de_aprobacion_de_4__c.format().split(',')[0];
            creator = opp.KS_Creador_Name__c;
            contabilizador = opp.KS_Agente_de_contabilizacion__c;        
            
            if (contabilizador == 'Distribuidor' && opp.KS_Distribuidor__c != null) {
                contabilizadorID = opp.KS_Distribuidor__c;
                contabilizadorName = opp.KS_Distribuidor__r.Name;
                
            } else if (contabilizador == 'Instalador' && opp.KS_Instalador__c != null) {
                contabilizadorID = opp.KS_Instalador__c;
                contabilizadorName = opp.KS_Instalador__r.Name;
                
            } else if (contabilizador == 'Cliente final' && opp.KS_Cliente_final__c != null) {
                contabilizadorID = opp.KS_Cliente_final__c;
                contabilizadorName = opp.KS_Cliente_final__r.Name;
            }
        }
    }
    
    public /*PageReference*/void gotoNewOferta() {
        return;//  null;
        PageReference pr = new PageReference('/' + getOfertaKeyPrefix() + '/e');
        pr.getParameters().put('Id','theId');
        pr.setRedirect(true);
        //return pr;
    }
}