src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KS_BillingCity_Diff__c</fullName>
        <label>Billing City Difference</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>KS_BillingCity__c</fullName>
        <label>Custom Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_BillingPostalCode_Diff__c</fullName>
        <label>Billing Postal Code Difference</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>KS_BillingPostalCode__c</fullName>
        <label>Custom Billing Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_BillingStreet_Diff__c</fullName>
        <label>Billing Street Difference</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>KS_BillingStreet__c</fullName>
        <label>Custom Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_C_digo_Postal__c</fullName>
        <label>Código Postal</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Calle__c</fullName>
        <label>Calle</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ciudad__c</fullName>
        <label>Ciudad</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_N_de_telefono_2__c</fullName>
        <label>Nº de telefono 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>KS_N_de_telefono_3__c</fullName>
        <label>Nº de telefono 3</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>KS_N_m_portal_piso_puerta_y_resto_de_di__c</fullName>
        <label>Núm, portal, piso, puerta y resto domici</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_ShippingCity_Diff__c</fullName>
        <label>Shipping City Difference</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>KS_ShippingCity__c</fullName>
        <label>Custom Shipping City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_ShippingPostalCode_Diff__c</fullName>
        <label>Shipping Postal Code Difference</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>KS_ShippingPostalCode__c</fullName>
        <label>Custom Shipping Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_ShippingStreet_Diff__c</fullName>
        <label>Shipping Street Difference</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>KS_ShippingStreet__c</fullName>
        <label>Custom Shipping Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Tipo_de_via__c</fullName>
        <label>Tipo de via</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Tipo_de_via</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>KS_Calle__c</fullName>
        <formula>Account.BillingStreet</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Calle</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ciudad__c</fullName>
        <formula>Account.BillingCity</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ciudad</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Tipo_de_via.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CALLE</fullName>
    </customValue>
    <customValue>
        <fullName>CARRER</fullName>
    </customValue>
    <customValue>
        <fullName>KALEA</fullName>
    </customValue>
    <customValue>
        <fullName>AVENIDA</fullName>
    </customValue>
    <customValue>
        <fullName>AVINGUDA</fullName>
    </customValue>
    <customValue>
        <fullName>ETORBIDEA</fullName>
    </customValue>
    <customValue>
        <fullName>ALAMEDA</fullName>
    </customValue>
    <customValue>
        <fullName>ALBEREDA</fullName>
    </customValue>
    <customValue>
        <fullName>ALDEA</fullName>
    </customValue>
    <customValue>
        <fullName>AUTOPISTA</fullName>
    </customValue>
    <customValue>
        <fullName>AUTOVIA</fullName>
    </customValue>
    <customValue>
        <fullName>AUTOVÍA</fullName>
    </customValue>
    <customValue>
        <fullName>AUZUNEA</fullName>
    </customValue>
    <customValue>
        <fullName>BARRI</fullName>
    </customValue>
    <customValue>
        <fullName>BARRIADA</fullName>
    </customValue>
    <customValue>
        <fullName>BARRIO</fullName>
    </customValue>
    <customValue>
        <fullName>BIDEA</fullName>
    </customValue>
    <customValue>
        <fullName>BULEVAR</fullName>
    </customValue>
    <customValue>
        <fullName>CALLEJÓN</fullName>
    </customValue>
    <customValue>
        <fullName>CALZADA</fullName>
    </customValue>
    <customValue>
        <fullName>CAMÍ</fullName>
    </customValue>
    <customValue>
        <fullName>CAMINO</fullName>
    </customValue>
    <customValue>
        <fullName>CAMIÑO</fullName>
    </customValue>
    <customValue>
        <fullName>CARRERA</fullName>
    </customValue>
    <customValue>
        <fullName>CARRETERA</fullName>
    </customValue>
    <customValue>
        <fullName>CONCELLO</fullName>
    </customValue>
    <customValue>
        <fullName>CUESTA</fullName>
    </customValue>
    <customValue>
        <fullName>ENPARANTZA</fullName>
    </customValue>
    <customValue>
        <fullName>ENTITATEA</fullName>
    </customValue>
    <customValue>
        <fullName>ERREPIDEA</fullName>
    </customValue>
    <masterLabel>Tipo de via</masterLabel>
</GlobalValueSet>

src/classes/KS_Batch_Normalizacion.cls
global class KS_Batch_Normalizacion implements Database.Batchable<sObject> {
    
    public String query {get;set;}
    public String sObjectType {get;set;}
        
	global KS_Batch_Normalizacion(String q, String t) {
		query = q;
        sObjectType = t;
	}
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope) 
    {
        System.debug('-- JCAR -- KS_Batch_Normalizacion ----------------- scope ' 
                     + scope.size() + ' List<sObject> ' + scope);
        KS_Normalizacion_Utils.executeNormalizacion(sObjectType, scope);
    }

    global void finish(Database.BatchableContext BC) {}

    global static String getQueryAccount() {
        return ('SELECT ID, Name, Phone, KS_N_de_telefono_2__c, KS_N_de_telefono_3__c'
                + ', BillingCity, BillingPostalCode, BillingStreet'
                + ', KS_BillingCity__c, KS_BillingPostalCode__c, KS_BillingStreet__c'
                + ', KS_BillingCity_Diff__c, KS_BillingPostalCode_Diff__c, KS_BillingStreet_Diff__c'
                + ', ShippingCity, ShippingPostalCode, ShippingStreet'
                + ', KS_ShippingCity__c, KS_ShippingPostalCode__c, KS_ShippingStreet__c'
                + ', KS_ShippingCity_Diff__c, KS_ShippingPostalCode_Diff__c, KS_ShippingStreet_Diff__c'
                + ', KS_Tipo_de_via__c, KS_Calle__c, KS_N_m_portal_piso_puerta_y_resto_de_di__c, KS_Ciudad__c, KS_C_digo_Postal__c'
                + ' FROM Account');
    }
    global static String getQueryContact() {
        return ('SELECT ID, FirstName, LastName, Phone, MobilePhone, HomePhone '
                + ' FROM Contact');
    }
}