src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <label>Canal</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KS_Actividad__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Canal</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_CountOC_FL31__c</fullName>
        <label>CountOC-FL31</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KS_CountOC_SI10__c</fullName>
        <label>CountOC-SI10</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KS_CountOC__c</fullName>
        <label>CountOC</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KS_Id_SAP__c</fullName>
        <externalId>true</externalId>
        <label>Id SAP</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>KS_Organizacion_Ventas__c</fullName>
        <label>Marcas comerciales</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizaciones_de_cuentas__c</fullName>
        <label>Organizaciones de cuentas</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Responsable_FL31__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable FLUVIA</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UsuariosFL31</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Responsable_IE20__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable LIGHTING</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UsuariosIE20</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Responsable_SI10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable SIMON</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UsuariosSI10</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>KS_Distribuidores_SAP</fullName>
        <active>true</active>
        <description>Tipo de registro para albergar clientes distribuidores provenientes de SAP</description>
        <label>Distribuidores SAP</label>
    </recordTypes>
    <recordTypes>
        <fullName>KS_Lead</fullName>
        <active>true</active>
        <description>Tipo de registro, para cuentas de tipo Candidatos</description>
        <label>Cuenta</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/KS_Estructura_Geografica__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto donde se recoge la configuración de regiones y areas para cada organización</description>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_CPDesde__c</fullName>
        <label>CPDesde</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_CPHasta__c</fullName>
        <label>CPHasta</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_CountryCode__c</fullName>
        <label>CountryCode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ISOCountryCodes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Delegacion__c</fullName>
        <label>Delegación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Delegacion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Zona__c</fullName>
        <label>Zona</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Zona_Geog</valueSetName>
        </valueSet>
    </fields>
    <label>Estructura Geografica</label>
    <nameField>
        <label>Estructura Geografica</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estructuras Geograficas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Organizacion_Cliente__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto vinculado con las cuentas (marcas) que muestra las organizaciones de ventas para cada cliente</description>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Canal_de_distribucion__c</fullName>
        <label>Canal de distribución</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Canal_de_distribucion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Cliente_Dest_Mercancias__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente Dest. Mercancias</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Clientes Dest. Mercancias</relationshipLabel>
        <relationshipName>Clientes_Dest_Mercancias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Cliente_Distribucion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente Distribución</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3) OR 4</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Distribuidores_SAP</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Lead</value>
            </filterItems>
            <filterItems>
                <field>Account.KS_Canal__c</field>
                <operation>equals</operation>
                <value>Distribuidores CRM</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Distribuidores CRM</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marcas Comerciales</relationshipLabel>
        <relationshipName>Organizaciones_Cliente</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Cliente_solicitante__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente solicitante</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Marcas Comerciales</relationshipLabel>
        <relationshipName>Clientes_solicitantes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Delegacion__c</fullName>
        <label>Delegación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Delegacion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_ID_Organizacion_Cliente__c</fullName>
        <externalId>true</externalId>
        <label>ID Organizacion Cliente</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>KS_Lista_de_precios__c</fullName>
        <label>Lista de precios</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Lista_de_precios</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Responsable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ResponablesOrgCliente</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Sector_Distribuidor__c</fullName>
        <label>Sector (Distribuidor)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Tipo_Sector</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Zona__c</fullName>
        <label>Zona</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Zona_Geog</valueSetName>
        </valueSet>
    </fields>
    <label>Organización Cliente</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Nombre de Organización Cliente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizaciones Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Territory2.object
<CustomObject>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <label>Canal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Canal_de_distribucion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizacion_Ventas__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Sector_Distribuidor__c</fullName>
        <label>Sector (Distribuidor)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Tipo_Sector</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/globalValueSets/ISOCountryCodes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AS</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BQ</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <default>true</default>
        <label>ES</label>
    </customValue>
    <description>EN USO --&gt; Estructuras geográficas / Autorizaciones Ofertas</description>
    <masterLabel>ISOCountryCodes</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Area.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1010</fullName>
    </customValue>
    <customValue>
        <fullName>1020</fullName>
    </customValue>
    <customValue>
        <fullName>1021</fullName>
    </customValue>
    <customValue>
        <fullName>1030</fullName>
    </customValue>
    <customValue>
        <fullName>1040</fullName>
    </customValue>
    <customValue>
        <fullName>1050</fullName>
    </customValue>
    <customValue>
        <fullName>1060</fullName>
    </customValue>
    <customValue>
        <fullName>INTE</fullName>
    </customValue>
    <description>SAP. IDs SAP de Área</description>
    <masterLabel>Área</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Canal.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Distribuidores CRM</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Prescriptores</fullName>
    </customValue>
    <customValue>
        <fullName>Clientes finales</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidores SAP</fullName>
    </customValue>
    <customValue>
        <fullName>Varios</fullName>
        <isActive>false</isActive>
        <label>Varios</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en Cuentas</description>
    <masterLabel>Canal</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Canal_de_distribucion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>Nacional</fullName>
        <isActive>false</isActive>
        <label>Nacional</label>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente - Jerarquia Cliente - Producto --&gt; CARGADO</description>
    <masterLabel>Canal de distribución</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Delegacion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>009</fullName>
    </customValue>
    <customValue>
        <fullName>010</fullName>
    </customValue>
    <customValue>
        <fullName>011</fullName>
    </customValue>
    <customValue>
        <fullName>012</fullName>
    </customValue>
    <customValue>
        <fullName>013</fullName>
    </customValue>
    <customValue>
        <fullName>015</fullName>
    </customValue>
    <customValue>
        <fullName>017</fullName>
    </customValue>
    <customValue>
        <fullName>018</fullName>
    </customValue>
    <customValue>
        <fullName>019</fullName>
    </customValue>
    <customValue>
        <fullName>020</fullName>
    </customValue>
    <customValue>
        <fullName>021</fullName>
    </customValue>
    <customValue>
        <fullName>023</fullName>
    </customValue>
    <customValue>
        <fullName>024</fullName>
    </customValue>
    <customValue>
        <fullName>025</fullName>
    </customValue>
    <customValue>
        <fullName>026</fullName>
    </customValue>
    <customValue>
        <fullName>027</fullName>
    </customValue>
    <customValue>
        <fullName>028</fullName>
    </customValue>
    <customValue>
        <fullName>029</fullName>
    </customValue>
    <customValue>
        <fullName>030</fullName>
    </customValue>
    <customValue>
        <fullName>031</fullName>
    </customValue>
    <customValue>
        <fullName>032</fullName>
    </customValue>
    <customValue>
        <fullName>033</fullName>
    </customValue>
    <customValue>
        <fullName>034</fullName>
    </customValue>
    <customValue>
        <fullName>035</fullName>
    </customValue>
    <customValue>
        <fullName>036</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <description>SAP. IDs SAP de Delegación</description>
    <masterLabel>Delegación</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Lista_de_precios.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>00</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>EC</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>PU</fullName>
    </customValue>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <customValue>
        <fullName>E0</fullName>
    </customValue>
    <customValue>
        <fullName>T0</fullName>
    </customValue>
    <customValue>
        <fullName>T1</fullName>
    </customValue>
    <customValue>
        <fullName>T2</fullName>
    </customValue>
    <customValue>
        <fullName>T3</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
    </customValue>
    <customValue>
        <fullName>B2</fullName>
    </customValue>
    <customValue>
        <fullName>B3</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente --&gt; CARGADO</description>
    <masterLabel>Lista de precios</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Organizacion_de_ventas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>FL31</fullName>
    </customValue>
    <customValue>
        <fullName>GI50</fullName>
    </customValue>
    <customValue>
        <fullName>IE20</fullName>
    </customValue>
    <customValue>
        <fullName>MA15</fullName>
    </customValue>
    <customValue>
        <fullName>MA16</fullName>
    </customValue>
    <customValue>
        <fullName>MX24</fullName>
    </customValue>
    <customValue>
        <fullName>MX25</fullName>
    </customValue>
    <customValue>
        <fullName>MX26</fullName>
    </customValue>
    <customValue>
        <fullName>SI10</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente / Jerarquia Cliente / Producto / Autorizaciones Oferta --&gt; CARGADO</description>
    <masterLabel>Organizacion de ventas</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Tipo_Sector.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <customValue>
        <fullName>40</fullName>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>60</fullName>
    </customValue>
    <customValue>
        <fullName>70</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente - Jerarquia Cliente - Producto --&gt; CARGADO</description>
    <masterLabel>Tipo Sector (SAP)</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Zona_Geog.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>23</fullName>
    </customValue>
    <customValue>
        <fullName>24</fullName>
    </customValue>
    <customValue>
        <fullName>25</fullName>
    </customValue>
    <customValue>
        <fullName>26</fullName>
    </customValue>
    <customValue>
        <fullName>27</fullName>
    </customValue>
    <customValue>
        <fullName>28</fullName>
    </customValue>
    <customValue>
        <fullName>29</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <description>SAP. En Uso en Oportunidaes/Obras</description>
    <masterLabel>Zona Geog.</masterLabel>
</GlobalValueSet>

src/classes/KS_OrgCliente_Trigger.cls
public without sharing class KS_OrgCliente_Trigger extends KS_TriggerController {

    public KS_OrgCliente_Trigger (Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate,
        List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems)
    {
        super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);
    }
    
    public static Boolean blocked() { System.debug('-- TRIGGER BLOCKED! --'); return Test.isRunningTest() && KS_Trigger_Test.blockTrigger; }
    
    public static Map<ID,Boolean> accInUse = new Map<ID,Boolean>();
    public static Map<ID,sObject> orgInUse = new Map<ID,sObject>();
    
    public Map<String,ID> recordTypes;
    protected override void runBeforeInsert(){ if(blocked()){return;} executeBeforeInsert(); }
    protected override void runBeforeUpdate(){ if(blocked()){return;} executeBeforeUpdate(); } 
    public void executeBeforeInsert() { executeBeforeUpsert(); }
    public void executeBeforeUpdate() { executeBeforeUpsert(); }       
    public void executeBeforeUpsert() {
        
        if (orgInUse != null && !orgInUse.isEmpty()) { return; }
        if (mapNewItems != null && !mapNewItems.isEmpty()) { orgInUse.putAll(mapNewItems); }
        
        System.debug('----------------------------------------JCAR - isBatch? : ' + System.isBatch());
        if (System.isBatch()) {return;}        
        
        recordTypes = new Map<String,ID>();
        List<RecordType> rtLst = [SELECT ID,DeveloperName FROM RecordType];
        for (RecordType rt : rtLst) {
            recordTypes.put(rt.DeveloperName, rt.ID);
        }
        Map<String,ID> terrType = new Map<String,ID>();
        List<Territory2Type> terrLst = [SELECT ID, DeveloperName FROM Territory2Type];
        for (Territory2Type tp : terrLst) {
            terrType.put(tp.DeveloperName, tp.ID);
        }        
        
        List<KS_Organizacion_Cliente__c> orgclLST = (List<KS_Organizacion_Cliente__c>)lstNewItems;
        
        Map<String, KS_Organizacion_Cliente__c> mapSAP2Orga = new Map<String, KS_Organizacion_Cliente__c>();
        Map<String, Id> mapSAP2Clie = new Map<String, Id>();
        Map<String, String> mapSAP2Vent = new Map<String, String>();
        
        Map<Id, String> mapPostalCode = new Map<Id, String>();
        Map<Id, Account> mapAccounts = new Map<Id, Account>();
        Map<String, KS_Estructura_Geografica__c> mapPC2EG = new Map<String, KS_Estructura_Geografica__c>();
        
        // Asignación ORG-ventas
        Map<ID, Set<String>> orgVentasCliente = new Map<ID, Set<String>>();
        
        for (KS_Organizacion_Cliente__c orgcl : orgclLST) {
            
            ID accID = getAccountOrgCliente(orgcl);
            
            List<String> orgaWVentas = new List<String>();
            if (orgcl.KS_Organizacion_de_ventas__c != null && accID != null) {
                               
                mapSAP2Orga.put(orgcl.KS_ID_Organizacion_Cliente__c, orgcl);
                mapSAP2Clie.put(orgcl.KS_ID_Organizacion_Cliente__c, accID);
                mapSAP2Vent.put(orgcl.KS_ID_Organizacion_Cliente__c, orgcl.KS_Organizacion_de_ventas__c);
                //mapPostalCode.put(orgcl., null);
                
                // Asignación ORG-ventas
                Set<String> orgVentas = new Set<String>();
                if (orgVentasCliente.containsKey(accID)) {
                    orgVentas = orgVentasCliente.get(accID);
                }
                orgVentas.add(orgcl.KS_Organizacion_de_ventas__c);
                orgVentasCliente.put(accID, orgVentas);
            }
            
            if (orgcl.KS_Lista_de_precios__c == null) { // tarifa is NULL
                
            }
        }
        
        if (!Test.isRunningTest()) { 
            System.debug('----------------------------------------JCAR - ' + mapSAP2Orga.size() + ' mapSAP2Orga : ' + mapSAP2Orga);
            System.debug('----------------------------------------JCAR - ' + mapSAP2Clie.size() + ' mapSAP2Clie : ' + mapSAP2Clie);
            System.debug('----------------------------------------JCAR - ' + mapSAP2Vent.size() + ' mapSAP2Vent : ' + mapSAP2Vent);
        }
    
        List<Account> accLst = [SELECT ID,KS_Id_SAP__c,BillingPostalCode,BillingCountryCode,ShippingPostalCode,ShippingCountryCode,
                                KS_Organizacion_Ventas__c,KS_Organizaciones_de_cuentas__c
                                FROM Account WHERE ID in :mapSAP2Clie.values() 
                                /*AND (RecordTypeId = :recordTypes.get('KS_Distribuidores_SAP') OR RecordTypeId = :recordTypes.get('KS_Lead'))*/];
        for (Account acc : accLst) {
            //mapPostalCode.put(acc.ID, acc.BillingPostalCode);
            mapAccounts.put(acc.ID, acc);
        }
        if (!Test.isRunningTest()) { System.debug('----------------------------------------JCAR - ' + mapAccounts.size() + ' mapAccounts : ' + mapAccounts); }
        
        List<KS_Estructura_Geografica__c> esGeogLst = 
            [SELECT Id, KS_CPDesde__c, KS_CPHasta__c, KS_Delegacion__c, KS_Area__c, KS_Zona__c, KS_Organizacion_de_ventas__c, KS_CountryCode__c 
             FROM KS_Estructura_Geografica__c WHERE KS_Organizacion_de_ventas__c in :mapSAP2Vent.values()];
        if (!Test.isRunningTest()) { System.debug('----------------------------------------JCAR - ' + esGeogLst.size() + ' KS_Estructura_Geografica__c : ' + esGeogLst); }
        
        //List<Account> accUPDATE = new List<Account>();
        Map<Id, Account> accUPDATE = new Map<Id, Account>();
        for (Account acc : mapAccounts.values()) {
            
            String countryS = acc.ShippingCountryCode != null ? acc.ShippingCountryCode : acc.BillingCountryCode;
            
            Boolean validCountry = (countryS == 'ES' || countryS == 'PT' || countryS == 'AD');
            
            String postalCodeS = acc.ShippingPostalCode != null ? acc.ShippingPostalCode : acc.BillingPostalCode;
            
            Integer i = 0;
            Map<String,Boolean> nextM = new Map<String,Boolean>();
            
            if (!Test.isRunningTest()) { 
                System.debug('----------------------------------------JCAR - postalCodeS : ' + postalCodeS);
                System.debug('----------------------------------------JCAR - validCountry : ' + countryS + ' - ' + validCountry);
            }
            
            while (i<esGeogLst.size() && validCountry && postalCodeS != null) {
                
                KS_Estructura_Geografica__c eg = esGeogLst.get(i);
                String dsd = eg.KS_CPDesde__c;
                String hst = eg.KS_CPHasta__c;
                
                Boolean goodPS = false;
                if (eg.KS_CountryCode__c == countryS && (countryS == 'AD' || countryS == 'ES') && dsd != null ) { // ANDORRA || ESPAÑA
                
                    if (postalCodeS.length() == 4) { 
                        postalCodeS = '0'+postalCodeS;
                        if(acc.ShippingPostalCode != null) {
                            acc.ShippingPostalCode = postalCodeS;
                        } else {
                            acc.BillingPostalCode = postalCodeS;
                        }
                    }
                    goodPS = postalCodeS.startsWithIgnoreCase(dsd.substring(0,2));
                
                } else if (countryS == 'PT' && eg.KS_CountryCode__c == countryS && dsd != null  && hst != null ) { // PORTUGAL
                    
                    if (dsd.split('-')[0].isNumeric() && hst.split('-')[0].isNumeric() && postalCodeS.split('-')[0].split(' ')[0].isNumeric()) {
                        Integer z = Integer.valueOf(postalCodeS.split('-')[0].split(' ')[0]);
                        Integer x = Integer.valueOf(dsd.split('-')[0]);
                        Integer y = Integer.valueOf(hst.split('-')[0]);
                        goodPS = (z >= x && z <= y);
                    }
                    
                } else { // Internacional, se sigue otra lógica
                    
                    goodPS = eg.KS_CountryCode__c == countryS && countryS == eg.KS_Delegacion__c && eg.KS_Area__c == 'INTE';
                }
                
                if (goodPS) { // se ha encontrado un CP
                    mapPC2EG.put(postalCodeS+'_'+eg.KS_Organizacion_de_ventas__c, eg);
                }
                i++;
            }
            
            if (!Test.isRunningTest()) { System.debug('----------------------------------------JCAR - mapPC2EG : ' + mapPC2EG); }
        }
        
        List<String> areaGLst = new List<String>();
        List<String> orgVnLST = new List<String>();
        List<String> canalLST = new List<String>();
        List<String> sectrLST = new List<String>();
        Map<String, KS_Organizacion_Cliente__c> marcareaOrgCliente = new Map<String, KS_Organizacion_Cliente__c>();
        Set<String> validMarca = KS_OrgCliente_Util.validMarcas();
        
        Set<ID> accounts = new Set<ID>();
        List<String> marcareas = new List<String>();
        for (String orgclK : mapSAP2Orga.keySet()) {
            
            KS_Organizacion_Cliente__c orgcl = (KS_Organizacion_Cliente__c)mapSAP2Orga.get(orgclK);
            ID accID = getAccountOrgCliente(orgcl);
            //KS_Estructura_Geografica__c eg = mapPC2EG.get(mapPostalCode.get(accID));
            if (!Test.isRunningTest()) { System.debug('----------------------------------------JCAR - mapAccounts.get(accID) : ' + mapAccounts.get(accID)); }
            if (mapAccounts.get(accID) != null) {
                
                Account acc = mapAccounts.get(accID);
                if (accUPDATE.containsKey(accID)) { acc = accUPDATE.get(accID);}
                
                String countryS = acc.ShippingCountryCode != null ? acc.ShippingCountryCode : acc.BillingCountryCode;
                Boolean validCountry = (countryS == 'ES' || countryS == 'PT' || countryS == 'AD');                 
                if (orgcl.KS_Lista_de_precios__c == null && validCountry) { // tarifa is NULL
                    
                    if (countryS == 'ES' || countryS == 'AD') {
                        orgcl.KS_Lista_de_precios__c = '00';
                    } else if (countryS == 'PT') {
                        orgcl.KS_Lista_de_precios__c = '10';
                    }
                }
                
                String billingPostalCode = acc.ShippingPostalCode != null ? acc.ShippingPostalCode : acc.BillingPostalCode;
                KS_Estructura_Geografica__c eg = mapPC2EG.get(billingPostalCode+'_'+orgcl.KS_Organizacion_de_ventas__c);
                if (eg != null) { 
                    if (!Test.isRunningTest()) { System.debug('----------------------------------------JCAR - KS_Estructura_Geografica__c : ' + eg); }
                    orgcl.KS_Area__c = eg.KS_Area__c;
                    orgcl.KS_Delegacion__c = eg.KS_Delegacion__c;
                    orgcl.KS_Zona__c = eg.KS_Zona__c;
                    if (!Test.isRunningTest()) { System.debug('----------------------------------------JCAR - orgcl+eg : ' + orgcl); }
                    
                    /*String marcarea = eg.KS_Organizacion_de_ventas__c+'-'+orgcl.KS_Canal_de_distribucion__c+'-'+orgcl.KS_Sector_Distribuidor__c+'-'
                        +eg.KS_Area__c+'-'+eg.KS_Delegacion__c+'-'+eg.KS_Zona__c;
                    acc.KS_Organizaciones_de_cuentas__c = acc.KS_Organizaciones_de_cuentas__c != null ? acc.KS_Organizaciones_de_cuentas__c : '';
                    System.debug('----------------------------------------JCAR - marcarea : ' + marcarea);
                    System.debug('----------------------------------------JCAR - acc.KS_Organizaciones_de_cuentas__c : ' + acc.KS_Organizaciones_de_cuentas__c);
                    if (!acc.KS_Organizaciones_de_cuentas__c.containsIgnoreCase(marcarea)) {
                        acc.KS_Organizaciones_de_cuentas__c += marcarea+';';
                        accUPDATE.put(acc.ID, acc);
                        accounts.add(acc.ID);
                    }*/
                    
                    acc.KS_Organizaciones_de_cuentas__c =
                        KS_OrgCliente_Util.buildMarcaAreaCuenta(
                            acc.KS_Organizaciones_de_cuentas__c,
                            orgcl.KS_Organizacion_de_ventas__c,
                            orgcl.KS_Canal_de_distribucion__c,
                            orgcl.KS_Sector_Distribuidor__c,
                            eg.KS_Area__c, eg.KS_Delegacion__c, eg.KS_Zona__c,
                            validMarca);
                    if (!Test.isRunningTest()) { System.debug('----------------------------------------JCAR - acc.KS_Organizaciones_de_cuentas__c : ' + acc.KS_Organizaciones_de_cuentas__c); }
                    
                    String maK = eg.KS_Organizacion_de_ventas__c+'-'+orgcl.KS_Canal_de_distribucion__c+'-'+orgcl.KS_Sector_Distribuidor__c+'-'+eg.KS_Area__c;
                    areaGLst.add(eg.KS_Area__c);
                    orgVnLST.add(eg.KS_Organizacion_de_ventas__c);
                    canalLST.add(orgcl.KS_Canal_de_distribucion__c);
                    sectrLST.add(orgcl.KS_Sector_Distribuidor__c);
                    marcareaOrgCliente.put(maK, orgcl);
                }
            }
        }
        
        System.debug('-- JCAR ---------------------------------- executeBeforeUpsert JAR - ' + marcareaOrgCliente.size() + ' marcareaOrgCliente - ' + marcareaOrgCliente);
        if (!Test.isRunningTest()) { 
            System.debug('-- JCAR ---------------------------------- executeBeforeUpsert JAR - ' + orgVnLST.size() + ' orgVnLST - ' + orgVnLST);
            System.debug('-- JCAR ---------------------------------- executeBeforeUpsert JAR - ' + canalLST.size() + ' canalLST - ' + canalLST);
            System.debug('-- JCAR ---------------------------------- executeBeforeUpsert JAR - ' + sectrLST.size() + ' sectrLST - ' + sectrLST);
            System.debug('-- JCAR ---------------------------------- executeBeforeUpsert JAR - ' + areaGLst.size() + ' areaGLst - ' + areaGLst);
            System.debug('-- JCAR ---------------------------------- executeBeforeUpsert JAR - ' + terrType.size() + ' terrType - ' + terrType);
        }
    
        List<UserTerritory2Association> terrOferta = 
            [SELECT Id, UserId, Territory2Id, RoleInTerritory2,
             Territory2.KS_Organizacion_Ventas__c,
             Territory2.KS_Canal__c,
             Territory2.KS_Sector_Distribuidor__c,
             Territory2.KS_Area__c
             FROM UserTerritory2Association 
             WHERE RoleInTerritory2 = 'JAR'
             AND Territory2.KS_Organizacion_Ventas__c IN :orgVnLST
             AND Territory2.KS_Canal__c IN :canalLST
             AND Territory2.KS_Sector_Distribuidor__c IN :sectrLST
             AND Territory2.KS_Area__c IN :areaGLst
             AND Territory2.Territory2TypeId = :terrType.get('KS_Area')
            ];
        if (!Test.isRunningTest()) { System.debug('-- JCAR ---------------------------------- executeBeforeUpsert JAR - ' + terrOferta.size() + ' terrOferta - ' + terrOferta); }
        for (UserTerritory2Association uta : terrOferta) {
            
            String maK = uta.Territory2.KS_Organizacion_Ventas__c+'-'
                +uta.Territory2.KS_Canal__c+'-'
                +uta.Territory2.KS_Sector_Distribuidor__c+'-'
                +uta.Territory2.KS_Area__c;
            
            if (!Test.isRunningTest()) { System.debug('-- JCAR ---------------------------------- executeBeforeUpsert JAR - ' + maK + ' - ' + uta.UserId); }
            
            if (marcareaOrgCliente.containsKey(maK) && uta.UserId != null) {
                
                KS_Organizacion_Cliente__c orgcl = marcareaOrgCliente.get(maK);
                orgcl.KS_Responsable__c = uta.UserId;
                
                if (!Test.isRunningTest()) { System.debug('-- JCAR ---------------------------------- executeBeforeUpsert JAR - ' + orgcl); }
                
                if (orgcl.KS_Cliente_Distribucion__c != null) {
                    
                    Account acc = new Account(); acc.ID = orgcl.KS_Cliente_Distribucion__c;
                    if (accUPDATE.containsKey(acc.ID)) { acc = accUPDATE.get(acc.ID); }
                    /*
                    String marca = orgcl.KS_Organizacion_de_ventas__c;
                    if (marca == 'SI10')
                    { acc.KS_Responsable_SI10__c = uta.UserId; accUPDATE.put(acc.ID, acc); }
                    if (marca == 'FL31')
                    { acc.KS_Responsable_FL31__c = uta.UserId; accUPDATE.put(acc.ID, acc); }
                    if (marca == 'IE20')
                    { acc.KS_Responsable_IE20__c = uta.UserId; accUPDATE.put(acc.ID, acc); }
					*/
                    //if (accInUse == null || (accInUse != null && accInUse.isEmpty()) || (accInUse != null && accInUse.containsKey(acc.ID)) ) {
                        if (accUPDATE == null)  {accUPDATE = new Map<ID,Account>(); } accUPDATE.put(acc.ID, acc);
                        //if (accInUse == null)  {accInUse = new Map<ID,Boolean>(); } accInUse.put(acc.ID, true);
                    //} 
                }
            }
        }
        
        System.debug('----------------------------------------JCAR - isRunningTest? : ' + Test.isRunningTest());
        System.debug('----------------------------------------JCAR - isBatch? : ' + System.isBatch());
        
        if (accUPDATE.isEmpty()) {accUPDATE.putAll(mapAccounts);}
        else { for (ID accID : mapAccounts.keySet()) { if (!accUPDATE.containsKey(accID)) { accUPDATE.put(accID, mapAccounts.get(accID)); } } }
        
        System.debug('----------------------------------------JCAR - executeBeforeUpsert accUPDATE - ' + accUPDATE.size() + ' - ' + accUPDATE);
        if (accUPDATE.size()>0 && !System.isBatch()) {
            update accUPDATE.values();
            if ( !System.isFuture() ) { futureUpdate(accUPDATE.keySet()); }
            
        }
    }
    
    @future(callout=true)
    public static void futureUpdate(Set<ID> accounts) {
        if (Test.isRunningTest()) {return;}
        //for (ID accID : accounts) { if (accInUse.containsKey(accID)) { return; } }
        futureUpdateCall(accounts);
        //if (accInUse == null) { accInUse = new Map<ID,Boolean>(); }
        //for (ID accID : accounts) { accInUse.put(accID, true); }
    }
    
    public static void futureUpdateCall(Set<ID> accounts) {
        futureUpdateCallTerritory(accounts);
        futureUpdateCallOrgCuenta(accounts);
    }
    public static void futureUpdateCallTerritory(Set<ID> accounts) {
        System.debug('-- JCAR ---------------------------------- - futureUpdateCallTerritory.accounts? ' + accounts.size() + ' accounts - ' + accounts);
        List<ID> ids = new List<ID>(); ids.addAll(accounts);
        TerritoryMangRule.fireTerritoryManagementViaSoap(ids);
    }
    public static void futureUpdateCallOrgCuenta(Set<ID> accounts) {
        
        Set<String> validMarca = KS_OrgCliente_Util.validMarcas();
        Map<ID, Account> accUpdate = new Map<ID, Account>();
        Map<ID, Integer> accSI10 = new Map<ID, Integer>();
        Map<ID, Integer> accFL31 = new Map<ID, Integer>();
        
        for (KS_Organizacion_Cliente__c oc : 
             [SELECT ID, KS_Organizacion_de_ventas__c, KS_Canal_de_distribucion__c, KS_Sector_Distribuidor__c, KS_Area__c, KS_Delegacion__c, KS_Zona__c,
              KS_Cliente_Distribucion__r.KS_Organizaciones_de_cuentas__c FROM KS_Organizacion_Cliente__c WHERE KS_Cliente_Distribucion__c in :accounts]) {
                  
                  Account acc = new Account(); acc.ID = oc.KS_Cliente_Distribucion__c;
                  if (accUpdate.containsKey(acc.ID)) { acc = accUpdate.get(acc.ID); }
                  else { acc.KS_Organizaciones_de_cuentas__c = oc.KS_Cliente_Distribucion__r.KS_Organizaciones_de_cuentas__c; }
                  
                  Integer countSI10 = 0; if (accSI10.containsKey(acc.ID)) { countSI10 = accSI10.get(acc.ID); }
                  Integer countFL31 = 0; if (accFL31.containsKey(acc.ID)) { countFL31 = accFL31.get(acc.ID); }
                  if (oc.KS_Organizacion_de_ventas__c == 'SI10') { countSI10++; }
                  if (oc.KS_Organizacion_de_ventas__c == 'FL31') { countFL31++; }
                  acc.KS_CountOC__c = countSI10 + countFL31;
                  acc.KS_CountOC_SI10__c = countSI10;
                  acc.KS_CountOC_FL31__c = countFL31;
                  accSI10.put(acc.ID, countSI10);
                  accFL31.put(acc.ID, countFL31);
                  
                  acc.KS_Organizaciones_de_cuentas__c =
                      KS_OrgCliente_Util.buildMarcaAreaCuenta(
                          acc.KS_Organizaciones_de_cuentas__c,
                          oc.KS_Organizacion_de_ventas__c,
                          oc.KS_Canal_de_distribucion__c,
                          oc.KS_Sector_Distribuidor__c,
                          oc.KS_Area__c, 
                          oc.KS_Delegacion__c, 
                          oc.KS_Zona__c,
                          validMarca);
                  accUpdate.put(acc.ID, acc);
              }
        System.debug('-- JCAR ---------------------------------- - futureUpdateCallOrgCuenta.accounts? ' + accUpdate.size() + ' accounts - ' + accUpdate.values());
        //accInUse = new Map<ID,Boolean>(); for (ID accID : accUpdate.keySet()) { accInUse.put(accID, true); }
        update accUpdate.values();
    }
    
    public ID getAccountOrgCliente(KS_Organizacion_Cliente__c orgcl) {
        
        ID accID = null;
        if (orgcl.KS_Cliente_Dest_Mercancias__c != null) {
            accID = orgcl.KS_Cliente_Dest_Mercancias__c;
        }
        if (orgcl.KS_Cliente_solicitante__c != null) {
            accID = orgcl.KS_Cliente_solicitante__c;
        }
        if (orgcl.KS_Cliente_Distribucion__c != null) {
            accID = orgcl.KS_Cliente_Distribucion__c;
        }
        return accID;
    }
    
    protected override void runAfterInsert(){ executeAfterInsert(); }
    protected override void runAfterUpdate(){ executeAfterUpdate(); } 
    public void executeAfterInsert() { executeAfterUpsert(); }
    public void executeAfterUpdate() { executeAfterUpsert(); }       
    public void executeAfterUpsert() {      
        
        Map<ID, Account> accUpdate = new Map<ID, Account>();
        List<KS_Organizacion_Cliente__c> orgclLST = (List<KS_Organizacion_Cliente__c>)lstNewItems;
        //system.debug('JCAR - executeAfterUpsert --------------------- : ' + orgclLST);
        for (KS_Organizacion_Cliente__c orgcl : orgclLST) {
            
            String accID = orgcl.KS_Cliente_Distribucion__c;
            accID = accID != null ? accID : orgcl.KS_Cliente_Dest_Mercancias__c;
            accID = accID != null ? accID : orgcl.KS_Cliente_solicitante__c;
            if (orgcl.KS_Responsable__c != null && accID != null) {
                
                Account acc = new Account(); acc.ID = accID;
                if (accUpdate.containsKey(accID)) { acc = accUpdate.get(accID); }
                
                String marca = orgcl.KS_Organizacion_de_ventas__c;
                if (marca == 'SI10')
                { acc.KS_Responsable_SI10__c = orgcl.KS_Responsable__c; accUPDATE.put(acc.ID, acc); }
                if (marca == 'FL31')
                { acc.KS_Responsable_FL31__c = orgcl.KS_Responsable__c; accUPDATE.put(acc.ID, acc); }
                if (marca == 'IE20')
                { acc.KS_Responsable_IE20__c = orgcl.KS_Responsable__c; accUPDATE.put(acc.ID, acc); }
            }
        }
        
        if (accUpdate.size()>0) {
            system.debug('accUpdate: ' + accUpdate);
            update accUpdate.values();
        }
    }
}