src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <label>Canal</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KS_Actividad__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Canal</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/KS_Obra__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Es el objeto superior que agrega las ofertas (oportunidades)</description>
    <fields>
        <fullName>KS_Prescrito__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prescrito</label>
        <type>Checkbox</type>
    </fields>
    <label>Obra</label>
    <nameField>
        <label>Nombre de Obra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Obras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Organizacion_Cliente__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto vinculado con las cuentas (marcas) que muestra las organizaciones de ventas para cada cliente</description>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <label>Organización Cliente</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Nombre de Organización Cliente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizaciones Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>KS_Agente_de_contabilizacion__c</fullName>
        <label>Agente de contabilización</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KS_Contabiliza__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Contabilizacion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <formula>TEXT(KS_Organizacion_Cliente__r.KS_Canal_de_distribucion__c)</formula>
        <label>Canal</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Contabiliza__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contabiliza</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Distribuidor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribuidor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Distribuidores</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Distribuidores_SAP</value>
            </filterItems>
            <filterItems>
                <field>Account.KS_Grupo_de_ctas_deudor__c</field>
                <operation>notEqual</operation>
                <value>Destinatarios mercancías</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ofertas (Distribuidor)</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>KS_Obra__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Oportunidades</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KS_Obra__c</referenceTo>
        <relationshipLabel>Ofertas</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Organizacion_Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marca Comercial</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>KS_Organizacion_Cliente__c.KS_Cliente_solicitante__c</field>
                <operation>equals</operation>
                <valueField>$Source.KS_Distribuidor__c</valueField>
            </filterItems>
            <filterItems>
                <field>KS_Organizacion_Cliente__c.KS_Cliente_Distribucion__c</field>
                <operation>equals</operation>
                <valueField>$Source.KS_Distribuidor__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KS_Organizacion_Cliente__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Organizacion__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <formula>text( KS_Organizacion_Cliente__r.KS_Organizacion_de_ventas__c )</formula>
        <label>Organización de ventas (FÓRMULA)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Prescrito__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prescrito</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Protected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Protegido</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <formula>Opportunity.KS_Canal__c</formula>
        <label>Canal</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Obra__c</fullName>
        <formula>CASESAFEID(Opportunity.KS_Obra__c)</formula>
        <label>Obra</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Prescrito__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prescrito</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/globalValueSets/KS_Canal.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Distribuidores CRM</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Prescriptores</fullName>
    </customValue>
    <customValue>
        <fullName>Clientes finales</fullName>
    </customValue>
    <customValue>
        <fullName>Asociaciones</fullName>
    </customValue>
    <customValue>
        <fullName>Distribuidores SAP</fullName>
    </customValue>
    <customValue>
        <fullName>Varios</fullName>
        <isActive>false</isActive>
        <label>Varios</label>
    </customValue>
    <description>SEGMENTACIÓN. Usado como variable de segmentación en Cuentas</description>
    <masterLabel>Canal</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Contabilizacion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Distribuidor</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente final</fullName>
    </customValue>
    <description>En uso --&gt; Oferta, para indicar el agente donde contabiliza</description>
    <masterLabel>Contabilizacion</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Organizacion_de_ventas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>FL31</fullName>
    </customValue>
    <customValue>
        <fullName>GI50</fullName>
    </customValue>
    <customValue>
        <fullName>IE20</fullName>
    </customValue>
    <customValue>
        <fullName>MA15</fullName>
    </customValue>
    <customValue>
        <fullName>MA16</fullName>
    </customValue>
    <customValue>
        <fullName>MX24</fullName>
    </customValue>
    <customValue>
        <fullName>MX25</fullName>
    </customValue>
    <customValue>
        <fullName>MX26</fullName>
    </customValue>
    <customValue>
        <fullName>SI10</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente / Jerarquia Cliente / Producto / Autorizaciones Oferta --&gt; CARGADO</description>
    <masterLabel>Organizacion de ventas</masterLabel>
</GlobalValueSet>

src/classes/KS_Opportunity_Trigger_TEST.cls
@isTest
public class KS_Opportunity_Trigger_TEST {

    public static testMethod void TEST_KS_Opportunity_Trigger() {
        
        KS_Trigger_Test.disableTrigger();
        KS_Trigger_Test.testTrigger();
        KS_TEST_FUNCTIONS tstfnc = new KS_TEST_FUNCTIONS();
        Opportunity opp = [SELECT ID,KS_Distribuidor__c,KS_Organizacion_Cliente__c,KS_Organizacion__c,KS_Obra__c,Pricebook2Id FROM Opportunity LIMIT 1];
        
        Opportunity opp2 = tstfnc.createOferta(
            new Account(ID=opp.KS_Distribuidor__c), 
            new KS_Organizacion_Cliente__c(ID=opp.KS_Organizacion_Cliente__c,KS_Organizacion_de_ventas__c=opp.KS_Organizacion__c), 
            new KS_Obra__c(ID=opp.KS_Obra__c), 
            new Pricebook2(ID=opp.Pricebook2Id)); // creamos una segunda oferta
        Opportunity oppOLD = opp.clone();
        KS_Trigger_Test.enableTrigger();
        
        Test.startTest();
        
        opp.KS_Contabiliza__c = true;
        opp.KS_Agente_de_contabilizacion__c = 'Distribuidor';
        opp.KS_Prescrito__c = true;   
        opp.KS_Organizacion__c = 'SI10';
        
        opp2.KS_Contabiliza__c = true;
        opp2.KS_Agente_de_contabilizacion__c = 'Distribuidor';
        opp2.KS_Prescrito__c = true;   
        opp2.KS_Organizacion__c = 'SI10';
        UPDATE opp2;
        
        List<sObject> sobjL = new List<sObject>(); sobjL.add(opp);
        List<sObject> sobjLOLD = new List<sObject>(); sobjLOLD.add(oppOLD);
        Map<Id, sObject> sobjM = new Map<Id, sObject>(); sobjM.put(opp.ID,opp);
        Map<Id, sObject> sobjMOLD = new Map<Id, sObject>(); sobjMOLD.put(oppOLD.ID,oppOLD);
        
        KS_Opportunity_Trigger trig = null;
        trig = new KS_Opportunity_Trigger(
            true, true, true, true, true, true, sobjL, sobjM, sobjLOLD, sobjMOLD);
        trig.executeBeforeInsert(); trig.executeAfterInsert(); trig.executeBeforeUpdate(); trig.executeAfterUpdate();   
        trig.callValidClienteOferta(opp);
        trig.getDescarted(opp);
        trig.setUbicacionObra();
        KS_Opportunity_Trigger.cloneOpportunity(opp);
        KS_Opportunity_Trigger.cloneOpportunityLineItem(new OpportunityLineItem(), opp.ID);
        trig.setPriceBookID(opp.Pricebook2Id);
        
        opp2.KS_Protected__c = true;
        UPDATE opp2;
        opp.KS_Protected__c = true;
        oppOLD = opp.clone();
        sobjL = new List<sObject>(); sobjL.add(opp);
        sobjLOLD = new List<sObject>(); sobjLOLD.add(oppOLD);
        sobjM = new Map<Id, sObject>(); sobjM.put(opp.ID,opp);
        sobjMOLD = new Map<Id, sObject>(); sobjMOLD.put(oppOLD.ID,oppOLD);
        trig = new KS_Opportunity_Trigger(
            true, true, true, true, true, true, sobjL, sobjM, sobjLOLD, sobjMOLD);
        trig.executeDuplicate();
    }   
    
    public static testMethod void TEST_KS_Opportunity_Trigger_sincro() {
        
        KS_Trigger_Test.disableTrigger();
        KS_Trigger_Test.testTrigger();
        KS_TEST_FUNCTIONS tstfnc = new KS_TEST_FUNCTIONS();
        Opportunity opp = [SELECT ID,KS_Distribuidor__c,KS_Organizacion_Cliente__c,KS_Organizacion__c,KS_Obra__c,Pricebook2Id FROM Opportunity LIMIT 1];
        Opportunity oppOLD = opp.clone();
        
        Opportunity opp2 = tstfnc.createOferta(
            new Account(ID=opp.KS_Distribuidor__c), 
            new KS_Organizacion_Cliente__c(ID=opp.KS_Organizacion_Cliente__c,KS_Organizacion_de_ventas__c=opp.KS_Organizacion__c), 
            new KS_Obra__c(ID=opp.KS_Obra__c), 
            new Pricebook2(ID=opp.Pricebook2Id)); // creamos una segunda oferta
        
        opp.KS_Contabiliza__c = true;
        opp.KS_Agente_de_contabilizacion__c = 'Distribuidor';
        opp.KS_Prescrito__c = true;   
        opp.KS_Organizacion__c = 'SI10';
        
        opp2.KS_Contabiliza__c = true;
        opp2.KS_Agente_de_contabilizacion__c = 'Distribuidor';
        opp2.KS_Prescrito__c = true;   
        opp2.KS_Organizacion__c = 'SI10';
        UPDATE opp2;
        
        List<sObject> sobjL = new List<sObject>(); sobjL.add(opp);
        List<sObject> sobjLOLD = new List<sObject>(); sobjLOLD.add(oppOLD);
        Map<Id, sObject> sobjM = new Map<Id, sObject>(); sobjM.put(opp.ID,opp);
        Map<Id, sObject> sobjMOLD = new Map<Id, sObject>(); sobjMOLD.put(oppOLD.ID,oppOLD);
        
        KS_Opportunity_Trigger trig = null;
        trig = new KS_Opportunity_Trigger(
            true, true, true, true, true, true, sobjL, sobjM, sobjLOLD, sobjMOLD);
        
        Test.startTest();
        KS_Trigger_Test.enableTrigger();
        
        String sincroKey = opp.KS_Obra__c+opp.KS_Organizacion__c;
        Map<ID,Opportunity> oppUpdate = new Map<ID,Opportunity>();
        Map<String, Boolean> obraContaAgente = new Map<String, Boolean>();
        Map<String,Opportunity> sincroClieFin = new Map<String,Opportunity>();
        Map<String,Opportunity> sincroInstala = new Map<String,Opportunity>();
        Map<String,Opportunity> sincroDistrib = new Map<String,Opportunity>();

        /*String kmarca = 
            (opp.KS_Canal__c != null ? opp.KS_Canal__c : '')
            + (opp.KS_Organizacion_de_ventas__c != null ? opp.KS_Organizacion_de_ventas__c : '') 
            + (opp.KS_Agente_de_contabilizacion__c != null ? opp.KS_Agente_de_contabilizacion__c : '');
        obraContaAgente.put(opp.KS_Obra__c + kmarca, true);*/
        
        sincroInstala.put(sincroKey, opp2);
        sincroClieFin.put(sincroKey, opp2);
        trig.calcSincronizacion(sobjL, oppUpdate, obraContaAgente, sincroClieFin, sincroInstala, sincroDistrib);
        
        sincroClieFin = new Map<String,Opportunity>();
        sincroInstala = new Map<String,Opportunity>();
        
        opp.KS_Agente_de_contabilizacion__c = 'Instalador';
        
        sobjL = new List<sObject>(); sobjL.add(opp);
        sincroDistrib.put(sincroKey, opp2);
        trig.calcSincronizacion(sobjL, oppUpdate, obraContaAgente, sincroClieFin, sincroInstala, sincroDistrib);
        
        sincroDistrib = new Map<String,Opportunity>();
        sincroClieFin.put(sincroKey, opp2);
        trig.calcSincronizacion(sobjL, oppUpdate, obraContaAgente, sincroClieFin, sincroInstala, sincroDistrib);
        
        sincroDistrib = new Map<String,Opportunity>();
        sincroClieFin = new Map<String,Opportunity>();
        sincroInstala = new Map<String,Opportunity>();
        
        opp.KS_Agente_de_contabilizacion__c = 'Cliente final';
        
        sincroDistrib.put(sincroKey, opp2);
        trig.calcSincronizacion(sobjL, oppUpdate, obraContaAgente, sincroClieFin, sincroInstala, sincroDistrib);
        
        sincroDistrib = new Map<String,Opportunity>();
        sincroInstala.put(sincroKey, opp2);
        trig.calcSincronizacion(sobjL, oppUpdate, obraContaAgente, sincroClieFin, sincroInstala, sincroDistrib);
        
        sincroDistrib = new Map<String,Opportunity>();
        sincroClieFin = new Map<String,Opportunity>();
        sincroInstala = new Map<String,Opportunity>();
        trig.calcSincronizacion(sobjL, oppUpdate, obraContaAgente, sincroClieFin, sincroInstala, sincroDistrib);
    }
}