src/objects/KS_Conf_Organizacion_Cliente__mdt.object
<CustomObject>
    <fields>
        <fullName>KS_Canal_SAP__c</fullName>
        <label>Canal SAP</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Lista_de_precios__c</fullName>
        <label>Lista de precios</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <label>Organizacion de ventas</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Sector__c</fullName>
        <label>Sector</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Organizacion Cliente</label>
    <pluralLabel>Organizaciones Clientes</pluralLabel>
</CustomObject>

src/classes/KS_OrgCliente_Util.cls
global class KS_OrgCliente_Util {

    global static String buildID(String idDistr, String idClFnal, String idSolic, 
                                 String orgVentas, String canal, String sector, String ofiVentas) {
                                     
                                     String idOrgCliente = '';
                                     
                                     idOrgCliente = idDistr;
                                     if (idClFnal != null) { idOrgCliente += '-' + idClFnal; }
                                     if (idSolic != null) { idOrgCliente += '-' + idSolic; }
                                     if (orgVentas != null) { idOrgCliente += '-' + orgVentas; }
                                     if (canal != null) { idOrgCliente += '-' + canal; }
                                     if (sector != null) { idOrgCliente += '-' + sector; }
                                     if (ofiVentas != null) { idOrgCliente += '-' + ofiVentas; }
                                     
                                     return idOrgCliente;
                                 }
    
    global static String buildMarcaAreaCuenta
        (String marcArea, String orgVentas, String canal, 
         String sector, String area, String delega, String zona,
         Set<String> validMarcas) {
             
             String marca = '';//orgVentas + '-' + canal + '-' + sector;
             if (orgVentas != null) { marca += orgVentas; }
             if (canal != null) { marca += '-' + canal; }
             if (sector != null) { marca += '-' + sector; }
              System.debug(Logginglevel.ERROR,'-- KS_OrgCliente_Util -- ----------------- JCAR - validMarca? - '
                           + marca + ' = ' + validMarcas.contains(marca));
             
             if (validMarcas.contains(marca)) {
                 String newMA = marca;// + '-' + area + '-' + delega + '-' + zona;
                 if (area != null) { newMA += '-' + area; }
                 if (delega != null) { newMA += '-' + delega; }
                 if (zona != null) { newMA += '-' + zona; }
                 
                 if (marcArea == null) { marcArea = newMA; }
                 else if (marcArea!=null && !marcArea.contains(newMA)) { marcArea += ';' + newMA; }
             }
             return marcArea;
         }
    
    global static Set<String> validMarcas() {
        List<KS_Conf_Organizacion_Cliente__mdt> orgConfLst = 
            [SELECT Id, DeveloperName, KS_Organizacion_de_ventas__c, KS_Canal_SAP__c, KS_Sector__c, KS_Lista_de_precios__c 
             FROM KS_Conf_Organizacion_Cliente__mdt];
        Set<String> validMarca = new Set<String>();
        for (KS_Conf_Organizacion_Cliente__mdt conf : orgConfLst) {
            validMarca.add(conf.KS_Organizacion_de_ventas__c 
                           + '-' + conf.KS_Canal_SAP__c
                           + '-' + conf.KS_Sector__c);
        }
        return validMarca;
    }
}