src/objects/KS_Condicion_Comercial__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Condiciones comerciales de SAP para el cálculo de precios en ofertas.</description>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <label>Canal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Canal_de_distribucion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Tipo_Sector</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Serie__c</fullName>
        <label>Serie (Global)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Serie_Gama</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Subserie__c</fullName>
        <label>Subserie</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Subserie</valueSetName>
        </valueSet>
    </fields>
    <label>Condicion Comercial</label>
    <nameField>
        <displayFormat>CC{000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones Comerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Configuracion__mdt.object
<CustomObject>
    <fields>
        <fullName>KS_Estado_Producto_Ofertable__c</fullName>
        <label>Estado Producto Ofertable</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Configuración</label>
    <pluralLabel>Configuraciones</pluralLabel>
</CustomObject>

src/objects/KS_Organizacion_Cliente__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto vinculado con las cuentas (marcas) que muestra las organizaciones de ventas para cada cliente</description>
    <fields>
        <fullName>KS_Lista_de_precios__c</fullName>
        <label>Lista de precios</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Lista_de_precios</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <label>Organización Cliente</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Nombre de Organización Cliente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizaciones Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/KS_Organizacion_Producto__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto relacional con productos que describe las características individuales de cada producto para cada org-vtas/canal (SAP)</description>
    <fields>
        <fullName>KS_Organizacion_de_Ventas__c</fullName>
        <label>Organizacion de Ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Tipo_Sector</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Subserie__c</fullName>
        <label>Subserie</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Subserie</valueSetName>
        </valueSet>
    </fields>
    <label>Organizacion Producto</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Nombre de Organizacion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizaciones Producto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Serie_Familia__c.object
<CustomObject>
    <fields>
        <fullName>KS_Org_Ventas__c</fullName>
        <label>Org. Ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SI10</fullName>
                </value>
                <value>
                    <fullName>FL31</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Serie__c</fullName>
        <label>Serie</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KS_Familia__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>C01</fullName>
                </value>
                <value>
                    <fullName>C05</fullName>
                </value>
                <value>
                    <fullName>C07</fullName>
                </value>
                <value>
                    <fullName>C10</fullName>
                </value>
                <value>
                    <fullName>C14</fullName>
                </value>
                <value>
                    <fullName>C15</fullName>
                </value>
                <value>
                    <fullName>C16</fullName>
                </value>
                <value>
                    <fullName>C17</fullName>
                </value>
                <value>
                    <fullName>C19</fullName>
                </value>
                <value>
                    <fullName>C21</fullName>
                </value>
                <value>
                    <fullName>COM</fullName>
                </value>
                <value>
                    <fullName>F00</fullName>
                </value>
                <value>
                    <fullName>I10</fullName>
                </value>
                <value>
                    <fullName>I11</fullName>
                </value>
                <value>
                    <fullName>L05</fullName>
                </value>
                <value>
                    <fullName>L10</fullName>
                </value>
                <value>
                    <fullName>L11</fullName>
                </value>
                <value>
                    <fullName>L12</fullName>
                </value>
                <value>
                    <fullName>L14</fullName>
                </value>
                <value>
                    <fullName>L15</fullName>
                </value>
                <value>
                    <fullName>L61</fullName>
                </value>
                <value>
                    <fullName>L70</fullName>
                </value>
                <value>
                    <fullName>L71</fullName>
                </value>
                <value>
                    <fullName>LIN</fullName>
                </value>
                <value>
                    <fullName>M00</fullName>
                </value>
                <value>
                    <fullName>MAD</fullName>
                </value>
                <value>
                    <fullName>S_C</fullName>
                </value>
                <value>
                    <fullName>S00</fullName>
                </value>
                <value>
                    <fullName>S01</fullName>
                </value>
                <value>
                    <fullName>S02</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Selección Serie</label>
    <nameField>
        <displayFormat>SS-{0000000}</displayFormat>
        <label>Nombre de Selección Serie</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selecciones Serie</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <formula>TEXT(KS_Organizacion_Cliente__r.KS_Canal_de_distribucion__c)</formula>
        <label>Canal</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Distribuidor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribuidor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Distribuidores</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Distribuidores_SAP</value>
            </filterItems>
            <filterItems>
                <field>Account.KS_Grupo_de_ctas_deudor__c</field>
                <operation>notEqual</operation>
                <value>Destinatarios mercancías</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ofertas (Distribuidor)</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Lista_de_precios__c</fullName>
        <formula>TEXT(KS_Organizacion_Cliente__r.KS_Lista_de_precios__c)</formula>
        <label>Lista de Precios</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Organizacion_Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marca Comercial</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>KS_Organizacion_Cliente__c.KS_Cliente_solicitante__c</field>
                <operation>equals</operation>
                <valueField>$Source.KS_Distribuidor__c</valueField>
            </filterItems>
            <filterItems>
                <field>KS_Organizacion_Cliente__c.KS_Cliente_Distribucion__c</field>
                <operation>equals</operation>
                <valueField>$Source.KS_Distribuidor__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KS_Organizacion_Cliente__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <formula>text( KS_Organizacion_Cliente__r.KS_Organizacion_de_ventas__c )</formula>
        <label>Organización de ventas (FÓRMULA)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Pais__c</fullName>
        <formula>NULLVALUE(
TEXT(KS_Distribuidor__r.ShippingCountryCode), 
TEXT(KS_Distribuidor__r.BillingCountryCode)
)</formula>
        <label>País Distribuidor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Sector__c</fullName>
        <formula>text( KS_Organizacion_Cliente__r.KS_Sector_Distribuidor__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sector</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_max_ficha__c</fullName>
        <label>Ficha máxima</label>
        <summarizedField>OpportunityLineItem.KS_Ficha__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>KS_min_ficha__c</fullName>
        <label>Ficha mínima</label>
        <summarizedField>OpportunityLineItem.KS_Ficha__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <description>VKORG</description>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Tipo_Sector</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/KS_Canal_de_distribucion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>Nacional</fullName>
        <isActive>false</isActive>
        <label>Nacional</label>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente - Jerarquia Cliente - Producto --&gt; CARGADO</description>
    <masterLabel>Canal de distribución</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Lista_de_precios.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>00</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>EC</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>PU</fullName>
    </customValue>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <customValue>
        <fullName>E0</fullName>
    </customValue>
    <customValue>
        <fullName>T0</fullName>
    </customValue>
    <customValue>
        <fullName>T1</fullName>
    </customValue>
    <customValue>
        <fullName>T2</fullName>
    </customValue>
    <customValue>
        <fullName>T3</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
    </customValue>
    <customValue>
        <fullName>B2</fullName>
    </customValue>
    <customValue>
        <fullName>B3</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente --&gt; CARGADO</description>
    <masterLabel>Lista de precios</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Organizacion_de_ventas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>FL31</fullName>
    </customValue>
    <customValue>
        <fullName>GI50</fullName>
    </customValue>
    <customValue>
        <fullName>IE20</fullName>
    </customValue>
    <customValue>
        <fullName>MA15</fullName>
    </customValue>
    <customValue>
        <fullName>MA16</fullName>
    </customValue>
    <customValue>
        <fullName>MX24</fullName>
    </customValue>
    <customValue>
        <fullName>MX25</fullName>
    </customValue>
    <customValue>
        <fullName>MX26</fullName>
    </customValue>
    <customValue>
        <fullName>SI10</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente / Jerarquia Cliente / Producto / Autorizaciones Oferta --&gt; CARGADO</description>
    <masterLabel>Organizacion de ventas</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Serie_Gama.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>S27</fullName>
    </customValue>
    <customValue>
        <fullName>S806</fullName>
    </customValue>
    <customValue>
        <fullName>S400</fullName>
    </customValue>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>018</fullName>
    </customValue>
    <customValue>
        <fullName>020</fullName>
    </customValue>
    <customValue>
        <fullName>022</fullName>
    </customValue>
    <customValue>
        <fullName>026</fullName>
    </customValue>
    <customValue>
        <fullName>027</fullName>
    </customValue>
    <customValue>
        <fullName>033</fullName>
    </customValue>
    <customValue>
        <fullName>034</fullName>
    </customValue>
    <customValue>
        <fullName>035</fullName>
    </customValue>
    <customValue>
        <fullName>036</fullName>
    </customValue>
    <customValue>
        <fullName>038</fullName>
    </customValue>
    <customValue>
        <fullName>045</fullName>
    </customValue>
    <customValue>
        <fullName>049</fullName>
    </customValue>
    <customValue>
        <fullName>051</fullName>
    </customValue>
    <customValue>
        <fullName>052</fullName>
    </customValue>
    <customValue>
        <fullName>053</fullName>
    </customValue>
    <customValue>
        <fullName>054</fullName>
    </customValue>
    <customValue>
        <fullName>056</fullName>
    </customValue>
    <customValue>
        <fullName>075</fullName>
    </customValue>
    <customValue>
        <fullName>077</fullName>
    </customValue>
    <customValue>
        <fullName>108</fullName>
    </customValue>
    <customValue>
        <fullName>110</fullName>
    </customValue>
    <customValue>
        <fullName>112</fullName>
    </customValue>
    <customValue>
        <fullName>122</fullName>
    </customValue>
    <customValue>
        <fullName>128</fullName>
    </customValue>
    <description>NOSE USA. SAP. Uso --&gt; Producto --&gt; CARGADO en SINGLE PICKLIST!!</description>
    <masterLabel>Serie/Gama</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Subserie.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>003</fullName>
    </customValue>
    <customValue>
        <fullName>004</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>009</fullName>
    </customValue>
    <customValue>
        <fullName>010</fullName>
    </customValue>
    <customValue>
        <fullName>011</fullName>
    </customValue>
    <customValue>
        <fullName>012</fullName>
    </customValue>
    <customValue>
        <fullName>013</fullName>
    </customValue>
    <customValue>
        <fullName>014</fullName>
    </customValue>
    <customValue>
        <fullName>015</fullName>
    </customValue>
    <customValue>
        <fullName>016</fullName>
    </customValue>
    <customValue>
        <fullName>017</fullName>
    </customValue>
    <customValue>
        <fullName>018</fullName>
    </customValue>
    <customValue>
        <fullName>019</fullName>
    </customValue>
    <customValue>
        <fullName>020</fullName>
    </customValue>
    <customValue>
        <fullName>021</fullName>
    </customValue>
    <customValue>
        <fullName>022</fullName>
    </customValue>
    <customValue>
        <fullName>023</fullName>
    </customValue>
    <customValue>
        <fullName>024</fullName>
    </customValue>
    <customValue>
        <fullName>025</fullName>
    </customValue>
    <customValue>
        <fullName>026</fullName>
    </customValue>
    <customValue>
        <fullName>027</fullName>
    </customValue>
    <customValue>
        <fullName>028</fullName>
    </customValue>
    <customValue>
        <fullName>029</fullName>
    </customValue>
    <customValue>
        <fullName>030</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Producto/Autorizaciones Oferta --&gt; CARGADO</description>
    <masterLabel>Subserie</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/KS_Tipo_Sector.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <customValue>
        <fullName>40</fullName>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>60</fullName>
    </customValue>
    <customValue>
        <fullName>70</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente - Jerarquia Cliente - Producto --&gt; CARGADO</description>
    <masterLabel>Tipo Sector (SAP)</masterLabel>
</GlobalValueSet>

src/classes/KS_Oferta_SearchProductos_Controller.cls
public class KS_Oferta_SearchProductos_Controller {

    public SearchKey searchKey {get;set;}
    public class SearchKey {
        
        public String name {get;set;}
        public String code {get;set;}
        public String gama {get;set;}
        public String subs {get;set;}
        public String famy {get;set;}
    }
    
    public String ofertaFicha {get;set;}
    public String idiomaActual {get;set;}
    public String letraClave  {get;set;}
    public String selectList {get;set;}
    public Boolean isPanelSelectProduct {get;set;}
    
    public String styleError {get;set;}
    public String errorTextOferta{get;set;}
    public Boolean getHaveErrorOferta() {
        return errorTextOferta!=null&&errorTextOferta!='';
    }    
    public String errorTextFicha{get;set;}
    public Boolean getHaveErrorFicha() {
        return errorTextFicha!=null&&errorTextFicha!='';
    }
    
    public Opportunity oferta {get;set;} // Objeto principal
    public KS_Serie_Familia__c seleccion {get;set;}
    
    public List<String> estadosValidos;
    
    public List<Id> lstIdProductSelect {get;set;}
    List<Product2> lstProductSelect {get;set;}
    public Map<String, String> prodSAPSF {get;set;}
    public Map<String, KS_Organizacion_Producto__c> mapOrgProducto {get;set;}
    
    public List<wrProduct> lstWrProduct {get;set;}
    public class wrProduct{ // SELECT PRODUCT
        public boolean isSelect {get; set;}
        public Product2 product {get; set;}
        public KS_Organizacion_Producto__c orgProduct {get; set;}
        
        public wrProduct(Boolean sel, Product2 prod, KS_Organizacion_Producto__c orgProd){
            isSelect = sel;
            product = prod;
            orgProduct = orgProd;
        }
    }
    
    public Map<Id,Product2> mapIdProductSelect {get;set;}
    public Boolean getHaveSelected() {
        return !mapIdProductSelect.isEmpty();
    }
    
    public String selectAddRow {get;set;}
    public String selectAddProd {get;set;}
    public Integer ofertaFilas {get;set;}
    
    public Boolean searchProds {get;set;}
    
    public KS_Oferta_SearchProductos_Controller(ApexPages.StandardController controller) {
        
        searchKey = new SearchKey();
        
        searchKey.code = ApexPages.currentPage().getParameters().get('codProducto');
        selectAddRow = ApexPages.currentPage().getParameters().get('rowProducto');
        selectAddProd = ApexPages.currentPage().getParameters().get('idProducto');
        ofertaFilas = selectAddRow != null ? selectAddRow.length(): 0;
        ofertaFicha = ApexPages.currentPage().getParameters().get('ficha');
        searchProds = false;
        
        System.debug('-- JCAR ---------------------------------- KS_Oferta_SearchProductos_Controller - selectAddRow : ' + selectAddRow );
        System.debug('-- JCAR ---------------------------------- KS_Oferta_SearchProductos_Controller - ofertaFilas : ' + ofertaFilas );
        System.debug('-- JCAR ---------------------------------- KS_Oferta_SearchProductos_Controller - ofertaFicha : ' + ofertaFicha );
        
        seleccion = new KS_Serie_Familia__c();
        
        oferta = (Opportunity)controller.getRecord();
        if (oferta.ID != null) {
            
            oferta = [SELECT ID, Name, Pricebook2Id, KS_Organizacion_de_ventas__c, KS_Canal__c, KS_Sector__c,
                      KS_max_ficha__c, KS_min_ficha__c, KS_Pais__c, KS_Organizacion_Cliente__c, KS_Lista_de_precios__c, KS_Distribuidor__c 
                      FROM Opportunity WHERE ID = :oferta.ID ];
            isPanelSelectProduct = true;
            mapIdProductSelect = new Map<Id,Product2>();
            styleError = 'error';
            String idioma = userInfo.getLanguage();
            idiomaActual = idioma.split('_')[0];
            System.debug('----------------------------------------SERG - idiomaActual : ' + idiomaActual );
            
            seleccion.KS_Org_ventas__c = oferta.KS_Organizacion_de_ventas__c;
        }       
        
        estadosValidos = new List<String>();
        List<KS_Configuracion__mdt> confLst = [SELECT KS_Estado_Producto_Ofertable__c FROM KS_Configuracion__mdt WHERE DeveloperName = 'CONF'];
        KS_Configuracion__mdt conf = null;
        if (confLst.size()>0) { 
            conf = confLst[0]; 
            estadosValidos.addAll(conf.KS_Estado_Producto_Ofertable__c.split(';'));
        }
        
        lstWrProduct = new List<wrProduct>();
    }
    
    
    
    //////////////////////////////////////////////////////////////////////////////////////////
    ///  PANEL SELECT PRODUCT                                                              ///
    //////////////////////////////////////////////////////////////////////////////////////////
    public ApexPages.StandardSetController setCon {
        get {
            if (setCon == null && searchProds) {
                
                String palabraClaveTemp;
                String codigoClaveTemp;
                String serieClaveTemp; searchKey.gama = seleccion.KS_Serie__c;
                String subserieClaveTemp; searchKey.subs = seleccion.KS_Subserie__c;
                String familiaClaveTemp; searchKey.famy = seleccion.KS_Familia__c;
                
                if(letraClave==null) {
                    palabraClaveTemp = '%' + ( searchKey.name!=null ? searchKey.name : '' ) + '%';
                } else {
                    palabraClaveTemp = letraClave + '%';
                    letraClave = null;
                }
                
                codigoClaveTemp = '%' + ( searchKey.code!=null ? searchKey.code : '' ) + '%';
                serieClaveTemp = '%' + ( searchKey.gama!=null ? searchKey.gama : '' ) + '%';
                subserieClaveTemp = '%' + ( searchKey.subs!=null ? searchKey.subs : '' ) + '%';
                familiaClaveTemp = '%' + ( searchKey.famy!=null ? searchKey.famy : '' ) + '%';
                
                palabraClaveTemp = palabraClaveTemp.replace('*', '%'); 
                codigoClaveTemp = codigoClaveTemp.replace('*', '%');
                
                System.debug('-- JCAR ---------------------------------- - SELECT product2 - ' + setCon);

				String canal = oferta.KS_Canal__c != null ? oferta.KS_Canal__c : '10';
                List<String> materiales = new List<String>();
                Set<String> IDproductos = new Set<String>();
                List<KS_Condicion_Comercial__c> condiciones = [SELECT Id, KS_Tarifa__c, KS_Material__c, KS_Condicion__c, KS_Importe__c, KS_Cliente_Jerarquia__c
                                                               FROM KS_Condicion_Comercial__c WHERE KS_Material__c != null 
                                                               AND (
                                                                   (KS_Condicion__c = 'PR00' 
                                                                    AND KS_Tarifa__c = :oferta.KS_Lista_de_precios__c
                                                                    AND KS_Canal__c = :canal
                                                                    AND KS_Sector__c = :oferta.KS_Sector__c
                                                                   )
                                                                    OR (KS_Condicion__c = null AND KS_Tarifa__c = NULL 
                                                                        AND KS_CountryCode__c = :oferta.KS_Pais__c 
                                                                        AND KS_Canal__c = '20')
                                                                   )
                                                               ];
                System.debug('-- JCAR ---------------------------------- - SELECT ' + condiciones.size() + ' condiciones - ' + condiciones);
                for (KS_Condicion_Comercial__c con : condiciones) {
                    IDproductos.add(con.KS_Material__c);
                }
                
                mapOrgProducto = new Map<String, KS_Organizacion_Producto__c>();
                List<KS_Organizacion_Producto__c> orgProductos = [SELECT ID, KS_Producto__c, KS_Familia__c, KS_Subserie__c, KS_Serie_Gama__c
                                                                  FROM KS_Organizacion_Producto__c 
                                                                  WHERE KS_Canal_de_distribucion__c = :canal 
                                                                  AND KS_Sector__c = :oferta.KS_Sector__c
                                                                  AND KS_Producto__c in :IDproductos
                                                                  AND KS_Estatus_Comercial__c in :estadosValidos
                                                                  AND KS_Organizacion_de_Ventas__c = :oferta.KS_Organizacion_de_ventas__c];
                System.debug('-- JCAR ---------------------------------- - SELECT ' + orgProductos.size() + ' orgProductos - ' + orgProductos);
                for (KS_Organizacion_Producto__c orgP : orgProductos) {
                    //System.debug('-- JCAR ---------------------------------- - PRODUCTO: ' + orgP.KS_Producto__c);
                    
                    if (seleccion.KS_Familia__c != null && (seleccion.KS_Familia__c == orgP.KS_Familia__c || seleccion.KS_Familia__c == '---') ) {
                        
                        if (seleccion.KS_Serie__c != null && seleccion.KS_Serie__c == orgP.KS_Serie_Gama__c) {
                            
                            if (seleccion.KS_Subserie__c != null && seleccion.KS_Subserie__c == orgP.KS_Subserie__c) {
                                
                                materiales.add(orgP.KS_Producto__c);
                                mapOrgProducto.put(orgP.KS_Producto__c, orgP);
                            
                            } else if (seleccion.KS_Subserie__c == null) {
                                
                                materiales.add(orgP.KS_Producto__c);
                                mapOrgProducto.put(orgP.KS_Producto__c, orgP);
                            }
                            
                        } else if (seleccion.KS_Serie__c == null && seleccion.KS_Subserie__c == null) {
                            
                            materiales.add(orgP.KS_Producto__c);
                            mapOrgProducto.put(orgP.KS_Producto__c, orgP);
                        }

                    } else if (seleccion.KS_Serie__c == null && seleccion.KS_Subserie__c == null && seleccion.KS_Familia__c == null) {
                        
                        materiales.add(orgP.KS_Producto__c);
                        mapOrgProducto.put(orgP.KS_Producto__c, orgP);
                    }
                }
                

                System.debug('--------------------------------serg - palabraClave: ' + palabraClaveTemp + ' - ' + codigoClaveTemp + ' - ' + serieClaveTemp + ' - ' + subserieClaveTemp + ' - ' + familiaClaveTemp);
                
                String name = searchKey.name != null ? searchKey.name : '';
                String code = searchKey.code != null ? searchKey.code : '';
                name = name.replace('*', '%');
                code = code.replace('*', '%');
                
                List<String> nombres = name.split(';');
                List<String> codigos = code.split(';');
                
                System.debug('-- JCAR ---------------------------------- - SEARCHKEY ' + nombres.size() + ' nombres - ' + nombres);
                System.debug('-- JCAR ---------------------------------- - SEARCHKEY ' + codigos.size() + ' codigos - ' + codigos);
                
                String productosQRY = 'select id, Name, ProductCode, Family, KS_Id_SAP__c, KS_Tipo_de_material__c, KS_Nombre_Producto__c, KS_Descripcion_corta__c, isActive';
                productosQRY += ' from Product2 where id in :materiales AND isActive = true';
                
                if (nombres.size()>1) 
                {
                    Integer index = 0;
                    while (index < nombres.size()) {
                        
                        String nameS = '%' + nombres[index] + '%';
                        if (index == 0) {
                            productosQRY += ' AND ( (KS_Nombre_Producto__c like \''+nameS+'\'';
                            productosQRY += ' OR KS_Descripcion_corta__c like \''+nameS+'\')';
                        } else {
                            productosQRY += ' OR (KS_Nombre_Producto__c like \''+nameS+'\'';
                            productosQRY += ' OR KS_Descripcion_corta__c like \''+nameS+'\')';
                        }
                        
                        index++;
                    }
                    productosQRY += ' )';
                }
                else 
                { 
                    String nameS = '%' + nombres[0] + '%';
                    productosQRY += ' and (KS_Nombre_Producto__c like \''+nameS+'\'';
                    productosQRY += ' OR KS_Descripcion_corta__c like \''+nameS+'\')';
                }
                
                if (codigos.size()>1) 
                { 
                    Integer index = 0;
                    while (index < codigos.size()) {
                        
                        String codeS = '%' + codigos[index] + '%';
                        if (index == 0) {
                            productosQRY += ' AND ( KS_Id_SAP__c like \''+codeS+'\'';
                        } else {
                            productosQRY += ' OR KS_Id_SAP__c like \''+codeS+'\'';                           
                        }
                        
                        index++;
                    }
                    productosQRY += ' )';
                }
                else 
                { 
                    String codeS = '%' + codigos[0] + '%';
                    productosQRY += ' AND KS_Id_SAP__c like \''+codeS+'\'';
                }                

                productosQRY += ' order by KS_Nombre_Producto__c limit 4000';
                
                System.debug('-- JCAR ---------------------------------- - STRING productosQRY - ' + productosQRY);

                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(productosQRY));
                setCon.setpageSize(25);
            
                System.debug('-- JCAR ---------------------------------- - SELECT product2 - ' + setCon);
                
                Map<String, KS_Organizacion_Producto__c> mapOrgProductoTMP = new Map<String, KS_Organizacion_Producto__c>();
                List<Product2> lstProd = (List<Product2>) setCon.getRecords();
                for(Product2 prod : lstProd) {
                    if (mapOrgProducto.containsKey(prod.ID)) {
                        mapOrgProductoTMP.put(prod.ID, mapOrgProducto.get(prod.ID));
                    }
                }
                mapOrgProducto = mapOrgProductoTMP;
            }
            return SetCon;
        }
        set;       
    }  

    public List<wrProduct> getProductos() {
        
        List<Product2> lstProd = (List<Product2>) setCon.getRecords();
        mapOrgProducto = new Map<String, KS_Organizacion_Producto__c>();
        
        List<ID> prodIDLst = new List<ID>();
        for(Product2 prod : lstProd) { prodIDLst.add(prod.ID); }
        String canal = oferta.KS_Canal__c != null ? oferta.KS_Canal__c : '10';
        List<KS_Organizacion_Producto__c> orgProductos = [SELECT ID, KS_Producto__c, KS_Familia__c, KS_Subserie__c, KS_Serie_Gama__c
                                                          FROM KS_Organizacion_Producto__c WHERE KS_Canal_de_distribucion__c = :canal 
                                                          AND KS_Producto__c in :prodIDLst
                                                          AND KS_Estatus_Comercial__c in :estadosValidos
                                                          AND KS_Organizacion_de_Ventas__c = :oferta.KS_Organizacion_de_ventas__c];        
        for (KS_Organizacion_Producto__c oP : orgProductos) { mapOrgProducto.put(oP.KS_Producto__c, oP); }
        
        lstWrProduct = new List<wrProduct>();
        for(Product2 prod : lstProd) {
            
            KS_Organizacion_Producto__c orgProd = new KS_Organizacion_Producto__c();
            if (mapOrgProducto.containsKey(prod.ID)) {
                orgProd = mapOrgProducto.get(prod.ID);
            }
            wrProduct wrProd;
            
            if(mapIdProductSelect.get(prod.Id)!=null) {
                wrProd = new wrProduct(true, prod, orgProd);
            } else {
                wrProd = new wrProduct(false, prod, orgProd);
            }
            lstWrProduct.add(wrProd);
        }
        return lstWrProduct;
    }
    
    public void getProductosFilter(){
        for(wrProduct wp : lstWrProduct)                
            if(wp.isSelect && mapIdProductSelect.get(wp.product.Id)==null)
                mapIdProductSelect.put(wp.product.Id, wp.product);
        searchProds = true;
        setcon = null;
        getProductos();
    }
    
    public void saveProdSelect_Next(){
        //Guardamos Id de Productos seleccionados
        for(wrProduct wp : lstWrProduct) {   
            if(wp.isSelect && mapIdProductSelect.get(wp.product.Id)==null) {
                mapIdProductSelect.put(wp.product.Id, wp.product); } 
            if(!wp.isSelect && mapIdProductSelect.get(wp.product.Id)!=null) {
                mapIdProductSelect.remove(wp.product.ID); }
        }
        setCon.next();
    }
    
    public void saveProdSelect_Previous(){
        //Guardamos Id de Productos seleccionados
        for(wrProduct wp : lstWrProduct) 
            if(wp.isSelect && mapIdProductSelect.get(wp.product.Id)==null) 
                mapIdProductSelect.put(wp.product.Id, wp.product);

        setCon.previous();
    }
    
    public PageReference cancel() {
        PageReference pg = null;
        if (oferta != null && oferta.ID != null) {
            pg = new PageReference('/' + oferta.ID);
            if (selectAddRow != null && selectAddRow.trim() != '') {
                pg = backToAddProductos(false);
            }
        } else {
            pg = new PageReference('/');
        }
        if (pg!=null) {pg.setRedirect(true);}
        return pg;
    }
    
    public PageReference selProducto() {
        PageReference pg = null;
        if (oferta != null && oferta.ID != null) {
            pg = new PageReference('/' + oferta.ID);
            if (selectAddRow != null && selectAddRow.trim() != '') {
                pg = backToAddProductos(true);
            }
        } else {
            pg = new PageReference('/');
        }
        if (pg!=null) {pg.setRedirect(true);}
        return pg;
    }
    
    private PageReference backToAddProductos(Boolean sendIDProd) {
        return new PageReference(
            '/apex/KS_Oferta_AddProductos?' 
            + 'id='+oferta.ID
            + '&rowProducto='+selectAddRow
            + (sendIDProd ? '&idProducto='+selectAddProd : '')
            + '&ficha='+ofertaFicha
            + '&fichaLineas='+selectAddRow.length());
    }
}