src/objects/KS_Condicion_de_Obra__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Recoge las condiciones de obra surgidas de cada oferta</description>
    <fields>
        <fullName>KS_Aprobado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Aprobado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Dto_adicional_2__c</fullName>
        <label>Extra</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>KS_Familia__c</fullName>
        <label>Familia</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Familia</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Nivel2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Nivel2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Nivel3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Nivel3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Nivel4__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Nivel4</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Oportunidad__c</fullName>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Condiciones de Obra</relationshipLabel>
        <relationshipName>Condiciones_de_Obra</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>KS_Resp_Conectividad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resp.Conectividad</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Condiciones_de_Obra</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Resp_Iluminacion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resp.Iluminación</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Condiciones_de_Obra1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Resp_Jefe_de_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resp. Jefe de Area</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Condiciones_de_Obra2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Resp_Negocio_Iberia_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resp.Negocio Iberia 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Condiciones_de_Obra8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Resp_Negocio_Iberia__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resp.Negocio Iberia</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Condiciones_de_Obra3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Resp_Resto_de_gamas__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resp.Resto de gamas</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Condiciones_de_Obra4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Resp_Sist_Control__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resp.Sist.Control</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Condiciones_de_Obra5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Resp_Vehiculo_Electrico__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resp.Vehículo Eléctrico</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Condiciones_de_Obra6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Serie__c</fullName>
        <label>Serie</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>001</fullName>
                </value>
                <value>
                    <fullName>008</fullName>
                </value>
                <value>
                    <fullName>018</fullName>
                </value>
                <value>
                    <fullName>020</fullName>
                </value>
                <value>
                    <fullName>022</fullName>
                </value>
                <value>
                    <fullName>026</fullName>
                </value>
                <value>
                    <fullName>027</fullName>
                </value>
                <value>
                    <fullName>033</fullName>
                </value>
                <value>
                    <fullName>034</fullName>
                </value>
                <value>
                    <fullName>035</fullName>
                </value>
                <value>
                    <fullName>036</fullName>
                </value>
                <value>
                    <fullName>038</fullName>
                </value>
                <value>
                    <fullName>045</fullName>
                </value>
                <value>
                    <fullName>049</fullName>
                </value>
                <value>
                    <fullName>051</fullName>
                </value>
                <value>
                    <fullName>052</fullName>
                </value>
                <value>
                    <fullName>053</fullName>
                </value>
                <value>
                    <fullName>054</fullName>
                </value>
                <value>
                    <fullName>056</fullName>
                </value>
                <value>
                    <fullName>075</fullName>
                </value>
                <value>
                    <fullName>077</fullName>
                </value>
                <value>
                    <fullName>108</fullName>
                </value>
                <value>
                    <fullName>110</fullName>
                </value>
                <value>
                    <fullName>112</fullName>
                </value>
                <value>
                    <fullName>122</fullName>
                </value>
                <value>
                    <fullName>128</fullName>
                </value>
                <value>
                    <fullName>129</fullName>
                </value>
                <value>
                    <fullName>131</fullName>
                </value>
                <value>
                    <fullName>134</fullName>
                </value>
                <value>
                    <fullName>135</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Subserie__c</fullName>
        <label>Subserie</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Subserie</valueSetName>
        </valueSet>
    </fields>
    <label>Condicion de Obra</label>
    <nameField>
        <displayFormat>IdCO-{0000000}</displayFormat>
        <label>id condicion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones de Obra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KS_Condicion_de_obra_publico__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Hace de dominio público los detalles genéricos de una condición de obra</description>
    <fields>
        <fullName>KS_Serie__c</fullName>
        <label>Serie</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Condición de obra</label>
    <nameField>
        <displayFormat>COO-{00000}</displayFormat>
        <label>COO-id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones de obra</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Obra__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Es el objeto superior que agrega las ofertas (oportunidades)</description>
    <fields>
        <fullName>KS_Condicion_de_obra__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Condición de obra</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Pais__c</fullName>
        <label>País</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ISOCountryCodes</valueSetName>
        </valueSet>
    </fields>
    <label>Obra</label>
    <nameField>
        <label>Nombre de Obra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Obras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Organizacion_Cliente__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto vinculado con las cuentas (marcas) que muestra las organizaciones de ventas para cada cliente</description>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <label>Organización Cliente</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Nombre de Organización Cliente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizaciones Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>KS_Aprobado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Aprobado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <formula>TEXT(KS_Organizacion_Cliente__r.KS_Canal_de_distribucion__c)</formula>
        <label>Canal</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Nivel2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Nivel2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Nivel3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Nivel3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Nivel4__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Nivel4</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <formula>text( KS_Organizacion_Cliente__r.KS_Organizacion_de_ventas__c )</formula>
        <label>Organización de ventas (FÓRMULA)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Pais__c</fullName>
        <formula>NULLVALUE(
TEXT(KS_Distribuidor__r.ShippingCountryCode), 
TEXT(KS_Distribuidor__r.BillingCountryCode)
)</formula>
        <label>País Distribuidor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Resp_Conectividad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resp.Conectividad</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Oportunidades1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Resp_Iluminacion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resp.Iluminación</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Resp_Jefe_de_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resp. Jefe de Area</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Oportunidades6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Resp_Negocio_Iberia_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resp.Negocio Iberia 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Oportunidades7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Resp_Sist_Control__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resp.Sist.Control</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Oportunidades2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Resp_Vehiculo_Electrico__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resp.Vehículo Eléctrico</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Oportunidades3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Resp_negocio_iberia__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resp.Negocio Iberia</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Oportunidades5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Resp_resto_de_gamas__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resp.Resto de gamas</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Oportunidades4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Sector__c</fullName>
        <formula>text( KS_Organizacion_Cliente__r.KS_Sector_Distribuidor__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sector</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Territory2.object
<CustomObject>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Canal__c</fullName>
        <label>Canal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Canal_de_distribucion</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/globalValueSets/ISOCountryCodes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AS</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BQ</fullName>
    </customValue>
    <description>EN USO --&gt; Estructuras geográficas / Autorizaciones Ofertas</description>
    <masterLabel>ISOCountryCodes</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Area.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1010</fullName>
    </customValue>
    <customValue>
        <fullName>1020</fullName>
    </customValue>
    <customValue>
        <fullName>1021</fullName>
    </customValue>
    <customValue>
        <fullName>1030</fullName>
    </customValue>
    <customValue>
        <fullName>1040</fullName>
    </customValue>
    <customValue>
        <fullName>1050</fullName>
    </customValue>
    <customValue>
        <fullName>1060</fullName>
    </customValue>
    <customValue>
        <fullName>INTE</fullName>
    </customValue>
    <description>SAP. IDs SAP de Área</description>
    <masterLabel>Área</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Canal_de_distribucion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>Nacional</fullName>
        <isActive>false</isActive>
        <label>Nacional</label>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente - Jerarquia Cliente - Producto --&gt; CARGADO</description>
    <masterLabel>Canal de distribución</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Familia.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>B00</fullName>
    </customValue>
    <customValue>
        <fullName>B01</fullName>
    </customValue>
    <customValue>
        <fullName>B02</fullName>
    </customValue>
    <customValue>
        <fullName>B03</fullName>
    </customValue>
    <customValue>
        <fullName>B04</fullName>
    </customValue>
    <customValue>
        <fullName>B05</fullName>
    </customValue>
    <customValue>
        <fullName>B06</fullName>
    </customValue>
    <customValue>
        <fullName>C00</fullName>
    </customValue>
    <customValue>
        <fullName>C01</fullName>
    </customValue>
    <customValue>
        <fullName>C02</fullName>
    </customValue>
    <customValue>
        <fullName>C03</fullName>
    </customValue>
    <customValue>
        <fullName>C04</fullName>
    </customValue>
    <customValue>
        <fullName>C05</fullName>
    </customValue>
    <customValue>
        <fullName>C06</fullName>
    </customValue>
    <customValue>
        <fullName>C07</fullName>
    </customValue>
    <customValue>
        <fullName>C08</fullName>
    </customValue>
    <customValue>
        <fullName>C09</fullName>
    </customValue>
    <customValue>
        <fullName>C10</fullName>
    </customValue>
    <customValue>
        <fullName>C11</fullName>
    </customValue>
    <customValue>
        <fullName>C12</fullName>
    </customValue>
    <customValue>
        <fullName>C13</fullName>
    </customValue>
    <customValue>
        <fullName>C14</fullName>
    </customValue>
    <customValue>
        <fullName>C15</fullName>
    </customValue>
    <customValue>
        <fullName>C16</fullName>
    </customValue>
    <customValue>
        <fullName>C17</fullName>
    </customValue>
    <customValue>
        <fullName>C18</fullName>
    </customValue>
    <customValue>
        <fullName>C19</fullName>
    </customValue>
    <customValue>
        <fullName>C20</fullName>
    </customValue>
    <customValue>
        <fullName>C21</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Producto / Autorizaciones Oferta --&gt; CARGADO</description>
    <masterLabel>Familia</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/globalValueSets/KS_Organizacion_de_ventas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>FL31</fullName>
    </customValue>
    <customValue>
        <fullName>GI50</fullName>
    </customValue>
    <customValue>
        <fullName>IE20</fullName>
    </customValue>
    <customValue>
        <fullName>MA15</fullName>
    </customValue>
    <customValue>
        <fullName>MA16</fullName>
    </customValue>
    <customValue>
        <fullName>MX24</fullName>
    </customValue>
    <customValue>
        <fullName>MX25</fullName>
    </customValue>
    <customValue>
        <fullName>MX26</fullName>
    </customValue>
    <customValue>
        <fullName>SI10</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente / Jerarquia Cliente / Producto / Autorizaciones Oferta --&gt; CARGADO</description>
    <masterLabel>Organizacion de ventas</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Subserie.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>001</fullName>
    </customValue>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>003</fullName>
    </customValue>
    <customValue>
        <fullName>004</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>009</fullName>
    </customValue>
    <customValue>
        <fullName>010</fullName>
    </customValue>
    <customValue>
        <fullName>011</fullName>
    </customValue>
    <customValue>
        <fullName>012</fullName>
    </customValue>
    <customValue>
        <fullName>013</fullName>
    </customValue>
    <customValue>
        <fullName>014</fullName>
    </customValue>
    <customValue>
        <fullName>015</fullName>
    </customValue>
    <customValue>
        <fullName>016</fullName>
    </customValue>
    <customValue>
        <fullName>017</fullName>
    </customValue>
    <customValue>
        <fullName>018</fullName>
    </customValue>
    <customValue>
        <fullName>019</fullName>
    </customValue>
    <customValue>
        <fullName>020</fullName>
    </customValue>
    <customValue>
        <fullName>021</fullName>
    </customValue>
    <customValue>
        <fullName>022</fullName>
    </customValue>
    <customValue>
        <fullName>023</fullName>
    </customValue>
    <customValue>
        <fullName>024</fullName>
    </customValue>
    <customValue>
        <fullName>025</fullName>
    </customValue>
    <customValue>
        <fullName>026</fullName>
    </customValue>
    <customValue>
        <fullName>027</fullName>
    </customValue>
    <customValue>
        <fullName>028</fullName>
    </customValue>
    <customValue>
        <fullName>029</fullName>
    </customValue>
    <customValue>
        <fullName>030</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Producto/Autorizaciones Oferta --&gt; CARGADO</description>
    <masterLabel>Subserie</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/KS_Condicion_Obra_Trigger.cls
public without sharing class KS_Condicion_Obra_Trigger extends KS_TriggerController {

    public KS_Condicion_Obra_Trigger (Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate,
        List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems)
    {
        super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);
    }
    
    public static Boolean blocked() { System.debug('-- TRIGGER BLOCKED! --'); return Test.isRunningTest() && KS_Trigger_Test.blockTrigger; }
    
    protected override void runBeforeInsert(){ if(blocked()){return;} executeBeforeInsert(); }
    protected override void runBeforeUpdate(){ if(blocked()){return;} executeBeforeUpdate(); } 
    public void executeBeforeInsert() { executeBeforeUpsert(); }
    public void executeBeforeUpdate() { executeBeforeUpsert(); }       
    public void executeBeforeUpsert() {
        
        List<KS_Condicion_de_Obra__c> condicionesLst = (List<KS_Condicion_de_Obra__c>)lstNewItems;
        List<KS_Condicion_de_Obra__c> condiciones = new List<KS_Condicion_de_Obra__c>();
        Map<ID, Opportunity> ofertas = new Map<ID, Opportunity>();
        
        List<ID> ofertasID = new List<ID>();
        List<String> clavesSerieFamilia = new List<String>();
        
        Set<String> serieSet = new Set<String>(); List<String> series = new List<String>();
        Set<String> subserieSet = new Set<String>(); List<String> subseries = new List<String>();
        Set<String> familiaSet = new Set<String>(); List<String> familias = new List<String>();        
        
        Map<String,Set<ID>> mapElementos = new Map<String,Set<ID>>();
        Map<String,Decimal> mapDescuentos = new Map<String,Decimal>();   
        
        for (KS_Condicion_de_Obra__c co : condicionesLst) {
            if (!co.KS_Aprobado__c) {
                
                if (co.KS_Dto_adicional_2__c != null && co.KS_Dto_adicional_2__c > 0) {
                    
                    String clave = ''; // Serie+Subserie+Familia
                    clave += co.KS_Serie__c != null ? co.KS_Serie__c : '';
                    clave += co.KS_Subserie__c != null ? co.KS_Subserie__c : '';
                    clave += co.KS_Familia__c != null ? co.KS_Familia__c : '';
                    
                    if (co.KS_Serie__c != null) { serieSet.add(co.KS_Serie__c); }
                    if (co.KS_Subserie__c != null) { subserieSet.add(co.KS_Subserie__c); }
                    if (co.KS_Familia__c != null) { familiaSet.add(co.KS_Familia__c); }
                    
                    Decimal dtoad2 = mapDescuentos.containsKey(clave) ? mapDescuentos.get(clave) : 0;
                    dtoad2 = co.KS_Dto_adicional_2__c > dtoad2 ? co.KS_Dto_adicional_2__c : dtoad2;
                    mapDescuentos.put(clave, dtoad2);
                    
                    Set<ID> conSet = new Set<ID>();
                    if (mapElementos.containsKey(clave))
                    { conSet = mapElementos.get(clave); }
                    conSet.add(co.ID); mapElementos.put(clave, conSet);
                    
                    clavesSerieFamilia.add(clave);
                    ofertasID.add(co.KS_Oportunidad__c);
                    ofertas.put(co.KS_Oportunidad__c, null);
                    
                    co.KS_Nivel2__c = false; co.KS_Nivel3__c = false; co.KS_Nivel4__c = false;
                    co.KS_Resp_Conectividad__c = null; co.KS_Resp_Iluminacion__c = null;
                    co.KS_Resp_Jefe_de_Area__c = null; co.KS_Resp_Negocio_Iberia_2__c = null;
                    co.KS_Resp_negocio_iberia__c = null; co.KS_Resp_resto_de_gamas__c = null;
                    co.KS_Resp_Sist_Control__c = null; co.KS_Resp_Vehiculo_Electrico__c = null;
                    condiciones.add(co);
                }
                
            }
        }

        Map<ID,String> paisesMap = new Map<ID,String>();
        Map<ID,String> orgVentas = new Map<ID,String>();
        Map<ID,ID> orgClientes = new Map<ID,ID>();
        List<String> marcaLST = new List<String>();
		
        List<Opportunity> oppLst = [SELECT ID, KS_Organizacion_de_Ventas__c, KS_Canal__c, KS_Pais__c, 
                                    KS_Sector__c, KS_Area__c, KS_Organizacion_Cliente__c, Territory2Id
                                    FROM Opportunity WHERE ID IN :ofertasID];
        for (Opportunity opp : oppLst) {
            
            ofertas.put(opp.ID, opp);
            orgVentas.put(opp.ID, opp.KS_Organizacion_de_Ventas__c);
            paisesMap.put(opp.ID, opp.KS_Pais__c);
            orgClientes.put(opp.ID, opp.KS_Organizacion_Cliente__c);
            marcaLST.add(opp.KS_Organizacion_Cliente__c);
        }
               
        System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + ofertas.size() + ' ofertas - ' + ofertas);

        Map<ID,ID> responsables = new Map<ID,ID>();
        
        List<KS_Organizacion_Cliente__c> orgClLst = [SELECT ID,KS_Responsable__c FROM KS_Organizacion_Cliente__c
                                                     WHERE ID in :marcaLST];
        for (KS_Organizacion_Cliente__c oc : orgClLst) {
            for (ID oppID : orgClientes.keySet()) {
                ID ocID = orgClientes.get(oppID);
                if (oc.ID == ocID && oc.KS_Responsable__c != null)  {
                    responsables.put(oppID , oc.KS_Responsable__c);
                }
            }
        }
        
        if (responsables.size() < ofertas.size()) {

            Map<ID,Opportunity> oppSinTerr = new Map<ID,Opportunity>();
            
            List<String> orgVnLST = new List<String>();
            List<String> canalLST = new List<String>();
            List<String> sectrLST = new List<String>();
            List<String> areaGLst = new List<String>();
            MAP<ID,ID> terrMAP = new MAP<ID,ID>();
            
            for (ID oppID : ofertas.keyset()) {
                
                if (!responsables.containsKey(oppID)) {
                    
                    Opportunity opp = ofertas.get(oppID);
                    oppSinTerr.put(opp.ID, opp);
                    
                    terrMAP.put(opp.Territory2Id, opp.ID);
                    
                    orgVnLST.add(opp.KS_Organizacion_de_Ventas__c);
                    canalLST.add(opp.KS_Canal__c);
                    sectrLST.add(opp.KS_Sector__c);
                    areaGLst.add(opp.KS_Area__c);                     
                }
               
            }
            
            List<ID> terrID = new List<ID>(); terrID.addAll(terrMAP.keySet());
            
            Map<String,ID> terrType = new Map<String,ID>();
            List<Territory2Type> terrLst = [SELECT ID, DeveloperName FROM Territory2Type];
            for (Territory2Type tp : terrLst) {
                terrType.put(tp.DeveloperName, tp.ID);
            }  
            
            System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + terrType.size() + ' terrType - ' + terrType);             
            System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + orgVnLST.size() + ' orgVnLST - ' + orgVnLST);
            System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + canalLST.size() + ' canalLST - ' + canalLST);
            System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + sectrLST.size() + ' sectrLST - ' + sectrLST);
            System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + areaGLst.size() + ' areaGLst - ' + areaGLst);
            System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + terrMAP.size() + ' terrMAP - ' + terrMAP);
            
            List<UserTerritory2Association> terrOferta = 
                [SELECT Id, UserId, Territory2Id, RoleInTerritory2,
                 Territory2.KS_Organizacion_Ventas__c,
                 Territory2.KS_Canal__c,
                 Territory2.KS_Sector_Distribuidor__c,
                 Territory2.KS_Area__c
                 FROM UserTerritory2Association 
                 WHERE RoleInTerritory2 = 'JAR'
                 AND Territory2.KS_Organizacion_Ventas__c IN :orgVnLST
                 AND Territory2.KS_Canal__c IN :canalLST
                 AND Territory2.KS_Sector_Distribuidor__c IN :sectrLST
                 AND Territory2.KS_Area__c IN :areaGLst
                 AND Territory2.Territory2TypeId = :terrType.get('KS_Area')
                ];
            System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + terrOferta.size() + ' terrOferta - ' + terrOferta);
            for (Opportunity opp : oppSinTerr.values()) {
                for (UserTerritory2Association uta : terrOferta) {
                    if (uta.Territory2.KS_Organizacion_Ventas__c == opp.KS_Organizacion_de_Ventas__c
                        && uta.Territory2.KS_Canal__c == opp.KS_Canal__c
                        && uta.Territory2.KS_Sector_Distribuidor__c == opp.KS_Sector__c
                        && uta.Territory2.KS_Area__c == opp.KS_Area__c) {
                            
                            responsables.put(opp.ID , uta.UserId);
                        }
                }
            }            
        }
        
        series.addAll(serieSet);
        subseries.addAll(subSerieSet);
        familias.addAll(familiaSet);        
        
        System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + mapDescuentos.size() + ' mapDescuentos - ' + mapDescuentos);
        System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + mapElementos.size() + ' mapElementos - ' + mapElementos);
        System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + responsables.size() + ' responsables - ' + responsables);
        System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + condiciones.size() + ' condiciones - ' + condiciones);
        System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + ofertas.values().size() + ' ofertas.values() - ' + ofertas.values());
        System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + orgVentas.size() + ' orgVentas - ' + orgVentas);
        System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + clavesSerieFamilia.size() + ' clavesSerieFamilia - ' + clavesSerieFamilia);
        System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + series.size() + ' series - ' + series);
        System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + subseries.size() + ' subseries - ' + subseries);
        System.debug('-- JCAR ---------------------------------- Opp.executeBeforeUpsert - ' + familias.size() + ' familias - ' + familias);
        
        if (mapDescuentos.size() > 0) {
            KS_Aprobaciones_Controller.setAprobacionesOferta(mapDescuentos, null, mapElementos, responsables, condiciones, ofertas.values(), orgVentas, clavesSerieFamilia,
                                                             subseries, series, familias, paisesMap);
        }
    }    
    
    protected override void  runAfterUpdate(){ executeAfterUpdate(); }
    public void executeAfterUpdate() {
        
        List<KS_Condicion_de_Obra__c> condiciones = (List<KS_Condicion_de_Obra__c>)lstNewItems;
        List<KS_Condicion_de_Obra__c> condicionesAprobadas = new List<KS_Condicion_de_Obra__c>();
        Map<ID, Set<String>> obrasAprobadas = new Map<ID, Set<String>>();        
        
        for (KS_Condicion_de_Obra__c co : condiciones) {
            if (co.KS_Aprobado__c && co.KS_Obra__c != null && co.KS_Oportunidad__c != null && co.KS_Organizacion_Ventas__c != null) {
                condicionesAprobadas.add(co);
                
                Set<String> orgVentasAprob = new Set<String>();
                if ( obrasAprobadas.containsKey(co.KS_Obra__c) ) { orgVentasAprob = obrasAprobadas.get(co.KS_Obra__c); }
                orgVentasAprob.add(co.KS_Organizacion_Ventas__c);
                obrasAprobadas.put(co.KS_Obra__c, orgVentasAprob);
            }
        }
        
        Map<ID, KS_Obra__c> obrasUpdate = new Map<ID, KS_Obra__c>();
        for (ID obraID : obrasAprobadas.keySet()) {
            
            KS_Obra__c obra = new KS_Obra__c(); obra.ID = obraID;
            if ( obrasUpdate.containsKey(obraID) ) { obra = obrasUpdate.get(obraID); }
            
            Set<String> orgVentas = obrasAprobadas.get(obraID);
            if (orgVentas.contains('SI10')) {

                obra.KS_hasSimon__c = true;
                obra.KS_hasSimon_condicion__c = true;

            } else if (orgVentas.contains('FL31')) {

                obra.KS_hasFluvia__c = true;
                obra.KS_hasFluvia_condicion__c = true;   

            } else if (orgVentas.contains('IE20')) {

                obra.KS_hasLighting__c = true;
                obra.KS_hasLighting_condicion__c = true;                   
            }
            
            obrasUpdate.put(obraID, obra);
        }
        update obrasUpdate.values();

		List<KS_Condicion_de_obra_publico__c> condicionesPublicas = new List<KS_Condicion_de_obra_publico__c>();
        for (KS_Condicion_de_Obra__c co : condicionesAprobadas) {
            if (co.KS_Aprobado__c && co.KS_Obra__c != null) { // Por si acaso
                
                KS_Condicion_de_obra_publico__c cop = new KS_Condicion_de_obra_publico__c();
                cop.KS_ID_Condicion__c = co.ID;
                cop.KS_Obra__c = co.KS_Obra__c;
                cop.KS_Estado_de_aprobacion__c = co.KS_Aprobado__c;
                cop.KS_Solicitante__c = co.CreatedById;
                cop.KS_Serie__c = co.KS_Serie__c;
                condicionesPublicas.add(cop);
            }
        }
        Schema.DescribeFieldResult field = KS_Condicion_de_obra_publico__c.KS_ID_Condicion__c.getDescribe();
        Schema.sObjectField idExt = field.getSObjectField();
        Database.UpsertResult[] upsertResult = Database.upsert(condicionesPublicas, idExt, false);          
    }   
}