src/objects/KS_Estructura_Geografica__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto donde se recoge la configuración de regiones y areas para cada organización</description>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_CPDesde__c</fullName>
        <label>CPDesde</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_CPHasta__c</fullName>
        <label>CPHasta</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_CountryCode__c</fullName>
        <label>CountryCode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ISOCountryCodes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Delegacion__c</fullName>
        <label>Delegación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Delegacion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Zona__c</fullName>
        <label>Zona</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Zona_Geog</valueSetName>
        </valueSet>
    </fields>
    <label>Estructura Geografica</label>
    <nameField>
        <label>Estructura Geografica</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estructuras Geograficas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Obra__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Es el objeto superior que agrega las ofertas (oportunidades)</description>
    <fields>
        <fullName>KS_Codigo_Postal__c</fullName>
        <label>Código Postal</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Codigo_postal_oportunidad__c</fullName>
        <label>Código postal</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Fase__c</fullName>
        <label>Fase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Proyecto</fullName>
                    <default>true</default>
                    <label>Proyecto</label>
                </value>
                <value>
                    <fullName>Obra</fullName>
                </value>
                <value>
                    <fullName>Parada</fullName>
                </value>
                <value>
                    <fullName>Finalizada</fullName>
                </value>
                <value>
                    <fullName>Abandonada / Desestimada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Marca__c</fullName>
        <label>Marca Ubicación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Pais__c</fullName>
        <label>País</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ISOCountryCodes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Pais_oportunidad__c</fullName>
        <label>País</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ISOCountryCodes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Ubicaciones_COUNT__c</fullName>
        <label>Ubicaciones (COUNT)</label>
        <summaryForeignKey>KS_Obra_Ubicacion__c.KS_Obra__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>KS_hasFluvia__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fluvia</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_hasLighting__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lighting</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_hasSimon__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Simon</label>
        <type>Checkbox</type>
    </fields>
    <label>Obra</label>
    <nameField>
        <label>Nombre de Obra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Obras</pluralLabel>
    <recordTypes>
        <fullName>KS_Construdatos</fullName>
        <active>true</active>
        <description>Tipo de registro para alojar las obras provenientes de Construdatos</description>
        <label>Construdatos</label>
    </recordTypes>
    <recordTypes>
        <fullName>KS_Oportunidades</fullName>
        <active>true</active>
        <description>Tipo de registro, para registrar las obras sobre las que se va a ofertar o se ha ofertado.</description>
        <label>Oportunidades</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Obra_Ubicacion__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Determina la ubicación de cada obra para las Organizaciones de venta intervinientes.</description>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Delegacion__c</fullName>
        <label>Delegación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Delegacion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>ID Ubicación</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>KS_Marca__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Obra__c</fullName>
        <label>Obra</label>
        <referenceTo>KS_Obra__c</referenceTo>
        <relationshipLabel>Ubicaciones Obra</relationshipLabel>
        <relationshipName>Ubicaciones_Obra</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>KS_Responsable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Ubicaciones_Obra</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Ubicacion__c</fullName>
        <label>Ubicación</label>
        <referenceTo>KS_Estructura_Geografica__c</referenceTo>
        <relationshipLabel>Ubicaciones Obra</relationshipLabel>
        <relationshipName>Ubicaciones_Obra</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>KS_Zona__c</fullName>
        <label>Zona</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Zona_Geog</valueSetName>
        </valueSet>
    </fields>
    <label>Ubicación Obra</label>
    <nameField>
        <displayFormat>UO-{0000000}</displayFormat>
        <label>ID Ubicación Obra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ubicaciones Obra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Delegacion__c</fullName>
        <label>Delegación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Delegacion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>KS_Obra__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Oportunidades</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KS_Obra__c</referenceTo>
        <relationshipLabel>Ofertas</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Organizacion_Ventas__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizacion_de_ventas__c</fullName>
        <formula>text( KS_Organizacion_Cliente__r.KS_Organizacion_de_ventas__c )</formula>
        <label>Organización de ventas (FÓRMULA)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Pais__c</fullName>
        <formula>NULLVALUE(
TEXT(KS_Distribuidor__r.ShippingCountryCode), 
TEXT(KS_Distribuidor__r.BillingCountryCode)
)</formula>
        <label>País Distribuidor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Zona__c</fullName>
        <label>Zona</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Zona_Geog</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Territory2.object
<CustomObject>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Organizacion_Ventas__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/globalValueSets/ISOCountryCodes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AS</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BQ</fullName>
    </customValue>
    <description>EN USO --&gt; Estructuras geográficas / Autorizaciones Ofertas</description>
    <masterLabel>ISOCountryCodes</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Area.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1010</fullName>
    </customValue>
    <customValue>
        <fullName>1020</fullName>
    </customValue>
    <customValue>
        <fullName>1021</fullName>
    </customValue>
    <customValue>
        <fullName>1030</fullName>
    </customValue>
    <customValue>
        <fullName>1040</fullName>
    </customValue>
    <customValue>
        <fullName>1050</fullName>
    </customValue>
    <customValue>
        <fullName>1060</fullName>
    </customValue>
    <customValue>
        <fullName>INTE</fullName>
    </customValue>
    <description>SAP. IDs SAP de Área</description>
    <masterLabel>Área</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Delegacion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>009</fullName>
    </customValue>
    <customValue>
        <fullName>010</fullName>
    </customValue>
    <customValue>
        <fullName>011</fullName>
    </customValue>
    <customValue>
        <fullName>012</fullName>
    </customValue>
    <customValue>
        <fullName>013</fullName>
    </customValue>
    <customValue>
        <fullName>015</fullName>
    </customValue>
    <customValue>
        <fullName>017</fullName>
    </customValue>
    <customValue>
        <fullName>018</fullName>
    </customValue>
    <customValue>
        <fullName>019</fullName>
    </customValue>
    <customValue>
        <fullName>020</fullName>
    </customValue>
    <customValue>
        <fullName>021</fullName>
    </customValue>
    <customValue>
        <fullName>023</fullName>
    </customValue>
    <customValue>
        <fullName>024</fullName>
    </customValue>
    <customValue>
        <fullName>025</fullName>
    </customValue>
    <customValue>
        <fullName>026</fullName>
    </customValue>
    <customValue>
        <fullName>027</fullName>
    </customValue>
    <customValue>
        <fullName>028</fullName>
    </customValue>
    <customValue>
        <fullName>029</fullName>
    </customValue>
    <customValue>
        <fullName>030</fullName>
    </customValue>
    <customValue>
        <fullName>031</fullName>
    </customValue>
    <customValue>
        <fullName>032</fullName>
    </customValue>
    <customValue>
        <fullName>033</fullName>
    </customValue>
    <customValue>
        <fullName>034</fullName>
    </customValue>
    <customValue>
        <fullName>035</fullName>
    </customValue>
    <customValue>
        <fullName>036</fullName>
    </customValue>
    <description>SAP. IDs SAP de Delegación</description>
    <masterLabel>Delegación</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Organizacion_de_ventas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>FL31</fullName>
    </customValue>
    <customValue>
        <fullName>GI50</fullName>
    </customValue>
    <customValue>
        <fullName>IE20</fullName>
    </customValue>
    <customValue>
        <fullName>MA15</fullName>
    </customValue>
    <customValue>
        <fullName>MA16</fullName>
    </customValue>
    <customValue>
        <fullName>MX24</fullName>
    </customValue>
    <customValue>
        <fullName>MX25</fullName>
    </customValue>
    <customValue>
        <fullName>MX26</fullName>
    </customValue>
    <customValue>
        <fullName>SI10</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente / Jerarquia Cliente / Producto / Autorizaciones Oferta --&gt; CARGADO</description>
    <masterLabel>Organizacion de ventas</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Zona_Geog.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>23</fullName>
    </customValue>
    <customValue>
        <fullName>24</fullName>
    </customValue>
    <customValue>
        <fullName>25</fullName>
    </customValue>
    <customValue>
        <fullName>26</fullName>
    </customValue>
    <customValue>
        <fullName>27</fullName>
    </customValue>
    <customValue>
        <fullName>28</fullName>
    </customValue>
    <customValue>
        <fullName>29</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <description>SAP. En Uso en Oportunidaes/Obras</description>
    <masterLabel>Zona Geog.</masterLabel>
</GlobalValueSet>

src/classes/KS_Obra_Trigger.cls
public without sharing class KS_Obra_Trigger extends KS_TriggerController {

    public KS_Obra_Trigger (Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate,
        List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems)
    {
        super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);
    }
    
    public static Map<ID,sObject> running = new Map<ID,sObject>();
    public static Boolean isBlocked() { System.debug('-- TRIGGER BLOCKED! --'); return Test.isRunningTest() && KS_Trigger_Test.blockTrigger; }
    public static Boolean isRunning(Map<Id, sObject> items) {
        // 2018/10/16 JCAR Control recursividad
        items = items != null ? items : new Map<ID,SObject>();
        if (running == null) { running = new Map<ID,sObject>(); }
        if(!running.isEmpty()) {return true;}
        if (items != null && running != null) { running.putAll(items); }
        return false;
    }
    
    //protected override void runBeforeInsert(){ executeBeforeUpsert(); }
    //protected override void runBeforeUpdate(){ executeBeforeUpsert(); }
    //public void executeBeforeUpsert(){ setUbicacionObra(); }
    
    protected override void runAfterInsert(){ if(isBlocked()){return;} setUbicacionObra(); }
    protected override void runAfterUpdate(){ if(isBlocked()||isRunning(mapNewItems)){return;} executeAfterUpdate(); setUbicacionObra(); }
    public void executeAfterUpdate() {
        
        List<KS_Obra__c> obraLst = (List<KS_Obra__c>)lstNewItems;
        List<KS_Obra__c> obraLstOLD = isInsert ? new List<KS_Obra__c>() : (List<KS_Obra__c>)lstOldItems;
        
        List<ID> obrasChangeEstado = new List<ID>();
        Map<ID, String> obrasEstados = new Map<ID, String>();
        
        for (Integer i = 0; i < obraLst.size(); i++) {
            
            KS_Obra__c obra = obraLst.get(i);
            KS_Obra__c obraOLD = isInsert ? new KS_Obra__c() : obraLstOLD.get(i);
            
            // Cambio de estado           
            if (obra.KS_Fase__c != obraOLD.KS_Fase__c) {
                obrasChangeEstado.add(obra.ID);
                obrasEstados.put(obra.ID, obra.KS_Fase__c);
            }
        }
        
        // Mapeo ofertas obras
        if (obrasChangeEstado.size()>0) {
            
            List<Opportunity> ofertasUpdate = new List<Opportunity>();
            List<Opportunity> ofertas =  [SELECT ID,StageName,KS_Obra__c FROM Opportunity
                                          WHERE KS_Obra__c in :obrasChangeEstado];
            
            for (Opportunity oferta : ofertas) {
                
                String estado = oferta.StageName;
                String estadoObra = obrasEstados.get(oferta.KS_Obra__c);
                
                if (estadoObra == 'Parada' && estado != estadoObra) {
                    oferta.StageName = estadoObra;
                    if (KS_Opportunity_Trigger.runningOpps != null && !KS_Opportunity_Trigger.runningOpps.containsKey(oferta.ID)) { // 2018/10/16 JCAR Control recursividad
                        ofertasUpdate.add(oferta);
                    } else {
                        // 2018/10/16 JCAR Control recursividad
                        KS_Opportunity_Trigger.runningOpps = KS_Opportunity_Trigger.runningOpps != null ? KS_Opportunity_Trigger.runningOpps : new Map<ID,sObject>();
                        KS_Opportunity_Trigger.runningOpps.put(oferta.ID, oferta);
                    }
                }
            }

            if (ofertasUpdate.size()>0) { update ofertasUpdate; }
        }
    }
    
    public void setUbicacionObra() {
        
        Map<String,ID> terrType = new Map<String,ID>();
        List<Territory2Type> terrLst = [SELECT ID, DeveloperName FROM Territory2Type];
        for (Territory2Type tp : terrLst) {
            terrType.put(tp.DeveloperName, tp.ID);
        }
        
        Map<String,ID> recordTypes = new Map<String,ID>();
        List<RecordType> rtLst = [SELECT ID,DeveloperName FROM RecordType];
        for (RecordType rt : rtLst) {
            recordTypes.put(rt.DeveloperName, rt.ID);
        }        
        
        List<KS_Obra__c> obraLst = (List<KS_Obra__c>)lstNewItems;
        List<KS_Obra__c> obraLstOLD = isInsert ? new List<KS_Obra__c>() : (List<KS_Obra__c>)lstOldItems;
        
        Map<ID, Set<String>> obraMarcas = new Map<ID, Set<String>>();
        Map<ID, String> obraPais = new Map<ID, String>();
        Map<ID, String> obraCodPos = new Map<ID, String>();
        Set<String> idMarcaSet = new Set<String>(); List<String> idMarcaLst = new List<String>();
        
        List<ID> resetMarcas = new List<ID>();
        
        for (Integer i = 0; i < obraLst.size(); i++) {

            KS_Obra__c obra = obraLst.get(i);
            KS_Obra__c obraOLD = isInsert ? new KS_Obra__c() : obraLstOLD.get(i);          
            
            Boolean direccionOportunidad = obra.KS_Codigo_postal_oportunidad__c != null && obra.KS_Pais_oportunidad__c != null;
            Boolean direccionOportunidadOLD = obraOLD.KS_Codigo_postal_oportunidad__c != null && obraOLD.KS_Pais_oportunidad__c != null;
            
            String codP = direccionOportunidad ? obra.KS_Codigo_postal_oportunidad__c : obra.KS_Codigo_Postal__c;
            String pais = direccionOportunidad ? obra.KS_Pais_oportunidad__c : obra.KS_Pais__c;      
            String codPOLD = direccionOportunidadOLD ? obraOLD.KS_Codigo_postal_oportunidad__c : obraOLD.KS_Codigo_Postal__c;
            String paisOLD = direccionOportunidadOLD ? obraOLD.KS_Pais_oportunidad__c : obraOLD.KS_Pais__c;            
            
            Boolean newRT = obraOLD.RecordTypeId == recordTypes.get('KS_Construdatos') && obra.RecordTypeId == recordTypes.get('KS_Oportunidades');
            
            /*if (obra.KS_Marca__c == null) {
                if (obra.KS_hasSimon__c) { obra.KS_Marca__c = 'SI10'; }
                else if (obra.KS_hasFluvia__c) { obra.KS_Marca__c = 'FL31'; }
                else if (obra.KS_hasLighting__c) { obra.KS_Marca__c = 'IE20'; }                
            }*/
            
            if ( (obraOLD.KS_Marca__c == null && obra.KS_Marca__c != null) || isInsert 
                || (codPOLD == null && codP != null) ) {

                Set<String> marcas = new Set<String>();
                if (obraMarcas.containsKey(obra.ID)) { marcas = obraMarcas.get(obra.ID); }
                marcas.add(obra.KS_Marca__c);
                
                obraMarcas.put(obra.ID, marcas);
                idMarcaSet.add(obra.KS_Marca__c);
                    
                if (codP != null) {
                    obraCodPos.put(obra.ID, codP);
                }
                    
                if (pais != null) {
                    obraPais.put(obra.ID, pais);
                }                    
            }

            if (isUpdate && ( newRT || obra.KS_Ubicaciones_COUNT__c == 0 || (codP != codPOLD || obra.KS_Marca__c != obraOLD.KS_Marca__c || pais != paisOLD) ) ) {
                
                resetMarcas.add(obra.ID);
                Set<String> marcas = new Set<String>();
                if (obraMarcas.containsKey(obra.ID)) { marcas = obraMarcas.get(obra.ID); }                
                
                if (obra.KS_Marca__c != null) { idMarcaSet.add(obra.KS_Marca__c); marcas.add(obra.KS_Marca__c); }
                if (obra.KS_hasSimon__c) { idMarcaSet.add('SI10'); marcas.add('SI10'); }
                if (obra.KS_hasFluvia__c) { idMarcaSet.add('FL31'); marcas.add('FL31'); }
                if (obra.KS_hasLighting__c) { idMarcaSet.add('IE20'); marcas.add('IE20'); }

                obraMarcas.put(obra.ID, marcas);
                obraCodPos.put(obra.ID, codP);
                obraPais.put(obra.ID, pais);
            
            } else if (isUpdate) {
                
                Set<String> marcas = new Set<String>();
                if (obraMarcas.containsKey(obra.ID)) { marcas = obraMarcas.get(obra.ID); }                 
                
                if (obra.KS_hasSimon__c && !obraOLD.KS_hasSimon__c) 
                { idMarcaSet.add('SI10'); marcas.add('SI10'); }
                else if(!obra.KS_hasSimon__c && obraOLD.KS_hasSimon__c) 
                { resetMarcas.add(obra.ID); }
                
                if (obra.KS_hasFluvia__c && !obraOLD.KS_hasFluvia__c) 
                { idMarcaSet.add('FL31'); marcas.add('FL31'); }
                else if(!obra.KS_hasFluvia__c && obraOLD.KS_hasFluvia__c) 
                { resetMarcas.add(obra.ID); }
                
                if (obra.KS_hasLighting__c && !obraOLD.KS_hasLighting__c) 
                { idMarcaSet.add('IE20'); marcas.add('IE20'); }
                else if(!obra.KS_hasLighting__c && obraOLD.KS_hasLighting__c) 
                { resetMarcas.add(obra.ID); }
                
                if (marcas.size()>0) {
                    obraMarcas.put(obra.ID, marcas);
                    obraCodPos.put(obra.ID, codP);
                    obraPais.put(obra.ID, pais);
                }
            }
        }

        System.debug('-- JCAR ---------------------------------- - setUbicacionObra ' + resetMarcas.size() + ' resetMarcas - ' + resetMarcas);
        if (resetMarcas.size()>0) {
            //KS_Obra_Ubicacion__c
            List<KS_Obra_Ubicacion__c> obuDEL = [SELECT ID FROM KS_Obra_Ubicacion__c WHERE KS_Obra__c IN :resetMarcas];
            System.debug('-- JCAR ---------------------------------- - setUbicacionObra ' + obuDEL.size() + ' DELETE KS_Obra_Ubicacion__c  - ' + obuDEL);
            delete obuDEL;
        }
        
		System.debug('-- JCAR ---------------------------------- - setUbicacionObra ' + obraMarcas.size() + ' obraMarcas - ' + obraMarcas);
        System.debug('-- JCAR ---------------------------------- - setUbicacionObra ' + obraCodPos.size() + ' obraCodPos - ' + obraCodPos);
        System.debug('-- JCAR ---------------------------------- - setUbicacionObra ' + obraPais.size() + ' obraPais - ' + obraPais);
        
        idMarcaLst.addAll(idMarcaSet);
        List<KS_Estructura_Geografica__c> esGeogLst = 
            [SELECT Id, KS_CPDesde__c, KS_CPHasta__c, KS_Delegacion__c, KS_Area__c, KS_Zona__c, KS_Organizacion_de_ventas__c, KS_CountryCode__c 
             FROM KS_Estructura_Geografica__c WHERE KS_Organizacion_de_ventas__c IN :idMarcaLst AND KS_CountryCode__c IN : obraPais.values()];
        
        Map<ID, Set<ID>> ubicacionObraMap = new Map<ID, Set<ID>>();
        Map<String, String> marcareaUbicacion = new Map<String, String>();
        
        List<String> areaGLst = new List<String>();
        List<String> orgVnLST = new List<String>();
        
        // Supondremos que las obras siempre son en España
        for (ID obraID : obraCodPos.keySet()) {
            
            String codPostal = obraCodPos.get(obraID);
            Set<String> marcas = obraMarcas.get(obraID);
            String pais = obraPais.get(obraID);
            
            System.debug('-- JCAR ---------------------------------- - for OBRA ' + obraID);
            System.debug('-- JCAR ---------------------------------- - for OBRA codPostal ' + codPostal);
            System.debug('-- JCAR ---------------------------------- - for OBRA marcas ' + marcas);
            
            for (KS_Estructura_Geografica__c eg : esGeogLst) {
                
                Boolean bingo = false;
                if (marcas.contains(eg.KS_Organizacion_de_ventas__c) && eg.KS_CountryCode__c == pais && eg.KS_CPDesde__c != null) {
                    
                    String dsd = eg.KS_CPDesde__c;
                    String hst = eg.KS_CPHasta__c;
                    
                    if (codPostal.length() == 4) { 
                        codPostal = '0'+codPostal;
                    }
                    bingo = codPostal.startsWithIgnoreCase(dsd.substring(0,2));                    
                }
                if (bingo && eg.KS_Area__c != null && eg.KS_Organizacion_de_ventas__c != null) {
                    
                    System.debug('-- JCAR ---------------------------------- - for OBRA BINGO');
                    System.debug('-- JCAR ---------------------------------- - for OBRA ' + eg);
                    
                    Set<ID> egIDs = new Set<ID>();
                    if (ubicacionObraMap.containsKey(obraID)) { egIDs = ubicacionObraMap.get(obraID); }
                    egIDs.add(eg.ID); ubicacionObraMap.put(obraID, egIDs);
                    
                    areaGLst.add(eg.KS_Area__c);
                    orgVnLST.add(eg.KS_Organizacion_de_ventas__c);
                    //break;

                    String uboK = obraID + '-' + eg.ID;
                    String uboV = eg.KS_Organizacion_de_ventas__c + '-' + eg.KS_Area__c;
                    marcareaUbicacion.put(uboK, uboV);
                }
            }
        }
        
        System.debug('-- JCAR ---------------------------------- - setUbicacionObra ' + ubicacionObraMap.size() + ' ubicacionObraMap - ' + ubicacionObraMap);
        System.debug('-- JCAR ---------------------------------- - setUbicacionObra ' + marcareaUbicacion.size() + ' marcareaUbicacion - ' + marcareaUbicacion);
        
        System.debug('-- JCAR ---------------------------------- - setUbicacionObra ' + areaGLst.size() + ' areaGLst - ' + areaGLst);
        System.debug('-- JCAR ---------------------------------- - setUbicacionObra ' + orgVnLST.size() + ' orgVnLST - ' + orgVnLST);
        
        //List<KS_Obra_Ubicacion__c> ubacionesObra = new List<KS_Obra_Ubicacion__c>();
        Map<String, KS_Obra_Ubicacion__c> ubacionesObra = new Map<String, KS_Obra_Ubicacion__c>();
        for (ID obraID : ubicacionObraMap.keySet()) {

            Set<ID> egID = ubicacionObraMap.get(obraID);
            for (ID eg : egID) {
                
                if (eg != null) {
                    KS_Obra_Ubicacion__c ubo = new KS_Obra_Ubicacion__c();
                    ubo.KS_Obra__c = obraID;
                    ubo.KS_Ubicacion__c = eg;
                    ubo.KS_ID__c = ubo.KS_Obra__c + '-' + ubo.KS_Ubicacion__c;
                    
                    ubacionesObra.put(ubo.KS_ID__c, ubo);
                }
            }
        }
        
        Map<ID,ID> responsables = new Map<ID,ID>();
        List<UserTerritory2Association> terrOferta = 
            [SELECT Id, UserId, Territory2Id, RoleInTerritory2,
             Territory2.KS_Organizacion_Ventas__c,
             Territory2.KS_Area__c
             FROM UserTerritory2Association 
             WHERE RoleInTerritory2 = 'JAR'
             AND Territory2.KS_Organizacion_Ventas__c IN :orgVnLST
             AND Territory2.KS_Area__c IN :areaGLst
             AND Territory2.Territory2TypeId = :terrType.get('KS_Area')
            ];
        
        System.debug('-- JCAR ---------------------------------- - setUbicacionObra ' + terrOferta.size() + ' terrOferta - ' + terrOferta);
        
        for (String uoK : ubacionesObra.keySet()) {
            
            KS_Obra_Ubicacion__c ubo = ubacionesObra.get(uoK);
            for (UserTerritory2Association uta : terrOferta) {
                
                String ovTerr = uta.Territory2.KS_Organizacion_Ventas__c;
                String arTerr = uta.Territory2.KS_Area__c;
                ID usTerr = uta.UserId;
                
                //System.debug('-- JCAR ---------------------------------- - setUbicacionObra - SET JAR eg - org.vent ' + ovTerr + ' - area ' + arTerr + ' - user ' + usTerr);
                
                if (usTerr != null && ovTerr != null && arTerr != null && marcareaUbicacion.containsKey(uoK)) {
                    
                    String marcarea = marcareaUbicacion.get(uoK);
                    String ovMA = marcarea.split('-')[0];
                    String arMA = marcarea.split('-')[1]; 
                    
                    //System.debug('-- JCAR ---------------------------------- - setUbicacionObra - SET JAR ma - org.vent ' + ovMA + ' - area ' + arMA);
                    
                    if (ovTerr == ovMA && arTerr == arMA ) {
                        
                        ubo.KS_Responsable__c = usTerr;
                        ubacionesObra.put(uoK, ubo);
                    }
                }
            }
        }
        
        System.debug('-- JCAR ---------------------------------- - setUbicacionObra ' + ubacionesObra.size() + ' ubacionesObra - ' + ubacionesObra.values());
        
        Schema.DescribeFieldResult field = KS_Obra_Ubicacion__c.KS_ID__c.getDescribe();
        Schema.sObjectField idUbOb = field.getSObjectField();
        Database.UpsertResult[] upsertResult = Database.upsert(ubacionesObra.values(), idUbOb, true);         
    }    
}