src/objects/KS_Fusion__c.object
<CustomObject>
    <fields>
        <fullName>KS_Accion__c</fullName>
        <label>KS_Accion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MERGE</fullName>
                </value>
                <value>
                    <fullName>DELETE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Id_Principal__c</fullName>
        <label>KS_Id_Principal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Fusion</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Fusion ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fusiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KS_Batch_MergeTool_DeleteContacts.cls
global class KS_Batch_MergeTool_DeleteContacts implements Database.Batchable<sObject> {
	
	String query = 'SELECT Id,KS_Id_Principal__c,KS_Accion__c FROM KS_Fusion__c WHERE KS_Accion__c = \'DELETE\'';
	
	global KS_Batch_MergeTool_DeleteContacts() {
		
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<KS_Fusion__c> scope) 
	{
		KS_MergeTool_MergeAuto mergeDelCn = new KS_MergeTool_MergeAuto();
        System.debug('-- JCAR -- KS_Batch_MergeTool_DeleteContacts ----------------- scope ' 
                     + scope.size() + ' List<sObject> ' + scope);
		mergeDelCn.DeleteContacts(scope);
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
}