src/objects/KS_Fusion__c.object
<CustomObject>
    <fields>
        <fullName>KS_Accion__c</fullName>
        <label>KS_Accion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MERGE</fullName>
                </value>
                <value>
                    <fullName>DELETE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Ctc_Calle__c</fullName>
        <label>KS_Ctc_Calle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Cargo__c</fullName>
        <label>KS_Ctc_Cargo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Ciudad__c</fullName>
        <label>KS_Ctc_Ciudad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Codigo_Postal__c</fullName>
        <label>KS_Ctc_Codigo_Postal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Correo__c</fullName>
        <label>KS_Ctc_Correo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Estado_Provincia__c</fullName>
        <label>KS_Ctc_Estado_Provincia</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Funcion_en_empresa__c</fullName>
        <label>KS_Ctc_Funcion_en_empresa</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Idioma__c</fullName>
        <label>KS_Ctc_Idioma</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Movil__c</fullName>
        <label>KS_Ctc_Movil</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Pais__c</fullName>
        <label>KS_Ctc_Pais</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Telefono_Particular__c</fullName>
        <label>KS_Ctc_Telefono_Particular</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Ctc_Telefono__c</fullName>
        <label>KS_Ctc_Telefono</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Id_Duplicado_2__c</fullName>
        <label>KS_Id_Duplicado_2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Id_Duplicado__c</fullName>
        <label>KS_Id_Duplicado</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Id_Principal__c</fullName>
        <label>KS_Id_Principal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Tipo__c</fullName>
        <label>KS_Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACCOUNT</fullName>
                </value>
                <value>
                    <fullName>CONTACT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fusion</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Fusion ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fusiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KS_Batch_MergeTool_MergeContacts.cls
global class KS_Batch_MergeTool_MergeContacts implements Database.Batchable<sObject> {
	
	String query = 'SELECT Id, Name, KS_Accion__c, KS_Id_Principal__c, KS_Id_Duplicado__c, KS_Id_Duplicado_2__c, KS_Ctc_Calle__c, KS_Ctc_Ciudad__c, KS_Ctc_Codigo_Postal__c, KS_Ctc_Estado_Provincia__c, KS_Ctc_Pais__c, KS_Ctc_Telefono__c, KS_Ctc_Movil__c, KS_Ctc_Telefono_Particular__c, KS_Ctc_Correo__c, KS_Ctc_Funcion_en_empresa__c, KS_Ctc_Cargo__c, KS_Ctc_Idioma__c FROM KS_Fusion__c WHERE KS_Accion__c = \'MERGE\' AND KS_Tipo__c = \'CONTACT\'';
	
	global KS_Batch_MergeTool_MergeContacts() {
		
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) 
	{
		KS_MergeTool_MergeAuto mergeCn = new KS_MergeTool_MergeAuto();
        System.debug('-- JCAR -- KS_Batch_MergeTool_MergeContacts ----------------- scope ' 
                     + scope.size() + ' List<sObject> ' + scope);
		mergeCn.MergeContacts(scope);
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}