src/objects/KS_Intervinientes__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto que registra el tipo de interacción que tiene una cuenta con las ofertas.</description>
    <fields>
        <fullName>KS_Interviniente__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Intervinientes</relationshipLabel>
        <relationshipName>Intervinientes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Obra__c</fullName>
        <label>Obra</label>
        <referenceTo>KS_Obra__c</referenceTo>
        <relationshipLabel>Intervinientes</relationshipLabel>
        <relationshipName>Intervinientes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>KS_Origen__c</fullName>
        <label>Origen</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Origen_Interviniente</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Repeticiones__c</fullName>
        <description>Veces que sale el interviniente en las Ofertas</description>
        <inlineHelpText>Veces que sale el interviniente en las Ofertas</inlineHelpText>
        <label>Repeticiones</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Interviniente</label>
    <nameField>
        <displayFormat>IT-{00000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervinientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KS_Obra__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Es el objeto superior que agrega las ofertas (oportunidades)</description>
    <label>Obra</label>
    <nameField>
        <label>Nombre de Obra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Obras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Oferta_pendiente__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Recoge los destinatarios de ofertas, relacionando cliente vs oferta</description>
    <fields>
        <fullName>KS_Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Destinatarios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <referenceTo>KS_Obra__c</referenceTo>
        <relationshipLabel>Registros de ofertas enviadas</relationshipLabel>
        <relationshipName>Registros_de_ofertas_enviadas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Registro de ofertas enviadas</label>
    <nameField>
        <displayFormat>DES-{000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registros de ofertas enviadas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>KS_Cliente_final__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente final / Prescriptor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Clientes finales, Prescriptores</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Lead</value>
            </filterItems>
            <filterItems>
                <field>Account.KS_Canal__c</field>
                <operation>notEqual</operation>
                <value>Distribuidores CRM, Instalador, Asociaciones</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ofertas (Cliente final)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Distribuidor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribuidor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Distribuidores</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Distribuidores_SAP</value>
            </filterItems>
            <filterItems>
                <field>Account.KS_Grupo_de_ctas_deudor__c</field>
                <operation>notEqual</operation>
                <value>Destinatarios mercancías</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ofertas (Distribuidor)</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Instalador__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instalador</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 4 OR (2 AND 3)</booleanFilter>
            <errorMessage>La cuenta indicada como Instalador no tiene dicha tipología. Tan sólo pueden aceptarse Lead de tipo Instalador o Cuentas de tipo Instalador.</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Instalador, Clientes finales, Prescriptores</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Lead</value>
            </filterItems>
            <filterItems>
                <field>Account.KS_Canal__c</field>
                <operation>equals</operation>
                <value>Instalador</value>
            </filterItems>
            <filterItems>
                <field>Account.Id</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ofertas (Instalador)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>KS_Obra__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Oportunidades</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KS_Obra__c</referenceTo>
        <relationshipLabel>Ofertas</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/KS_Origen_Interviniente.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <default>true</default>
        <label>0</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <description>0 = Obra, 1 = Oferta</description>
    <masterLabel>Origen Interviniente</masterLabel>
</GlobalValueSet>

src/classes/KS_Opportunity_Trigger_Utility.cls
public without sharing class KS_Opportunity_Trigger_Utility {

    
    public static void calculaIntervinientes(List<ID> idObra) {
        
        if (idObra.isEmpty()) {return;}
        else if (idObra.get(0)==null) {return;}
        
        // TRIGGER INTERVINIENTE
        // INTERVINIENTE == KS_Obra__c+KS_Distribuidor__c
        // Los lookup KS_Cliente_final__c, KS_Instalador__c y KS_Distribuidor__c se convertirán en Interviniente
        // Hay que verificar si ya hay creados con los criterios KS_Obra__c+KS_Distribuidor__c y sumarles 1 al campo KS_Repeticiones__c        
        
        // Primer mapeo, extracción de cuentas
        List<Opportunity> ofertas = [SELECT ID,KS_Distribuidor__c,AccountId,KS_Instalador__c,KS_Cliente_final__c,KS_Obra__c
                                     FROM Opportunity WHERE KS_Obra__c IN :idObra];
        List<KS_Oferta_Pendiente__c> ofertasP = [SELECT ID,KS_Cuenta__c,KS_Obra__c
                                                 FROM KS_Oferta_Pendiente__c WHERE KS_Obra__c IN :idObra];
        Map<String, Decimal> intervinientesObra = setIntervinientesObra(ofertas, ofertasP);
		System.debug('----------------------------------------JCAR - ' + intervinientesObra.size() + ' intervinientesObra : ' + intervinientesObra);
        
        // Segundo mapeo, intervinientes actuales!
        // SI está en OLD y NO en NEW, DELETE
        // SI está en NEW y NO en OLD, INSERT
        // SI está en NEW y SI en OLD, UPDATE
        Map<String, KS_Intervinientes__c> intervinientesObraOLD = new Map<String, KS_Intervinientes__c>();
        List<KS_Intervinientes__c> interDELETE = new List<KS_Intervinientes__c>();
        for (KS_Intervinientes__c inter : [SELECT ID,KS_Obra__c,KS_Interviniente__c,KS_Repeticiones__c FROM KS_Intervinientes__c WHERE KS_Obra__c IN :idObra]) {

            String skey = inter.KS_Obra__c + '_' + inter.KS_Interviniente__c;
            //System.debug('----------------------------------------JCAR - ' + skey);
            if (!intervinientesObra.containsKey(skey)) { // DELETE
                interDELETE.add(inter);
            } else { // UPDATE
            	intervinientesObraOLD.put(skey, inter);    
            }
        }
        System.debug('----------------------------------------JCAR - ' + intervinientesObraOLD.size() + ' intervinientesObraOLD : ' + intervinientesObraOLD);
        
        // Tercer mapeo, cruzado de datos
        List<KS_Intervinientes__c> interUPSERT = new List<KS_Intervinientes__c>();
        for (String skey : intervinientesObra.keySet()) {
            
            //System.debug('----------------------------------------JCAR - ' + skey);
            
            Decimal count = intervinientesObra.get(skey);
            KS_Intervinientes__c inter = new KS_Intervinientes__c();
            if ( intervinientesObraOLD.containsKey(skey) ) //  UPDATE!
            { 
                inter = intervinientesObraOLD.get(skey);
                //System.debug('----------------------------------------JCAR - ' + inter);
            }
            else // INSERT!
            {
                inter.KS_Obra__c = skey.split('_')[0];
                inter.KS_Interviniente__c = skey.split('_')[1];
            }
            inter.KS_Origen__c = '1'; // Origen = Oferta
            inter.KS_Repeticiones__c = count;
            interUPSERT.add(inter);
            
        }
        System.debug('----------------------------------------JCAR - ' + interUPSERT.size() + ' interUPSERT : ' + interUPSERT);
        upsert interUPSERT;
        System.debug('----------------------------------------JCAR - ' + interDELETE.size() + ' interDELETE : ' + interDELETE);
        delete interDELETE;        
        
    }
    private static Map<String, Decimal>  setIntervinientesObra (List<Opportunity> ofertas, List<KS_Oferta_Pendiente__c> ofertasP) {
        
        System.debug('----------------------------------------JCAR - ' + ofertas.size() + ' ofertas : ' + ofertas);
        System.debug('----------------------------------------JCAR - ' + ofertasP.size() + ' ofertasP : ' + ofertasP);        
        
        Map<String, Decimal> intervinientesObra = new Map<String, Decimal>();
        for (Opportunity opp : ofertas) {
            
            List<String> oppAcc = new List<String>();
            if (opp.KS_Distribuidor__c != null) { oppAcc.add(opp.KS_Distribuidor__c); }
            if (opp.KS_Instalador__c != null) { oppAcc.add(opp.KS_Instalador__c); }
            if (opp.KS_Cliente_final__c != null) { oppAcc.add(opp.KS_Cliente_final__c); }
            
            for (String accID : oppAcc) {
                
                String skey = opp.KS_Obra__c + '_' + accID;
                Decimal count = 0;
                if (intervinientesObra.containsKey(skey)) {
                    count = intervinientesObra.get(skey);
                }
				intervinientesObra.put(skey, count + 1);                
            }
        }
		for (KS_Oferta_Pendiente__c opp : ofertasP) {
            
            if (opp.KS_Cuenta__c != null) {
                
                String skey = opp.KS_Obra__c + '_' + opp.KS_Cuenta__c;
                Decimal count = 0;
                if (intervinientesObra.containsKey(skey)) {
                    count = intervinientesObra.get(skey);
                }
				intervinientesObra.put(skey, count + 1);                
            }
        } 
        return intervinientesObra;
    }
}