src/objects/KS_Obra__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Es el objeto superior que agrega las ofertas (oportunidades)</description>
    <label>Obra</label>
    <nameField>
        <label>Nombre de Obra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Obras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Oferta_pendiente__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Recoge los destinatarios de ofertas, relacionando cliente vs oferta</description>
    <fields>
        <fullName>KS_Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <referenceTo>KS_Obra__c</referenceTo>
        <relationshipLabel>Registros de ofertas enviadas</relationshipLabel>
        <relationshipName>Registros_de_ofertas_enviadas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Oferta__c</fullName>
        <label>Oferta</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Registros de ofertas enviadas</relationshipLabel>
        <relationshipName>Destinatarios</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Registro de ofertas enviadas</label>
    <nameField>
        <displayFormat>DES-{000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registros de ofertas enviadas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>KS_Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>KS_Obra__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Oportunidades</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KS_Obra__c</referenceTo>
        <relationshipLabel>Ofertas</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>KS_Oferta</fullName>
        <active>true</active>
        <businessProcess>Simon</businessProcess>
        <label>Oferta</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/KS_Oferta_Enviada_Controller.cls
global without sharing class KS_Oferta_Enviada_Controller {
    
    public Opportunity oferta {get;set;}
    public KS_Oferta_pendiente__c ofertaPendiente {get;set;}

    public KS_Oferta_Enviada_Controller(ApexPages.StandardController controller) {
        
        String ofertaID = ApexPages.currentPage().getParameters().get('oferta');
        if (ofertaID != null && ofertaID != '') {
            
        	oferta = [SELECT ID, KS_Obra__c FROM Opportunity WHERE ID = :ofertaID];
        }
        
        ofertaPendiente = new KS_Oferta_pendiente__c();
        ofertaPendiente.KS_Oferta__c = oferta.ID;
        ofertaPendiente.KS_Obra__c = oferta.KS_Obra__c;
    }
    
    public PageReference cancel() {
        PageReference pageRef = new PageReference( '/apex/KS_Oferta?id=' + oferta.Id);
        pageRef.SetRedirect(true);
        System.debug('----------------------------------------SERG - pageRef : ' + pageRef );
        return pageRef;
    }    

    public PageReference save() {
        if (ofertaPendiente == null) { return null; }
        System.Approval.unlock(oferta);
        System.debug('-- JCAR ---------------------------------- - ofertaPendiente ' + ofertaPendiente);
        try {
            insert ofertaPendiente;
            System.Approval.lock(oferta);
            PageReference pageRef = new PageReference( '/apex/KS_Oferta_PDF?id=' + ofertaPendiente.ID );
            pageRef.SetRedirect(true);
            System.debug('----------------------------------------SERG - pageRef : ' + pageRef );
            return pageRef;
        } catch (Exception e) {
            ApexPages.addMessages(e);
            return null;
        }
    }
}