src/objects/KS_Obra_Ubicacion__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Determina la ubicación de cada obra para las Organizaciones de venta intervinientes.</description>
    <fields>
        <fullName>KS_AreaF__c</fullName>
        <formula>TEXT( KS_Ubicacion__r.KS_Area__c )</formula>
        <label>Área Fórmula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Area__c</fullName>
        <label>Área</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_DelegacionF__c</fullName>
        <formula>TEXT( KS_Ubicacion__r.KS_Delegacion__c )</formula>
        <label>Delegación Fórmula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Delegacion__c</fullName>
        <label>Delegación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Delegacion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_MarcaF__c</fullName>
        <formula>TEXT( KS_Ubicacion__r.KS_Organizacion_de_ventas__c )</formula>
        <label>Org. Ventas Fórmula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Marca__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_ZonaF__c</fullName>
        <formula>TEXT( KS_Ubicacion__r.KS_Zona__c )</formula>
        <label>Zona Fórmula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KS_Zona__c</fullName>
        <label>Zona</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Zona_Geog</valueSetName>
        </valueSet>
    </fields>
    <label>Ubicación Obra</label>
    <nameField>
        <displayFormat>UO-{0000000}</displayFormat>
        <label>ID Ubicación Obra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ubicaciones Obra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/KS_Area.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1010</fullName>
    </customValue>
    <customValue>
        <fullName>1020</fullName>
    </customValue>
    <customValue>
        <fullName>1021</fullName>
    </customValue>
    <customValue>
        <fullName>1030</fullName>
    </customValue>
    <customValue>
        <fullName>1040</fullName>
    </customValue>
    <customValue>
        <fullName>1050</fullName>
    </customValue>
    <customValue>
        <fullName>1060</fullName>
    </customValue>
    <customValue>
        <fullName>INTE</fullName>
    </customValue>
    <description>SAP. IDs SAP de Área</description>
    <masterLabel>Área</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Delegacion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>002</fullName>
    </customValue>
    <customValue>
        <fullName>005</fullName>
    </customValue>
    <customValue>
        <fullName>006</fullName>
    </customValue>
    <customValue>
        <fullName>007</fullName>
    </customValue>
    <customValue>
        <fullName>008</fullName>
    </customValue>
    <customValue>
        <fullName>009</fullName>
    </customValue>
    <customValue>
        <fullName>010</fullName>
    </customValue>
    <customValue>
        <fullName>011</fullName>
    </customValue>
    <customValue>
        <fullName>012</fullName>
    </customValue>
    <customValue>
        <fullName>013</fullName>
    </customValue>
    <customValue>
        <fullName>015</fullName>
    </customValue>
    <customValue>
        <fullName>017</fullName>
    </customValue>
    <customValue>
        <fullName>018</fullName>
    </customValue>
    <customValue>
        <fullName>019</fullName>
    </customValue>
    <customValue>
        <fullName>020</fullName>
    </customValue>
    <customValue>
        <fullName>021</fullName>
    </customValue>
    <customValue>
        <fullName>023</fullName>
    </customValue>
    <customValue>
        <fullName>024</fullName>
    </customValue>
    <customValue>
        <fullName>025</fullName>
    </customValue>
    <customValue>
        <fullName>026</fullName>
    </customValue>
    <customValue>
        <fullName>027</fullName>
    </customValue>
    <customValue>
        <fullName>028</fullName>
    </customValue>
    <customValue>
        <fullName>029</fullName>
    </customValue>
    <customValue>
        <fullName>030</fullName>
    </customValue>
    <customValue>
        <fullName>031</fullName>
    </customValue>
    <customValue>
        <fullName>032</fullName>
    </customValue>
    <customValue>
        <fullName>033</fullName>
    </customValue>
    <customValue>
        <fullName>034</fullName>
    </customValue>
    <customValue>
        <fullName>035</fullName>
    </customValue>
    <customValue>
        <fullName>036</fullName>
    </customValue>
    <description>SAP. IDs SAP de Delegación</description>
    <masterLabel>Delegación</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Organizacion_de_ventas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>FL31</fullName>
    </customValue>
    <customValue>
        <fullName>GI50</fullName>
    </customValue>
    <customValue>
        <fullName>IE20</fullName>
    </customValue>
    <customValue>
        <fullName>MA15</fullName>
    </customValue>
    <customValue>
        <fullName>MA16</fullName>
    </customValue>
    <customValue>
        <fullName>MX24</fullName>
    </customValue>
    <customValue>
        <fullName>MX25</fullName>
    </customValue>
    <customValue>
        <fullName>MX26</fullName>
    </customValue>
    <customValue>
        <fullName>SI10</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente / Jerarquia Cliente / Producto / Autorizaciones Oferta --&gt; CARGADO</description>
    <masterLabel>Organizacion de ventas</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Zona_Geog.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <customValue>
        <fullName>9</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>23</fullName>
    </customValue>
    <customValue>
        <fullName>24</fullName>
    </customValue>
    <customValue>
        <fullName>25</fullName>
    </customValue>
    <customValue>
        <fullName>26</fullName>
    </customValue>
    <customValue>
        <fullName>27</fullName>
    </customValue>
    <customValue>
        <fullName>28</fullName>
    </customValue>
    <customValue>
        <fullName>29</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <description>SAP. En Uso en Oportunidaes/Obras</description>
    <masterLabel>Zona Geog.</masterLabel>
</GlobalValueSet>

src/classes/KS_Obra_Ubicacion_Trigger.cls
public without sharing class KS_Obra_Ubicacion_Trigger extends KS_TriggerController {

    public KS_Obra_Ubicacion_Trigger (Boolean isAfter, Boolean isBefore, Boolean isDelete, Boolean isInsert, Boolean isUndelete, Boolean isUpdate,
        List<sObject> lstNewItems, Map<Id, sObject> mapNewItems, List<sObject> lstOldItems, Map<Id, sObject> mapOldItems)
    {
        super(isAfter, isBefore, isDelete, isInsert, isUndelete, isUpdate, lstNewItems, mapNewItems, lstOldItems, mapOldItems);
    }
    
    public static Boolean blocked() { System.debug('-- TRIGGER BLOCKED! --'); return Test.isRunningTest() && KS_Trigger_Test.blockTrigger; }
    
    protected override void  runBeforeInsert(){ if(blocked()){return;} executeBeforeInsert(); }
    protected override void  runBeforeUpdate(){ if(blocked()){return;} executeBeforeUpdate(); }    
    public void executeBeforeInsert() { executeBeforeUpsert(); }
    public void executeBeforeUpdate() { executeBeforeUpsert(); } 

    public void executeBeforeUpsert() {
        
        List<KS_Obra_Ubicacion__c> ouLst = (List<KS_Obra_Ubicacion__c>)lstNewItems;
        for (KS_Obra_Ubicacion__c ou : ouLst) {
            
            if (ou.KS_MarcaF__c != null) { ou.KS_Marca__c = ou.KS_MarcaF__c; }
            if (ou.KS_AreaF__c != null) { ou.KS_Area__c = ou.KS_AreaF__c; }
            if (ou.KS_DelegacionF__c != null) { ou.KS_Delegacion__c = ou.KS_DelegacionF__c; }
            if (ou.KS_ZonaF__c != null) { ou.KS_Zona__c = ou.KS_ZonaF__c; }
        }
    }
}