src/objects/KS_Obra__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Es el objeto superior que agrega las ofertas (oportunidades)</description>
    <label>Obra</label>
    <nameField>
        <label>Nombre de Obra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Obras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KS_Organizacion_Cliente__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto vinculado con las cuentas (marcas) que muestra las organizaciones de ventas para cada cliente</description>
    <label>Organización Cliente</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Nombre de Organización Cliente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizaciones Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>KS_Distribuidor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribuidor</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Distribuidores</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>KS_Distribuidores_SAP</value>
            </filterItems>
            <filterItems>
                <field>Account.KS_Grupo_de_ctas_deudor__c</field>
                <operation>notEqual</operation>
                <value>Destinatarios mercancías</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ofertas (Distribuidor)</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>KS_Obra__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Oportunidades</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KS_Obra__c</referenceTo>
        <relationshipLabel>Ofertas</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Organizacion_Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marca Comercial</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>KS_Organizacion_Cliente__c.KS_Cliente_solicitante__c</field>
                <operation>equals</operation>
                <valueField>$Source.KS_Distribuidor__c</valueField>
            </filterItems>
            <filterItems>
                <field>KS_Organizacion_Cliente__c.KS_Cliente_Distribucion__c</field>
                <operation>equals</operation>
                <valueField>$Source.KS_Distribuidor__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>KS_Organizacion_Cliente__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KS_Organizacion__c</fullName>
        <label>Organización de ventas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>KS_Dto_adicional_2__c</fullName>
        <label>Extra</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>KS_Material_sin_cargo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Material sin cargo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Obra__c</fullName>
        <formula>CASESAFEID(Opportunity.KS_Obra__c)</formula>
        <label>Obra</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>KS_Obra__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obra</label>
        <referenceTo>KS_Obra__c</referenceTo>
        <relationshipLabel>Productos</relationshipLabel>
        <relationshipName>Productos</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/KS_Organizacion_de_ventas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>FL31</fullName>
    </customValue>
    <customValue>
        <fullName>GI50</fullName>
    </customValue>
    <customValue>
        <fullName>IE20</fullName>
    </customValue>
    <customValue>
        <fullName>MA15</fullName>
    </customValue>
    <customValue>
        <fullName>MA16</fullName>
    </customValue>
    <customValue>
        <fullName>MX24</fullName>
    </customValue>
    <customValue>
        <fullName>MX25</fullName>
    </customValue>
    <customValue>
        <fullName>MX26</fullName>
    </customValue>
    <customValue>
        <fullName>SI10</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente / Jerarquia Cliente / Producto / Autorizaciones Oferta --&gt; CARGADO</description>
    <masterLabel>Organizacion de ventas</masterLabel>
</GlobalValueSet>

src/classes/KS_Oferta_TEST.cls
@isTest
public class KS_Oferta_TEST {

    @testSetup static void TEST_SETUP_KS_Oferta() {
        
        KS_Trigger_Test.disableTrigger();
        KS_Trigger_Test.testTrigger();
        Opportunity opp = [SELECT ID,KS_Distribuidor__c,KS_Organizacion_Cliente__c,KS_Organizacion__c,KS_Obra__c,Pricebook2Id FROM Opportunity LIMIT 1];
        
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);
        KS_Oferta_AddProductos_Controller oppAddProdCTRL = new KS_Oferta_AddProductos_Controller(sc);
        oppAddProdCTRL.productosADD = 4; oppAddProdCTRL.callAddProductos(); // lanzamos añadido de lineas
        oppAddProdCTRL.callAddFicha(); // lanzamos añadido de ficha nueva
        
        // AÑADIR PRODUCTO "PRODTEST1234"
        oppAddProdCTRL.productoLookup = [SELECT ID FROM Product2 LIMIT 1].ID;
        for (String k : oppAddProdCTRL.productosOferta.keySet()) { oppAddProdCTRL.productoIDROW = k; break; }
        oppAddProdCTRL.callDatosProducto();
        KS_Trigger_Test.enableTrigger();
    }
    
    public static testMethod void TEST_KS_Oferta() {
        
        KS_Trigger_Test.disableTrigger();
        Opportunity opp = [SELECT ID,KS_Distribuidor__c,KS_Organizacion_Cliente__c,KS_Organizacion__c,KS_Obra__c,Pricebook2Id FROM Opportunity LIMIT 1];
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);
        KS_Oferta_Controller control = new KS_Oferta_Controller(sc);
        control.fichaToEdit = 1;

        control.getEditOferta();
        control.getHasProductos();
        control.getFichas();
        control.getHaveOfertasPendientes();
        control.getPendientes();
        control.getCompetencias();
        control.getHaveEdit();
        control.getHaveErrorOferta();
        control.getHaveErrorFicha();
        control.getValidUser();
        control.getAdminUser();
        control.getOwnerUser();
        control.getManagerUser();
        control.getSubmitted();
        control.getApproval();
        control.getClosed();
        control.getLocked();
        control.getTerritorio();
        control.getOfertaRT();
        control.getGroupValid();
        control.enableEdit();
        control.validClienteOferta();
        control.setAgenteOferta();
        control.getOrgClienteByClienteID(opp.KS_Distribuidor__c);
        
        KS_Oferta_Controller.format2Decimal(1.1);
        KS_Trigger_Test.enableTrigger();
    }
    
    public static testMethod void TEST_KS_Oferta_fichas() {
        
        KS_Trigger_Test.disableTrigger();
        Opportunity opp = [SELECT ID,KS_Distribuidor__c,KS_Organizacion_Cliente__c,KS_Organizacion__c,KS_Obra__c,Pricebook2Id FROM Opportunity LIMIT 1];
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);
        KS_Oferta_Controller control = new KS_Oferta_Controller(sc);
        control.fichaToEdit = 1;

        control.save();
        control.saveFichas();
        control.addProducts();
        control.addProductsToFicha();
        control.duplicar();
        control.deleteFicha();
        control.setProductosFromOferta();
        control.setOfertasPendientes();
        control.cancelFichas();
        control.cancel();
        control.editMode();
        control.gotoPDF();
        control.setVariedadVolumenToProducto(new Set<ID>());
        control.unlock();
        control.editEtapaOferta();
        control.calculateCondicionesComerciales();
        control.resetCondicionProducto(new OpportunityLineItem());
        control.gotoDEMO();
        control.reload();
        control.getPrescribeDistribuidor();
        KS_Trigger_Test.enableTrigger();
    }
    
    public static testMethod void TEST_KS_Oferta_sendApproval() {
        
        KS_Trigger_Test.disableTrigger();
        Opportunity opp = [SELECT ID,KS_Distribuidor__c,KS_Organizacion_Cliente__c,KS_Organizacion__c,KS_Obra__c,Pricebook2Id FROM Opportunity LIMIT 1];
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);
        KS_Oferta_Controller control = new KS_Oferta_Controller(sc);
        control.fichaToEdit = 1;
        for (List<OpportunityLineItem> prodL : control.productosOferta.values()) {
            for (OpportunityLineItem prod : prodL) {
                prod.KS_Dto_adicional_2__c = 10;
                prod.KS_Material_sin_cargo__c = true;
            }
        }
        control.sendApproval();
        KS_Trigger_Test.enableTrigger();
    }
}