src/objects/KS_Oferta_express__c.object
<CustomObject>
    <description>KAIZENSTEP. ACTIVO. Objeto para recoger las condiciones de obra comentadas. Paso previo a una oferta</description>
    <fields>
        <fullName>KS_Dto_Cliente_final__c</fullName>
        <label>Dto. Cliente final</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>KS_Dto_Instalador__c</fullName>
        <label>Dto. Instalador</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>KS_Dto_adicional_1__c</fullName>
        <label>Dto. adicional 1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>KS_Dto_adicional_2__c</fullName>
        <label>Dto. adicional 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>KS_Dto_base_1__c</fullName>
        <label>Dto. base 1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>KS_Dto_base_2__c</fullName>
        <label>Dto. base 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>KS_Dto_total__c</fullName>
        <label>Dto. Total</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KS_Importe_bruto__c</fullName>
        <label>Importe bruto</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>KS_Importe_clientefinal__c</fullName>
        <label>Importe neto Cliente final</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>KS_Importe_instalador__c</fullName>
        <label>Importe neto Instalador</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>KS_Importe_neto__c</fullName>
        <label>Importe neto</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>KS_Margen__c</fullName>
        <label>Margen</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Oferta express</label>
    <nameField>
        <displayFormat>OFX - {000000}</displayFormat>
        <label>id OfertaX</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas express</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KS_OfertaExpress_Controller.cls
global with sharing class KS_OfertaExpress_Controller {
	
    public KS_Oferta_express__c oferta {get;set;} // Objeto principal
    public KS_OfertaExpress_Controller(ApexPages.StandardController controller) {
        
        oferta = (KS_Oferta_express__c)controller.getRecord();
        // SELECT Id, KS_Dto_Cliente_final__c, KS_Dto_Instalador__c, KS_Dto_adicional_1__c, KS_Dto_adicional_2__c, KS_Dto_base_1__c, KS_Dto_base_2__c, KS_Importe_bruto__c, KS_Importe_neto__c FROM KS_Oferta_express__c
        if (oferta.ID!=null) {
            oferta = [SELECT Id, KS_Dto_Cliente_final__c, KS_Dto_Instalador__c, KS_Dto_adicional_1__c, KS_Dto_adicional_2__c, 
                      KS_Dto_base_1__c, KS_Dto_base_2__c, KS_Importe_bruto__c, KS_Importe_neto__c, KS_Dto_total__c, KS_Margen__c,
                      KS_Importe_clientefinal__c, KS_Importe_instalador__c
                      FROM KS_Oferta_express__c];
        }
    }
}