src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>KS_Agente_de_contabilizacion__c</fullName>
        <label>Agente de contabilización</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KS_Contabiliza__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Contabilizacion</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Contabiliza__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contabiliza</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Prescrito__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prescrito</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KS_Probabilidad__c</fullName>
        <label>Probabilidad (%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>KS_Sincronizacion__c</fullName>
        <label>Sincronización</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KS_Organizacion_de_ventas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>KS_Subetapa__c</fullName>
        <label>Subetapa</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetName>KS_Subetapa</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>KS_Oferta</fullName>
        <active>true</active>
        <businessProcess>Simon</businessProcess>
        <label>Oferta</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/KS_Contabilizacion.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Distribuidor</fullName>
    </customValue>
    <customValue>
        <fullName>Instalador</fullName>
    </customValue>
    <customValue>
        <fullName>Cliente final</fullName>
    </customValue>
    <description>En uso --&gt; Oferta, para indicar el agente donde contabiliza</description>
    <masterLabel>Contabilizacion</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Organizacion_de_ventas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>FL31</fullName>
    </customValue>
    <customValue>
        <fullName>GI50</fullName>
    </customValue>
    <customValue>
        <fullName>IE20</fullName>
    </customValue>
    <customValue>
        <fullName>MA15</fullName>
    </customValue>
    <customValue>
        <fullName>MA16</fullName>
    </customValue>
    <customValue>
        <fullName>MX24</fullName>
    </customValue>
    <customValue>
        <fullName>MX25</fullName>
    </customValue>
    <customValue>
        <fullName>MX26</fullName>
    </customValue>
    <customValue>
        <fullName>SI10</fullName>
    </customValue>
    <description>SAP. Uso --&gt; Organizaciones Cliente / Jerarquia Cliente / Producto / Autorizaciones Oferta --&gt; CARGADO</description>
    <masterLabel>Organizacion de ventas</masterLabel>
</GlobalValueSet>

src/globalValueSets/KS_Subetapa.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>S1</fullName>
    </customValue>
    <customValue>
        <fullName>S2</fullName>
    </customValue>
    <customValue>
        <fullName>S3</fullName>
    </customValue>
    <customValue>
        <fullName>Planificación Proyecto</fullName>
    </customValue>
    <customValue>
        <fullName>Desarrollo</fullName>
    </customValue>
    <customValue>
        <fullName>Entrega</fullName>
    </customValue>
    <description>Uso --&gt; Usado en el objeto Oportunidad</description>
    <masterLabel>Subetapa</masterLabel>
</GlobalValueSet>

src/classes/KS_OfertaEtapa_Controller.cls
public without sharing class KS_OfertaEtapa_Controller {

    public Opportunity oferta {get;set;}
    public String errorTextOferta {get;set;}
    public Boolean getHaveErrorOferta() {
        return errorTextOferta !=null&&errorTextOferta !='';
    }
    public Boolean getContabilizaDistribuidor() {
        return oferta != null && oferta.KS_Agente_de_contabilizacion__c != null
            && oferta.KS_Agente_de_contabilizacion__c == 'Distribuidor';
    } 
    public Boolean getPrescribeDistribuidor() {
        return oferta != null && getContabilizaDistribuidor() && oferta.KS_Prescrito__c;
    }
    public Boolean yaPrescrito {get;set;}
    
    public KS_OfertaEtapa_Controller(ApexPages.StandardController controller) {
        
        oferta = (Opportunity)controller.getRecord();
        if (oferta.ID != null) {
            oferta = [SELECT ID, Name, StageName, KS_Subetapa__c, KS_Sincronizacion__c,
                      KS_Probabilidad__c, CloseDate, KS_Prescrito__c,
                      KS_Contabiliza__c, KS_Agente_de_contabilizacion__c
                      FROM Opportunity WHERE ID = :oferta.ID];
            yaPrescrito = oferta.KS_Prescrito__c;
        }
    }
    
    public PageReference editEtapaOferta() {
        
        errorTextOferta = '';
        if (getClosed()) { oferta.KS_Contabiliza__c = true; }
        if (oferta.KS_Contabiliza__c && oferta.KS_Agente_de_contabilizacion__c == null) {
            errorTextOferta = 'Error en oferta "'+oferta.Name+'": Debe seleccionarse agente de contabilización.';
            oferta.addError(errorTextOferta);
            return null;
        }
        oferta.KS_Prescrito__c = checkPrescrito();
        
        try {
            
            System.Approval.unlock(oferta, true);
        	update oferta;  
            System.Approval.lock(oferta, true);

        } catch(Exception e) {
            
            errorTextOferta = e.getMessage();
            return null;
        }
        
        return gotoOferta();
    }
    
    public PageReference cancel() {
        return gotoOferta();
    }
    
    private PageReference gotoOferta() {
        PageReference pageRef = new PageReference( '/apex/KS_Oferta?id=' + oferta.Id);
        pageRef.SetRedirect(true);
        return pageRef; 
    }
    
    public Boolean getClosed() {
        return oferta != null && 
            (oferta.StageName.containsIgnoreCase('Adjudicada') ||
             oferta.StageName.containsIgnoreCase('Perdida')
            )
            && !oferta.StageName.containsIgnoreCase('otro Distribuidor');
    }
    
    public void reload(){ 
        System.debug('-- KS_OfertaEtapa RELOAD --');
        oferta.KS_Prescrito__c = checkPrescrito();//oferta.KS_Agente_de_contabilizacion__c == 'Cliente final' || getPrescribeDistribuidor() || yaPrescrito;
    }
    
    public Boolean checkPrescrito() { return oferta != null && oferta.KS_Prescrito__c;/*&& checkPrescritoAgente() && oferta.KS_Contabiliza__c;*/ }
    public Boolean checkPrescritoAgente() {
        if (oferta != null && oferta.KS_Agente_de_contabilizacion__c != null
            && oferta.KS_Agente_de_contabilizacion__c == 'Cliente final') { return true; }
        if (oferta != null && oferta.KS_Agente_de_contabilizacion__c != null
            && oferta.KS_Agente_de_contabilizacion__c == 'Distribuidor') { return oferta.KS_Prescrito__c; }
        if (oferta != null && oferta.KS_Agente_de_contabilizacion__c != null
            && oferta.KS_Agente_de_contabilizacion__c == 'Instalador') { return oferta.KS_Prescrito__c; }
        return false;
    }
    
    public static Boolean getIsAdmin() {
        if (UserInfo.getUserEmail()=='jrius@simon.es') {return true;}
        if (UserInfo.getUserEmail()=='jmarchena@simon.es') {return true;}
        if (UserInfo.getUserEmail()=='psamo@simon.es') {return true;}
        if (UserInfo.getUserEmail()=='customers@kaizenstep.com') {return true;}
        return false;
    }
}